// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddPropertyReducer from "./add_property_reducer";
import ApplyYjsUpdateReducer from "./apply_yjs_update_reducer";
import ClearPropertyValueReducer from "./clear_property_value_reducer";
import CreateDatabaseSchemaReducer from "./create_database_schema_reducer";
import CreatePageReducer from "./create_page_reducer";
import CreateViewReducer from "./create_view_reducer";
import DeletePageReducer from "./delete_page_reducer";
import DeletePropertyReducer from "./delete_property_reducer";
import DeleteViewReducer from "./delete_view_reducer";
import LoginReducer from "./login_reducer";
import LogoutReducer from "./logout_reducer";
import RegisterReducer from "./register_reducer";
import RenamePropertyReducer from "./rename_property_reducer";
import RenameViewReducer from "./rename_view_reducer";
import ReorderPropertyReducer from "./reorder_property_reducer";
import RestorePageReducer from "./restore_page_reducer";
import RestorePageToSnapshotReducer from "./restore_page_to_snapshot_reducer";
import SetDefaultViewReducer from "./set_default_view_reducer";
import SetPropertyValueReducer from "./set_property_value_reducer";
import SetUserProfileReducer from "./set_user_profile_reducer";
import TakeSnapshotReducer from "./take_snapshot_reducer";
import UpdatePageContentReducer from "./update_page_content_reducer";
import UpdatePageTitleReducer from "./update_page_title_reducer";
import UpdatePropertyConfigReducer from "./update_property_config_reducer";
import UpdatePropertyTypeReducer from "./update_property_type_reducer";
import UpdateViewConfigReducer from "./update_view_config_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import DatabaseSchemaRow from "./database_schema_table";
import DatabaseViewRow from "./database_view_table";
import PageRow from "./page_table";
import PageContentRow from "./page_content_table";
import PagePropertyValueRow from "./page_property_value_table";
import PagePropertyValueHistoryRow from "./page_property_value_history_table";
import PageSnapshotRow from "./page_snapshot_table";
import PageYjsUpdateRow from "./page_yjs_update_table";
import PropertyDefinitionRow from "./property_definition_table";
import UserRow from "./user_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  database_schema: __table({
    name: 'database_schema',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_schema_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseSchemaRow),
  database_view: __table({
    name: 'database_view',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_view_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseViewRow),
  page: __table({
    name: 'page',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'parent_id', algorithm: 'btree', columns: [
        'parentId',
      ] },
    ],
    constraints: [
      { name: 'page_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageRow),
  page_content: __table({
    name: 'page_content',
    indexes: [
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_content_page_id_key', constraint: 'unique', columns: ['pageId'] },
    ],
  }, PageContentRow),
  page_property_value: __table({
    name: 'page_property_value',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { name: 'property_definition_id', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
    ],
    constraints: [
      { name: 'page_property_value_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagePropertyValueRow),
  page_property_value_history: __table({
    name: 'page_property_value_history',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { name: 'property_definition_id', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
    ],
    constraints: [
      { name: 'page_property_value_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagePropertyValueHistoryRow),
  page_snapshot: __table({
    name: 'page_snapshot',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_snapshot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageSnapshotRow),
  page_yjs_update: __table({
    name: 'page_yjs_update',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_yjs_update_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageYjsUpdateRow),
  property_definition: __table({
    name: 'property_definition',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'schema_id', algorithm: 'btree', columns: [
        'schemaId',
      ] },
    ],
    constraints: [
      { name: 'property_definition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PropertyDefinitionRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_property", AddPropertyReducer),
  __reducerSchema("apply_yjs_update", ApplyYjsUpdateReducer),
  __reducerSchema("clear_property_value", ClearPropertyValueReducer),
  __reducerSchema("create_database_schema", CreateDatabaseSchemaReducer),
  __reducerSchema("create_page", CreatePageReducer),
  __reducerSchema("create_view", CreateViewReducer),
  __reducerSchema("delete_page", DeletePageReducer),
  __reducerSchema("delete_property", DeletePropertyReducer),
  __reducerSchema("delete_view", DeleteViewReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("rename_property", RenamePropertyReducer),
  __reducerSchema("rename_view", RenameViewReducer),
  __reducerSchema("reorder_property", ReorderPropertyReducer),
  __reducerSchema("restore_page", RestorePageReducer),
  __reducerSchema("restore_page_to_snapshot", RestorePageToSnapshotReducer),
  __reducerSchema("set_default_view", SetDefaultViewReducer),
  __reducerSchema("set_property_value", SetPropertyValueReducer),
  __reducerSchema("set_user_profile", SetUserProfileReducer),
  __reducerSchema("take_snapshot", TakeSnapshotReducer),
  __reducerSchema("update_page_content", UpdatePageContentReducer),
  __reducerSchema("update_page_title", UpdatePageTitleReducer),
  __reducerSchema("update_property_config", UpdatePropertyConfigReducer),
  __reducerSchema("update_property_type", UpdatePropertyTypeReducer),
  __reducerSchema("update_view_config", UpdateViewConfigReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

