// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActorType,
  SnapshotType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  pageId: __t.u64().name("page_id"),
  title: __t.string(),
  content: __t.string(),
  snapshotAt: __t.timestamp().name("snapshot_at"),
  get createdBy() {
    return ActorType.name("created_by");
  },
  get snapshotType() {
    return SnapshotType.name("snapshot_type");
  },
});
