// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PropertyType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  schemaId: __t.u64().name("schema_id"),
  name: __t.string(),
  get propertyType() {
    return PropertyType.name("property_type");
  },
  config: __t.string(),
  order: __t.u32(),
});
