//! Automations: typed trigger/action graphs, event queue, dry-run execution,
//! and scheduled routines.
//!
//! This is the v0 substrate. Live side effects intentionally remain behind the
//! queue boundary; dry-run execution is available immediately so humans and AI
//! users can draft, validate, simulate, and inspect automations safely.

use std::time::Duration;

use chrono::{Datelike, Timelike, Utc};
use serde_json::{json, Value};
use spacetimedb::{
    reducer, table, Identity, ReducerContext, ScheduleAt, SpacetimeType, Table, Timestamp,
};

use crate::access_control::helpers::require_creator_or_admin;
use crate::id_counters::alloc_id;
use crate::pages::{page, PageType};

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationTriggerKind {
    PageCreated,
    PageUpdated,
    PageDeleted,
    PropertyChanged,
    Scheduled,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationScheduleKind {
    None,
    Interval,
    OneShot,
    Cron,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationMode {
    DryRun,
    Live,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationActionKind {
    HttpRequest,
    SendEmail,
    CreatePage,
    UpdateProperty,
    OrchaJob,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationCapabilityKind {
    ReadPage,
    WritePage,
    HttpOutbound,
    SendEmail,
    SpendAiTokens,
    SpawnOrchaJob,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationConditionKind {
    PayloadFieldEquals,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationEventStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Skipped,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationPrimitiveKind {
    Trigger,
    Action,
    Condition,
    Capability,
}

/// A user- or AI-authored automation rule. Rules default to dry-run and disabled.
#[table(accessor = automation_rule, public)]
pub struct AutomationRule {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub name: String,
    pub enabled: bool,
    pub mode: AutomationMode,
    pub trigger_kind: AutomationTriggerKind,
    /// JSON config scoped to the trigger. Examples:
    /// - PageCreated: {"parent_id": 12}
    /// - PropertyChanged: {"property_definition_id": 42}
    pub trigger_config: String,
    pub schedule_kind: AutomationScheduleKind,
    /// JSON schedule config. Interval: {"interval_seconds": 3600}; one-shot:
    /// {"run_at_micros": 1770000000000000}; cron: {"expression": "0 9 * * 1"}.
    pub schedule_config: String,
    /// Stored now so the review surface is future-proof. Cron v0 evaluates in UTC.
    pub timezone: String,
    pub next_run_at: Option<Timestamp>,
    pub last_run_at: Option<Timestamp>,
    pub max_ticks: Option<u64>,
    pub tick_count: u64,
    pub expires_at: Option<Timestamp>,
    /// The principal whose authority live execution will use. Defaults to creator.
    pub run_as: Identity,
    pub created_by: Identity,
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
    /// Canonical human review string, generated by UI or AI alongside the graph.
    pub canonical_description: String,
}

#[table(accessor = automation_action, public, index(accessor = by_rule, btree(columns = [automation_id])))]
pub struct AutomationAction {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub automation_id: u64,
    pub order: u32,
    pub action_kind: AutomationActionKind,
    /// JSON config specific to action_kind. Dry-run logs this verbatim.
    pub config: String,
}

#[table(accessor = automation_condition, public, index(accessor = by_rule, btree(columns = [automation_id])))]
pub struct AutomationCondition {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub automation_id: u64,
    pub order: u32,
    pub condition_kind: AutomationConditionKind,
    /// PayloadFieldEquals: {"field": "page_id", "equals": "123"}.
    pub config: String,
}

#[table(accessor = automation_capability, public, index(accessor = by_rule, btree(columns = [automation_id])))]
pub struct AutomationCapability {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub automation_id: u64,
    pub capability_kind: AutomationCapabilityKind,
    /// JSON scope, e.g. {"page_id": 12}, {"host": "hooks.slack.com"}, {"monthly_tokens": 10000}.
    pub scope_config: String,
}

#[table(accessor = automation_event_queue, public, index(accessor = by_rule, btree(columns = [automation_id])))]
pub struct AutomationEventQueue {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub automation_id: u64,
    pub trigger_kind: AutomationTriggerKind,
    pub trigger_payload: String,
    pub status: AutomationEventStatus,
    pub attempts: u32,
    pub claimed_by: Option<String>,
    pub error: Option<String>,
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
}

#[table(accessor = automation_run_log, public, index(accessor = by_queue, btree(columns = [queue_id])))]
pub struct AutomationRunLog {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub queue_id: u64,
    pub action_id: Option<u64>,
    pub success: bool,
    pub dry_run: bool,
    pub message: String,
    pub result_json: String,
    pub created_at: Timestamp,
}

/// AI/user-facing registry of primitives the automation authoring tools may use.
#[table(accessor = automation_primitive, public)]
pub struct AutomationPrimitive {
    #[primary_key]
    pub name: String,
    pub primitive_kind: AutomationPrimitiveKind,
    pub title: String,
    pub description: String,
    pub config_schema_json: String,
}

#[table(accessor = automation_schedule_job, scheduled(run_scheduled_automation))]
pub struct AutomationScheduleJob {
    #[primary_key]
    #[auto_inc]
    pub scheduled_id: u64,
    pub scheduled_at: ScheduleAt,
    pub automation_id: u64,
}

#[table(accessor = automation_cron_tick, scheduled(run_automation_cron_tick))]
pub struct AutomationCronTick {
    #[primary_key]
    #[auto_inc]
    pub scheduled_id: u64,
    pub scheduled_at: ScheduleAt,
}

pub(crate) fn next_automation_rule_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_rule", || {
        ctx.db
            .automation_rule()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_action_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_action", || {
        ctx.db
            .automation_action()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_condition_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_condition", || {
        ctx.db
            .automation_condition()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_capability_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_capability", || {
        ctx.db
            .automation_capability()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_event_queue_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_event_queue", || {
        ctx.db
            .automation_event_queue()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_run_log_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_run_log", || {
        ctx.db
            .automation_run_log()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn seed_automation_primitives_inner(ctx: &ReducerContext) {
    let primitives = [
        (
            "trigger.page_created",
            AutomationPrimitiveKind::Trigger,
            "Page created",
            "Runs when a page or database row is created.",
            r#"{"type":"object","properties":{"page_id":{"type":"integer"},"parent_id":{"type":"integer"}}}"#,
        ),
        (
            "trigger.page_updated",
            AutomationPrimitiveKind::Trigger,
            "Page updated",
            "Runs when page title or content changes.",
            r#"{"type":"object","properties":{"page_id":{"type":"integer"},"parent_id":{"type":"integer"}}}"#,
        ),
        (
            "trigger.page_deleted",
            AutomationPrimitiveKind::Trigger,
            "Page deleted",
            "Runs when a page or database row is soft-deleted.",
            r#"{"type":"object","properties":{"page_id":{"type":"integer"},"parent_id":{"type":"integer"}}}"#,
        ),
        (
            "trigger.property_changed",
            AutomationPrimitiveKind::Trigger,
            "Property changed",
            "Runs when a database row property changes.",
            r#"{"type":"object","properties":{"page_id":{"type":"integer"},"property_definition_id":{"type":"integer"}}}"#,
        ),
        (
            "trigger.scheduled",
            AutomationPrimitiveKind::Trigger,
            "Scheduled",
            "Runs on an interval, one-shot timestamp, or five-field UTC cron expression.",
            r#"{"type":"object","properties":{"interval_seconds":{"type":"integer"},"run_at_micros":{"type":"integer"},"expression":{"type":"string"}}}"#,
        ),
        (
            "action.http_request",
            AutomationPrimitiveKind::Action,
            "HTTP request",
            "Posts to an external URL. Dry-run only in v0.",
            r#"{"type":"object","properties":{"url":{"type":"string"},"headers":{"type":"object"},"body_template":{"type":"string"}}}"#,
        ),
        (
            "action.send_email",
            AutomationPrimitiveKind::Action,
            "Send email",
            "Sends an SMTP email. Dry-run only in v0.",
            r#"{"type":"object","properties":{"to":{"type":"string"},"subject_template":{"type":"string"},"body_template":{"type":"string"}}}"#,
        ),
        (
            "action.create_page",
            AutomationPrimitiveKind::Action,
            "Create page",
            "Creates a page or database row. Dry-run only in v0.",
            r#"{"type":"object","properties":{"parent_id":{"type":"integer"},"title_template":{"type":"string"}}}"#,
        ),
        (
            "action.update_property",
            AutomationPrimitiveKind::Action,
            "Update property",
            "Sets a property value on a row. Dry-run only in v0.",
            r#"{"type":"object","properties":{"property_definition_id":{"type":"integer"},"value":{"type":"object"}}}"#,
        ),
        (
            "action.orcha_job",
            AutomationPrimitiveKind::Action,
            "Orcha job",
            "Creates an AI job from the trigger payload. Dry-run only in v0.",
            r#"{"type":"object","properties":{"prompt_template":{"type":"string"},"page_id_field":{"type":"string"}}}"#,
        ),
        (
            "condition.payload_field_equals",
            AutomationPrimitiveKind::Condition,
            "Payload field equals",
            "Checks a top-level trigger payload field against a value.",
            r#"{"type":"object","properties":{"field":{"type":"string"},"equals":{"type":"string"}},"required":["field","equals"]}"#,
        ),
    ];

    for (name, primitive_kind, title, description, config_schema_json) in primitives {
        let row = AutomationPrimitive {
            name: name.to_string(),
            primitive_kind,
            title: title.to_string(),
            description: description.to_string(),
            config_schema_json: config_schema_json.to_string(),
        };
        if ctx
            .db
            .automation_primitive()
            .name()
            .find(row.name.clone())
            .is_some()
        {
            ctx.db.automation_primitive().name().update(row);
        } else {
            ctx.db.automation_primitive().insert(row);
        }
    }
}

#[reducer]
pub fn create_automation_draft(
    ctx: &ReducerContext,
    name: String,
    trigger_kind: AutomationTriggerKind,
    trigger_config: String,
    schedule_kind: AutomationScheduleKind,
    schedule_config: String,
    timezone: String,
    canonical_description: String,
) -> Result<(), String> {
    if name.trim().is_empty() {
        return Err("Automation name cannot be empty".to_string());
    }
    parse_json_object(&trigger_config, "trigger_config")?;
    parse_json_object(&schedule_config, "schedule_config")?;

    ctx.db.automation_rule().insert(AutomationRule {
        id: next_automation_rule_id(ctx),
        name: name.trim().to_string(),
        enabled: false,
        mode: AutomationMode::DryRun,
        trigger_kind,
        trigger_config,
        schedule_kind,
        schedule_config,
        timezone: normalize_timezone(timezone),
        next_run_at: None,
        last_run_at: None,
        max_ticks: None,
        tick_count: 0,
        expires_at: None,
        run_as: ctx.sender(),
        created_by: ctx.sender(),
        created_at: ctx.timestamp,
        updated_at: ctx.timestamp,
        canonical_description,
    });
    Ok(())
}

#[reducer]
pub fn update_automation_rule(
    ctx: &ReducerContext,
    automation_id: u64,
    name: String,
    trigger_kind: AutomationTriggerKind,
    trigger_config: String,
    schedule_kind: AutomationScheduleKind,
    schedule_config: String,
    timezone: String,
    canonical_description: String,
) -> Result<(), String> {
    parse_json_object(&trigger_config, "trigger_config")?;
    parse_json_object(&schedule_config, "schedule_config")?;
    let rule = require_rule_owner(ctx, automation_id, "update automation")?;
    ctx.db.automation_rule().id().update(AutomationRule {
        name: name.trim().to_string(),
        trigger_kind,
        trigger_config,
        schedule_kind,
        schedule_config,
        timezone: normalize_timezone(timezone),
        canonical_description,
        enabled: false,
        next_run_at: None,
        updated_at: ctx.timestamp,
        ..rule
    });
    delete_schedule_jobs_for_rule(ctx, automation_id);
    Ok(())
}

#[reducer]
pub fn set_automation_limits(
    ctx: &ReducerContext,
    automation_id: u64,
    max_ticks: Option<u64>,
    expires_at: Option<Timestamp>,
) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "set automation limits")?;
    ctx.db.automation_rule().id().update(AutomationRule {
        max_ticks,
        expires_at,
        updated_at: ctx.timestamp,
        ..rule
    });
    Ok(())
}

#[reducer]
pub fn set_automation_mode(
    ctx: &ReducerContext,
    automation_id: u64,
    mode: AutomationMode,
) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "set automation mode")?;
    if mode == AutomationMode::Live {
        return Err(
            "Live automation execution is not enabled in v0; keep the rule in DryRun".to_string(),
        );
    }
    ctx.db.automation_rule().id().update(AutomationRule {
        mode,
        updated_at: ctx.timestamp,
        ..rule
    });
    Ok(())
}

#[reducer]
pub fn add_automation_action(
    ctx: &ReducerContext,
    automation_id: u64,
    order: u32,
    action_kind: AutomationActionKind,
    config: String,
) -> Result<(), String> {
    require_rule_owner(ctx, automation_id, "add automation actions")?;
    parse_json_object(&config, "action config")?;
    ctx.db.automation_action().insert(AutomationAction {
        id: next_automation_action_id(ctx),
        automation_id,
        order,
        action_kind,
        config,
    });
    Ok(())
}

#[reducer]
pub fn update_automation_action(
    ctx: &ReducerContext,
    action_id: u64,
    order: u32,
    action_kind: AutomationActionKind,
    config: String,
) -> Result<(), String> {
    parse_json_object(&config, "action config")?;
    let action = ctx
        .db
        .automation_action()
        .id()
        .find(action_id)
        .ok_or("Automation action not found")?;
    require_rule_owner(ctx, action.automation_id, "update automation actions")?;
    ctx.db.automation_action().id().update(AutomationAction {
        order,
        action_kind,
        config,
        ..action
    });
    Ok(())
}

#[reducer]
pub fn delete_automation_action(ctx: &ReducerContext, action_id: u64) -> Result<(), String> {
    let action = ctx
        .db
        .automation_action()
        .id()
        .find(action_id)
        .ok_or("Automation action not found")?;
    require_rule_owner(ctx, action.automation_id, "delete automation actions")?;
    ctx.db.automation_action().id().delete(action_id);
    Ok(())
}

#[reducer]
pub fn add_automation_condition(
    ctx: &ReducerContext,
    automation_id: u64,
    order: u32,
    condition_kind: AutomationConditionKind,
    config: String,
) -> Result<(), String> {
    require_rule_owner(ctx, automation_id, "add automation conditions")?;
    parse_json_object(&config, "condition config")?;
    ctx.db.automation_condition().insert(AutomationCondition {
        id: next_automation_condition_id(ctx),
        automation_id,
        order,
        condition_kind,
        config,
    });
    Ok(())
}

#[reducer]
pub fn add_automation_capability(
    ctx: &ReducerContext,
    automation_id: u64,
    capability_kind: AutomationCapabilityKind,
    scope_config: String,
) -> Result<(), String> {
    require_rule_owner(ctx, automation_id, "add automation capabilities")?;
    parse_json_object(&scope_config, "capability scope_config")?;
    ctx.db.automation_capability().insert(AutomationCapability {
        id: next_automation_capability_id(ctx),
        automation_id,
        capability_kind,
        scope_config,
    });
    Ok(())
}

#[reducer]
pub fn validate_automation(ctx: &ReducerContext, automation_id: u64) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "validate automation")?;
    validate_rule(ctx, &rule)
}

#[reducer]
pub fn enable_automation(ctx: &ReducerContext, automation_id: u64) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "enable automation")?;
    validate_rule(ctx, &rule)?;
    delete_schedule_jobs_for_rule(ctx, automation_id);
    let next_run_at = schedule_rule_if_needed(ctx, &rule)?;
    ctx.db.automation_rule().id().update(AutomationRule {
        enabled: true,
        next_run_at,
        updated_at: ctx.timestamp,
        ..rule
    });
    Ok(())
}

#[reducer]
pub fn disable_automation(ctx: &ReducerContext, automation_id: u64) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "disable automation")?;
    delete_schedule_jobs_for_rule(ctx, automation_id);
    ctx.db.automation_rule().id().update(AutomationRule {
        enabled: false,
        next_run_at: None,
        updated_at: ctx.timestamp,
        ..rule
    });
    stop_cron_tick_if_unused(ctx);
    Ok(())
}

#[reducer]
pub fn delete_automation(ctx: &ReducerContext, automation_id: u64) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "delete automation")?;
    delete_schedule_jobs_for_rule(ctx, automation_id);
    for a in ctx
        .db
        .automation_action()
        .by_rule()
        .filter(&automation_id)
        .collect::<Vec<_>>()
    {
        ctx.db.automation_action().id().delete(a.id);
    }
    for c in ctx
        .db
        .automation_condition()
        .by_rule()
        .filter(&automation_id)
        .collect::<Vec<_>>()
    {
        ctx.db.automation_condition().id().delete(c.id);
    }
    for cap in ctx
        .db
        .automation_capability()
        .by_rule()
        .filter(&automation_id)
        .collect::<Vec<_>>()
    {
        ctx.db.automation_capability().id().delete(cap.id);
    }
    ctx.db.automation_rule().id().delete(rule.id);
    stop_cron_tick_if_unused(ctx);
    Ok(())
}

/// Process one queued event. In v0 this executes dry-run actions only.
#[reducer]
pub fn process_automation_event(ctx: &ReducerContext, queue_id: u64) -> Result<(), String> {
    let event = ctx
        .db
        .automation_event_queue()
        .id()
        .find(queue_id)
        .ok_or("Automation event not found")?;
    let rule = ctx
        .db
        .automation_rule()
        .id()
        .find(event.automation_id)
        .ok_or("Automation rule not found")?;
    require_creator_or_admin(ctx, rule.created_by, "process automation events")?;
    process_automation_event_inner(ctx, queue_id, Some("manual".to_string()))
}

/// Process pending events without needing a dedicated worker yet.
#[reducer]
pub fn process_pending_automation_events(ctx: &ReducerContext, limit: u32) -> Result<(), String> {
    let max = limit.clamp(1, 100);
    let events: Vec<u64> = ctx
        .db
        .automation_event_queue()
        .iter()
        .filter(|e| e.status == AutomationEventStatus::Pending)
        .take(max as usize)
        .map(|e| e.id)
        .collect();

    for queue_id in events {
        if let Some(event) = ctx.db.automation_event_queue().id().find(queue_id) {
            if let Some(rule) = ctx.db.automation_rule().id().find(event.automation_id) {
                require_creator_or_admin(ctx, rule.created_by, "process automation events")?;
                process_automation_event_inner(ctx, queue_id, Some("manual-batch".to_string()))?;
            }
        }
    }
    Ok(())
}

#[reducer]
pub fn run_scheduled_automation(
    ctx: &ReducerContext,
    job: AutomationScheduleJob,
) -> Result<(), String> {
    let Some(rule) = ctx.db.automation_rule().id().find(job.automation_id) else {
        return Ok(());
    };
    if !rule.enabled || rule.trigger_kind != AutomationTriggerKind::Scheduled {
        return Ok(());
    }
    if rule_is_expired(ctx, &rule) {
        disable_automation_inner(ctx, rule);
        return Ok(());
    }

    enqueue_scheduled_event(ctx, &rule, "schedule")?;
    bump_scheduled_rule(ctx, rule);
    Ok(())
}

#[reducer]
pub fn run_automation_cron_tick(
    ctx: &ReducerContext,
    _job: AutomationCronTick,
) -> Result<(), String> {
    let due: Vec<u64> = ctx
        .db
        .automation_rule()
        .iter()
        .filter(|r| {
            r.enabled
                && r.trigger_kind == AutomationTriggerKind::Scheduled
                && r.schedule_kind == AutomationScheduleKind::Cron
                && !rule_is_expired(ctx, r)
                && cron_rule_due(r, ctx.timestamp)
        })
        .map(|r| r.id)
        .collect();

    for automation_id in due {
        if let Some(rule) = ctx.db.automation_rule().id().find(automation_id) {
            enqueue_scheduled_event(ctx, &rule, "cron")?;
            bump_scheduled_rule(ctx, rule);
        }
    }
    stop_cron_tick_if_unused(ctx);
    Ok(())
}

pub(crate) fn enqueue_page_created(ctx: &ReducerContext, page_id: u64) {
    if let Some(page) = ctx.db.page().id().find(page_id) {
        let payload = json!({
            "event_type": "page_created",
            "page_id": page.id,
            "parent_id": page.parent_id,
            "parent_pk": page.parent_pk,
            "page_type": page_type_name(&page.page_type),
            "title": page.title,
        });
        let _ = enqueue_matching_automations(ctx, AutomationTriggerKind::PageCreated, payload);
    }
}

pub(crate) fn enqueue_page_updated(ctx: &ReducerContext, page_id: u64) {
    if let Some(page) = ctx.db.page().id().find(page_id) {
        let payload = json!({
            "event_type": "page_updated",
            "page_id": page.id,
            "parent_id": page.parent_id,
            "parent_pk": page.parent_pk,
            "page_type": page_type_name(&page.page_type),
            "title": page.title,
        });
        let _ = enqueue_matching_automations(ctx, AutomationTriggerKind::PageUpdated, payload);
    }
}

pub(crate) fn enqueue_page_deleted(ctx: &ReducerContext, page_id: u64) {
    if let Some(page) = ctx.db.page().id().find(page_id) {
        let payload = json!({
            "event_type": "page_deleted",
            "page_id": page.id,
            "parent_id": page.parent_id,
            "parent_pk": page.parent_pk,
            "page_type": page_type_name(&page.page_type),
            "title": page.title,
        });
        let _ = enqueue_matching_automations(ctx, AutomationTriggerKind::PageDeleted, payload);
    }
}

pub(crate) fn enqueue_property_changed(
    ctx: &ReducerContext,
    page_id: u64,
    property_definition_id: u64,
) {
    let payload = json!({
        "event_type": "property_changed",
        "page_id": page_id,
        "property_definition_id": property_definition_id,
    });
    let _ = enqueue_matching_automations(ctx, AutomationTriggerKind::PropertyChanged, payload);
}

fn enqueue_matching_automations(
    ctx: &ReducerContext,
    trigger_kind: AutomationTriggerKind,
    payload: Value,
) -> Result<(), String> {
    let rules: Vec<AutomationRule> = ctx
        .db
        .automation_rule()
        .iter()
        .filter(|r| {
            r.enabled && r.trigger_kind == trigger_kind && trigger_matches_payload(r, &payload)
        })
        .collect();

    for rule in rules {
        let queue_id = insert_event(ctx, &rule, trigger_kind.clone(), payload.to_string());
        if rule.mode == AutomationMode::DryRun {
            process_automation_event_inner(ctx, queue_id, Some("inline-dry-run".to_string()))?;
        }
    }
    Ok(())
}

fn enqueue_scheduled_event(
    ctx: &ReducerContext,
    rule: &AutomationRule,
    source: &str,
) -> Result<(), String> {
    let payload = json!({
        "event_type": "scheduled",
        "source": source,
        "automation_id": rule.id,
        "tick_count": rule.tick_count + 1,
        "scheduled_at_micros": ctx.timestamp.to_micros_since_unix_epoch(),
    });
    let queue_id = insert_event(
        ctx,
        rule,
        AutomationTriggerKind::Scheduled,
        payload.to_string(),
    );
    if rule.mode == AutomationMode::DryRun {
        process_automation_event_inner(ctx, queue_id, Some(format!("{source}-dry-run")))?;
    }
    Ok(())
}

fn insert_event(
    ctx: &ReducerContext,
    rule: &AutomationRule,
    trigger_kind: AutomationTriggerKind,
    trigger_payload: String,
) -> u64 {
    let row = ctx
        .db
        .automation_event_queue()
        .insert(AutomationEventQueue {
            id: next_automation_event_queue_id(ctx),
            automation_id: rule.id,
            trigger_kind,
            trigger_payload,
            status: AutomationEventStatus::Pending,
            attempts: 0,
            claimed_by: None,
            error: None,
            created_at: ctx.timestamp,
            updated_at: ctx.timestamp,
        });
    row.id
}

fn process_automation_event_inner(
    ctx: &ReducerContext,
    queue_id: u64,
    claimed_by: Option<String>,
) -> Result<(), String> {
    let event = ctx
        .db
        .automation_event_queue()
        .id()
        .find(queue_id)
        .ok_or("Automation event not found")?;
    if event.status == AutomationEventStatus::Completed
        || event.status == AutomationEventStatus::Failed
        || event.status == AutomationEventStatus::Skipped
    {
        return Ok(());
    }

    let rule = ctx
        .db
        .automation_rule()
        .id()
        .find(event.automation_id)
        .ok_or("Automation rule not found")?;
    let payload = parse_json_object(&event.trigger_payload, "trigger_payload")?;

    ctx.db
        .automation_event_queue()
        .id()
        .update(AutomationEventQueue {
            status: AutomationEventStatus::Running,
            attempts: event.attempts + 1,
            claimed_by,
            updated_at: ctx.timestamp,
            ..event
        });

    if !conditions_match(ctx, rule.id, &payload)? {
        insert_run_log(
            ctx,
            queue_id,
            None,
            true,
            true,
            "Conditions did not match; no actions would run".to_string(),
            json!({"condition_result":"skipped"}).to_string(),
        );
        update_event_status(ctx, queue_id, AutomationEventStatus::Skipped, None);
        return Ok(());
    }

    let mut actions: Vec<AutomationAction> = ctx
        .db
        .automation_action()
        .by_rule()
        .filter(&rule.id)
        .collect();
    actions.sort_by_key(|a| a.order);

    if actions.is_empty() {
        insert_run_log(
            ctx,
            queue_id,
            None,
            true,
            true,
            "No actions configured".to_string(),
            "{}".to_string(),
        );
        update_event_status(ctx, queue_id, AutomationEventStatus::Completed, None);
        return Ok(());
    }

    if rule.mode != AutomationMode::DryRun {
        insert_run_log(
            ctx,
            queue_id,
            None,
            false,
            false,
            "Live automation execution is not implemented in v0".to_string(),
            "{}".to_string(),
        );
        update_event_status(
            ctx,
            queue_id,
            AutomationEventStatus::Failed,
            Some("Live automation execution is not implemented in v0".to_string()),
        );
        return Ok(());
    }

    for action in actions {
        insert_run_log(
            ctx,
            queue_id,
            Some(action.id),
            true,
            true,
            format!("Would execute {}", action_kind_name(&action.action_kind)),
            json!({
                "action_kind": action_kind_name(&action.action_kind),
                "config": parse_json_object(&action.config, "action config")?,
                "trigger_payload": payload,
            })
            .to_string(),
        );
    }
    update_event_status(ctx, queue_id, AutomationEventStatus::Completed, None);
    Ok(())
}

fn insert_run_log(
    ctx: &ReducerContext,
    queue_id: u64,
    action_id: Option<u64>,
    success: bool,
    dry_run: bool,
    message: String,
    result_json: String,
) {
    ctx.db.automation_run_log().insert(AutomationRunLog {
        id: next_automation_run_log_id(ctx),
        queue_id,
        action_id,
        success,
        dry_run,
        message,
        result_json,
        created_at: ctx.timestamp,
    });
}

fn update_event_status(
    ctx: &ReducerContext,
    queue_id: u64,
    status: AutomationEventStatus,
    error: Option<String>,
) {
    if let Some(event) = ctx.db.automation_event_queue().id().find(queue_id) {
        ctx.db
            .automation_event_queue()
            .id()
            .update(AutomationEventQueue {
                status,
                error,
                updated_at: ctx.timestamp,
                ..event
            });
    }
}

fn require_rule_owner(
    ctx: &ReducerContext,
    automation_id: u64,
    action: &str,
) -> Result<AutomationRule, String> {
    let rule = ctx
        .db
        .automation_rule()
        .id()
        .find(automation_id)
        .ok_or("Automation rule not found")?;
    require_creator_or_admin(ctx, rule.created_by, action)?;
    Ok(rule)
}

fn validate_rule(ctx: &ReducerContext, rule: &AutomationRule) -> Result<(), String> {
    if rule.name.trim().is_empty() {
        return Err("Automation name cannot be empty".to_string());
    }
    if rule.canonical_description.trim().is_empty() {
        return Err("Automation must include a canonical human-readable description".to_string());
    }
    parse_json_object(&rule.trigger_config, "trigger_config")?;
    parse_json_object(&rule.schedule_config, "schedule_config")?;

    match rule.trigger_kind {
        AutomationTriggerKind::Scheduled => validate_schedule(rule)?,
        _ => {
            if rule.schedule_kind != AutomationScheduleKind::None {
                return Err("Only Scheduled triggers may use schedule_kind".to_string());
            }
        }
    }

    if ctx
        .db
        .automation_action()
        .by_rule()
        .filter(&rule.id)
        .next()
        .is_none()
    {
        return Err("Automation must have at least one action".to_string());
    }

    for action in ctx.db.automation_action().by_rule().filter(&rule.id) {
        parse_json_object(&action.config, "action config")?;
    }
    for condition in ctx.db.automation_condition().by_rule().filter(&rule.id) {
        parse_json_object(&condition.config, "condition config")?;
    }
    for capability in ctx.db.automation_capability().by_rule().filter(&rule.id) {
        parse_json_object(&capability.scope_config, "capability scope_config")?;
    }
    Ok(())
}

fn validate_schedule(rule: &AutomationRule) -> Result<(), String> {
    match rule.schedule_kind {
        AutomationScheduleKind::Interval => {
            let secs = interval_seconds(&rule.schedule_config)?;
            if secs == 0 {
                return Err("interval_seconds must be greater than zero".to_string());
            }
        }
        AutomationScheduleKind::OneShot => {
            run_at_micros(&rule.schedule_config)?;
        }
        AutomationScheduleKind::Cron => {
            let expr = cron_expression(&rule.schedule_config)?;
            parse_cron_fields(&expr)?;
        }
        AutomationScheduleKind::None => {
            return Err("Scheduled trigger must use Interval, OneShot, or Cron".to_string());
        }
    }
    Ok(())
}

fn schedule_rule_if_needed(
    ctx: &ReducerContext,
    rule: &AutomationRule,
) -> Result<Option<Timestamp>, String> {
    if rule.trigger_kind != AutomationTriggerKind::Scheduled {
        return Ok(None);
    }
    match rule.schedule_kind {
        AutomationScheduleKind::Interval => {
            let secs = interval_seconds(&rule.schedule_config)?;
            let dur = Duration::from_secs(secs);
            ctx.db
                .automation_schedule_job()
                .insert(AutomationScheduleJob {
                    scheduled_id: 0,
                    scheduled_at: dur.into(),
                    automation_id: rule.id,
                });
            Ok(Some(ctx.timestamp + dur))
        }
        AutomationScheduleKind::OneShot => {
            let run_at =
                Timestamp::from_micros_since_unix_epoch(run_at_micros(&rule.schedule_config)?);
            ctx.db
                .automation_schedule_job()
                .insert(AutomationScheduleJob {
                    scheduled_id: 0,
                    scheduled_at: run_at.into(),
                    automation_id: rule.id,
                });
            Ok(Some(run_at))
        }
        AutomationScheduleKind::Cron => {
            ensure_cron_tick(ctx);
            Ok(None)
        }
        AutomationScheduleKind::None => Ok(None),
    }
}

fn delete_schedule_jobs_for_rule(ctx: &ReducerContext, automation_id: u64) {
    let ids: Vec<u64> = ctx
        .db
        .automation_schedule_job()
        .iter()
        .filter(|j| j.automation_id == automation_id)
        .map(|j| j.scheduled_id)
        .collect();
    for id in ids {
        ctx.db.automation_schedule_job().scheduled_id().delete(id);
    }
}

fn ensure_cron_tick(ctx: &ReducerContext) {
    if ctx.db.automation_cron_tick().iter().next().is_some() {
        return;
    }
    ctx.db.automation_cron_tick().insert(AutomationCronTick {
        scheduled_id: 0,
        scheduled_at: Duration::from_secs(60).into(),
    });
}

fn stop_cron_tick_if_unused(ctx: &ReducerContext) {
    let has_enabled_cron = ctx.db.automation_rule().iter().any(|r| {
        r.enabled
            && r.trigger_kind == AutomationTriggerKind::Scheduled
            && r.schedule_kind == AutomationScheduleKind::Cron
    });
    if has_enabled_cron {
        return;
    }
    let ids: Vec<u64> = ctx
        .db
        .automation_cron_tick()
        .iter()
        .map(|j| j.scheduled_id)
        .collect();
    for id in ids {
        ctx.db.automation_cron_tick().scheduled_id().delete(id);
    }
}

fn disable_automation_inner(ctx: &ReducerContext, rule: AutomationRule) {
    delete_schedule_jobs_for_rule(ctx, rule.id);
    ctx.db.automation_rule().id().update(AutomationRule {
        enabled: false,
        next_run_at: None,
        updated_at: ctx.timestamp,
        ..rule
    });
    stop_cron_tick_if_unused(ctx);
}

fn bump_scheduled_rule(ctx: &ReducerContext, rule: AutomationRule) {
    let tick_count = rule.tick_count + 1;
    let max_reached = rule.max_ticks.is_some_and(|m| tick_count >= m);
    if max_reached || rule.schedule_kind == AutomationScheduleKind::OneShot {
        ctx.db.automation_rule().id().update(AutomationRule {
            enabled: false,
            last_run_at: Some(ctx.timestamp),
            next_run_at: None,
            tick_count,
            updated_at: ctx.timestamp,
            ..rule
        });
        delete_schedule_jobs_for_rule(ctx, rule.id);
        stop_cron_tick_if_unused(ctx);
        return;
    }

    let next_run_at = match rule.schedule_kind {
        AutomationScheduleKind::Interval => interval_seconds(&rule.schedule_config)
            .ok()
            .map(|secs| ctx.timestamp + Duration::from_secs(secs)),
        _ => None,
    };
    ctx.db.automation_rule().id().update(AutomationRule {
        last_run_at: Some(ctx.timestamp),
        next_run_at,
        tick_count,
        updated_at: ctx.timestamp,
        ..rule
    });
}

fn rule_is_expired(ctx: &ReducerContext, rule: &AutomationRule) -> bool {
    if let Some(expires_at) = rule.expires_at {
        if ctx.timestamp >= expires_at {
            return true;
        }
    }
    rule.max_ticks.is_some_and(|m| rule.tick_count >= m)
}

fn trigger_matches_payload(rule: &AutomationRule, payload: &Value) -> bool {
    let Ok(config) = parse_json_object(&rule.trigger_config, "trigger_config") else {
        return false;
    };
    field_matches_optional_u64(&config, "page_id", payload, "page_id")
        && field_matches_optional_u64(&config, "parent_id", payload, "parent_id")
        && field_matches_optional_u64(&config, "parent_pk", payload, "parent_pk")
        && field_matches_optional_u64(
            &config,
            "property_definition_id",
            payload,
            "property_definition_id",
        )
}

fn field_matches_optional_u64(
    config: &Value,
    config_field: &str,
    payload: &Value,
    payload_field: &str,
) -> bool {
    let Some(expected) = json_u64(config.get(config_field)) else {
        return true;
    };
    json_u64(payload.get(payload_field)) == Some(expected)
}

fn conditions_match(
    ctx: &ReducerContext,
    automation_id: u64,
    payload: &Value,
) -> Result<bool, String> {
    let mut conditions: Vec<AutomationCondition> = ctx
        .db
        .automation_condition()
        .by_rule()
        .filter(&automation_id)
        .collect();
    conditions.sort_by_key(|c| c.order);

    for condition in conditions {
        match condition.condition_kind {
            AutomationConditionKind::PayloadFieldEquals => {
                let config = parse_json_object(&condition.config, "condition config")?;
                let field = config
                    .get("field")
                    .and_then(Value::as_str)
                    .ok_or("PayloadFieldEquals condition requires field")?;
                let expected = config
                    .get("equals")
                    .map(json_scalar_as_string)
                    .ok_or("PayloadFieldEquals condition requires equals")?;
                let actual = payload.get(field).map(json_scalar_as_string);
                if actual.as_deref() != Some(expected.as_str()) {
                    return Ok(false);
                }
            }
        }
    }
    Ok(true)
}

fn parse_json_object(raw: &str, label: &str) -> Result<Value, String> {
    let value: Value =
        serde_json::from_str(raw).map_err(|e| format!("Invalid {label} JSON: {e}"))?;
    if !value.is_object() {
        return Err(format!("{label} must be a JSON object"));
    }
    Ok(value)
}

fn json_u64(value: Option<&Value>) -> Option<u64> {
    match value? {
        Value::Number(n) => n.as_u64(),
        Value::String(s) => s.parse::<u64>().ok(),
        _ => None,
    }
}

fn json_scalar_as_string(value: &Value) -> String {
    match value {
        Value::String(s) => s.clone(),
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Null => "null".to_string(),
        other => other.to_string(),
    }
}

fn interval_seconds(config: &str) -> Result<u64, String> {
    let config = parse_json_object(config, "schedule_config")?;
    json_u64(config.get("interval_seconds"))
        .ok_or("schedule_config.interval_seconds is required".to_string())
}

fn run_at_micros(config: &str) -> Result<i64, String> {
    let config = parse_json_object(config, "schedule_config")?;
    match config.get("run_at_micros") {
        Some(Value::Number(n)) => n
            .as_i64()
            .ok_or("schedule_config.run_at_micros must fit in i64".to_string()),
        Some(Value::String(s)) => s
            .parse::<i64>()
            .map_err(|_| "schedule_config.run_at_micros must be an integer".to_string()),
        _ => Err("schedule_config.run_at_micros is required".to_string()),
    }
}

fn cron_expression(config: &str) -> Result<String, String> {
    let config = parse_json_object(config, "schedule_config")?;
    config
        .get("expression")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .ok_or("schedule_config.expression is required for cron schedules".to_string())
}

fn cron_rule_due(rule: &AutomationRule, now: Timestamp) -> bool {
    if rule
        .last_run_at
        .is_some_and(|last| minute_bucket(last) == minute_bucket(now))
    {
        return false;
    }
    let Ok(expr) = cron_expression(&rule.schedule_config) else {
        return false;
    };
    cron_matches(&expr, now).unwrap_or(false)
}

fn minute_bucket(ts: Timestamp) -> i64 {
    ts.to_micros_since_unix_epoch() / 60_000_000
}

fn cron_matches(expr: &str, ts: Timestamp) -> Result<bool, String> {
    let fields = parse_cron_fields(expr)?;
    let micros = ts.to_micros_since_unix_epoch();
    let dt = chrono::DateTime::<Utc>::from_timestamp_micros(micros)
        .ok_or("Timestamp out of cron evaluation range")?;
    let minute = dt.minute();
    let hour = dt.hour();
    let day = dt.day();
    let month = dt.month();
    let dow = dt.weekday().num_days_from_sunday();
    Ok(cron_field_matches(&fields[0], minute, 0, 59, false)?
        && cron_field_matches(&fields[1], hour, 0, 23, false)?
        && cron_field_matches(&fields[2], day, 1, 31, false)?
        && cron_field_matches(&fields[3], month, 1, 12, false)?
        && cron_field_matches(&fields[4], dow, 0, 7, true)?)
}

fn parse_cron_fields(expr: &str) -> Result<Vec<String>, String> {
    let fields: Vec<String> = expr.split_whitespace().map(str::to_string).collect();
    if fields.len() != 5 {
        return Err(
            "Cron expression must have five fields: minute hour day month weekday".to_string(),
        );
    }
    for (idx, field) in fields.iter().enumerate() {
        let (min, max, sunday_alias) = match idx {
            0 => (0, 59, false),
            1 => (0, 23, false),
            2 => (1, 31, false),
            3 => (1, 12, false),
            4 => (0, 7, true),
            _ => unreachable!(),
        };
        cron_field_matches(field, min, min, max, sunday_alias)?;
    }
    Ok(fields)
}

fn cron_field_matches(
    field: &str,
    value: u32,
    min: u32,
    max: u32,
    sunday_alias: bool,
) -> Result<bool, String> {
    for part in field.split(',') {
        let part = part.trim();
        if part.is_empty() {
            return Err("Cron field contains an empty segment".to_string());
        }
        if part == "*" {
            return Ok(true);
        }
        if let Some(step) = part.strip_prefix("*/") {
            let step = step
                .parse::<u32>()
                .map_err(|_| "Cron step must be an integer".to_string())?;
            if step == 0 {
                return Err("Cron step must be greater than zero".to_string());
            }
            if (value - min) % step == 0 {
                return Ok(true);
            }
            continue;
        }
        if let Some((start, end)) = part.split_once('-') {
            let start = parse_cron_number(start, sunday_alias)?;
            let end = parse_cron_number(end, sunday_alias)?;
            if start < min || end > max || start > end {
                return Err("Cron range is out of bounds".to_string());
            }
            if value >= start && value <= end {
                return Ok(true);
            }
            continue;
        }
        let exact = parse_cron_number(part, sunday_alias)?;
        if exact < min || exact > max {
            return Err("Cron value is out of bounds".to_string());
        }
        if exact == value || (sunday_alias && exact == 7 && value == 0) {
            return Ok(true);
        }
    }
    Ok(false)
}

fn parse_cron_number(raw: &str, sunday_alias: bool) -> Result<u32, String> {
    let n = raw
        .parse::<u32>()
        .map_err(|_| "Cron value must be an integer".to_string())?;
    if sunday_alias && n == 7 {
        Ok(7)
    } else {
        Ok(n)
    }
}

fn normalize_timezone(timezone: String) -> String {
    let trimmed = timezone.trim();
    if trimmed.is_empty() {
        "UTC".to_string()
    } else {
        trimmed.to_string()
    }
}

fn page_type_name(page_type: &PageType) -> &'static str {
    match page_type {
        PageType::Doc => "Doc",
        PageType::Database => "Database",
    }
}

fn action_kind_name(kind: &AutomationActionKind) -> &'static str {
    match kind {
        AutomationActionKind::HttpRequest => "HttpRequest",
        AutomationActionKind::SendEmail => "SendEmail",
        AutomationActionKind::CreatePage => "CreatePage",
        AutomationActionKind::UpdateProperty => "UpdateProperty",
        AutomationActionKind::OrchaJob => "OrchaJob",
    }
}
