//! Automations: typed trigger/action graphs, event queue, and live/dry-run
//! execution.
//!
//! v1: the in-module actions (`CreatePage`, `UpdateProperty`, `OrchaJob`)
//! execute for real when a rule is in `Live` mode; `HttpRequest` / `SendEmail`
//! stay dry-run until an off-module worker executor exists (reducers cannot do
//! I/O). Live actions run with the rule's `run_as` authority, except Manual
//! invocations, which use the invoking principal so a button cannot borrow the
//! rule author's access. Authority is checked against page ACLs per action.
//! Governance: anyone — including AI users — may author
//! and dry-run rules, but only a human (creator or admin) may flip a rule
//! Live, and any structural edit to a Live rule demotes it back to DryRun so
//! changes need fresh human approval.

use std::cell::Cell;
use std::time::Duration;

use serde_json::{json, Value};
use spacetimedb::{
    reducer, table, Identity, ReducerContext, ScheduleAt, SpacetimeType, Table, Timestamp,
};

use crate::access_control::helpers::{can_write_page, require_creator_or_admin};
use crate::ai::{ai_user_config, ai_user_profile};
use crate::auth::{sender_is_admin, user};
use crate::cron::{cron_matches, minute_bucket, parse_cron_fields, parse_timezone};
use crate::id_counters::alloc_id;
use crate::orcha::{
    ai_user_at_hard_cap, create_job_inner, orcha_job, tail_chars, truncate_chars, OrchaTask,
};
use crate::pages::schemas::{
    property_definition, set_property_value_inner, PropertyType, PropertyValue,
};
use crate::pages::{create_component_tree_page_inner, page, ActorType, PageType};

/// Bound on inline execution recursion: a live action that itself fires
/// triggers (e.g. CreatePage → PageCreated) processes the nested events inline
/// only this deep; deeper events stay Pending instead of recursing unbounded
/// within one transaction. `process_pending_automation_events` drains them.
const MAX_INLINE_EXEC_DEPTH: u32 = 4;
const MAX_MANUAL_INPUT_BYTES: usize = 16 * 1024;
const MAX_IDEMPOTENCY_KEY_BYTES: usize = 128;
const MANUAL_RESERVED_FIELDS: [&str; 4] = [
    "event_type",
    "automation_id",
    "invoked_by",
    "idempotency_key",
];

thread_local! {
    static INLINE_EXEC_DEPTH: Cell<u32> = const { Cell::new(0) };
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationTriggerKind {
    PageCreated,
    PageUpdated,
    PageDeleted,
    PropertyChanged,
    Scheduled,
    Manual,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationScheduleKind {
    None,
    Interval,
    OneShot,
    Cron,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationMode {
    DryRun,
    Live,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationActionKind {
    HttpRequest,
    SendEmail,
    CreatePage,
    UpdateProperty,
    OrchaJob,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationCapabilityKind {
    ReadPage,
    WritePage,
    HttpOutbound,
    SendEmail,
    SpendAiTokens,
    SpawnOrchaJob,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationConditionKind {
    PayloadFieldEquals,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationEventStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Skipped,
}

#[derive(SpacetimeType, Clone, Debug, PartialEq)]
pub enum AutomationPrimitiveKind {
    Trigger,
    Action,
    Condition,
    Capability,
}

/// A user- or AI-authored automation rule. Rules default to dry-run and disabled.
#[table(accessor = automation_rule, public)]
pub struct AutomationRule {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub name: String,
    pub enabled: bool,
    pub mode: AutomationMode,
    pub trigger_kind: AutomationTriggerKind,
    /// JSON config scoped to the trigger. Examples:
    /// - PageCreated: {"parent_id": 12}
    /// - PropertyChanged: {"property_definition_id": 42}
    pub trigger_config: String,
    pub schedule_kind: AutomationScheduleKind,
    /// JSON schedule config. Interval: {"interval_seconds": 3600}; one-shot:
    /// {"run_at_micros": 1770000000000000}; cron: {"expression": "0 9 * * 1"}.
    pub schedule_config: String,
    /// Stored now so the review surface is future-proof. Cron v0 evaluates in UTC.
    pub timezone: String,
    pub next_run_at: Option<Timestamp>,
    pub last_run_at: Option<Timestamp>,
    pub max_ticks: Option<u64>,
    pub tick_count: u64,
    pub expires_at: Option<Timestamp>,
    /// The principal whose authority live execution will use. Defaults to creator.
    pub run_as: Identity,
    pub created_by: Identity,
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
    /// Canonical human review string, generated by UI or AI alongside the graph.
    pub canonical_description: String,
}

#[table(accessor = automation_action, public, index(accessor = by_rule, btree(columns = [automation_id])))]
pub struct AutomationAction {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub automation_id: u64,
    pub order: u32,
    pub action_kind: AutomationActionKind,
    /// JSON config specific to action_kind. Dry-run logs this verbatim.
    pub config: String,
}

#[table(accessor = automation_condition, public, index(accessor = by_rule, btree(columns = [automation_id])))]
pub struct AutomationCondition {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub automation_id: u64,
    pub order: u32,
    pub condition_kind: AutomationConditionKind,
    /// PayloadFieldEquals: {"field": "page_id", "equals": "123"}.
    pub config: String,
}

#[table(accessor = automation_capability, public, index(accessor = by_rule, btree(columns = [automation_id])))]
pub struct AutomationCapability {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub automation_id: u64,
    pub capability_kind: AutomationCapabilityKind,
    /// JSON scope, e.g. {"page_id": 12}, {"host": "hooks.slack.com"}, {"monthly_tokens": 10000}.
    pub scope_config: String,
}

#[table(accessor = automation_event_queue, public, index(accessor = by_rule, btree(columns = [automation_id])))]
pub struct AutomationEventQueue {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub automation_id: u64,
    pub trigger_kind: AutomationTriggerKind,
    pub trigger_payload: String,
    pub status: AutomationEventStatus,
    pub attempts: u32,
    pub claimed_by: Option<String>,
    pub error: Option<String>,
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
    /// Present for explicit Manual invocations. The executor uses this
    /// principal for Live page ACL checks instead of borrowing `rule.run_as`.
    #[default(None::<Identity>)]
    pub invoked_by: Option<Identity>,
    /// Caller-provided retry key, scoped to `(automation_id, invoked_by)`.
    #[default(None::<String>)]
    pub idempotency_key: Option<String>,
}

#[table(accessor = automation_run_log, public, index(accessor = by_queue, btree(columns = [queue_id])))]
pub struct AutomationRunLog {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub queue_id: u64,
    pub action_id: Option<u64>,
    pub success: bool,
    pub dry_run: bool,
    pub message: String,
    pub result_json: String,
    pub created_at: Timestamp,
}

/// AI/user-facing registry of primitives the automation authoring tools may use.
#[table(accessor = automation_primitive, public)]
pub struct AutomationPrimitive {
    #[primary_key]
    pub name: String,
    pub primitive_kind: AutomationPrimitiveKind,
    pub title: String,
    pub description: String,
    pub config_schema_json: String,
}

#[table(accessor = automation_schedule_job, scheduled(run_scheduled_automation))]
pub struct AutomationScheduleJob {
    #[primary_key]
    #[auto_inc]
    pub scheduled_id: u64,
    pub scheduled_at: ScheduleAt,
    pub automation_id: u64,
}

#[table(accessor = automation_cron_tick, scheduled(run_automation_cron_tick))]
pub struct AutomationCronTick {
    #[primary_key]
    #[auto_inc]
    pub scheduled_id: u64,
    pub scheduled_at: ScheduleAt,
}

pub(crate) fn next_automation_rule_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_rule", || {
        ctx.db
            .automation_rule()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_action_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_action", || {
        ctx.db
            .automation_action()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_condition_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_condition", || {
        ctx.db
            .automation_condition()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_capability_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_capability", || {
        ctx.db
            .automation_capability()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_event_queue_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_event_queue", || {
        ctx.db
            .automation_event_queue()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn next_automation_run_log_id(ctx: &ReducerContext) -> u64 {
    alloc_id(ctx, "automation_run_log", || {
        ctx.db
            .automation_run_log()
            .iter()
            .map(|r| r.id)
            .max()
            .unwrap_or(0)
    })
}

pub(crate) fn seed_automation_primitives_inner(ctx: &ReducerContext) {
    let primitives = [
        (
            "trigger.page_created",
            AutomationPrimitiveKind::Trigger,
            "Page created",
            "Runs when a page or database row is created.",
            r#"{"type":"object","properties":{"page_id":{"type":"integer"},"parent_id":{"type":"integer"}}}"#,
        ),
        (
            "trigger.page_updated",
            AutomationPrimitiveKind::Trigger,
            "Page updated",
            "Runs when page title or content changes.",
            r#"{"type":"object","properties":{"page_id":{"type":"integer"},"parent_id":{"type":"integer"}}}"#,
        ),
        (
            "trigger.page_deleted",
            AutomationPrimitiveKind::Trigger,
            "Page deleted",
            "Runs when a page or database row is soft-deleted.",
            r#"{"type":"object","properties":{"page_id":{"type":"integer"},"parent_id":{"type":"integer"}}}"#,
        ),
        (
            "trigger.property_changed",
            AutomationPrimitiveKind::Trigger,
            "Property changed",
            "Runs when a database row property changes.",
            r#"{"type":"object","properties":{"page_id":{"type":"integer"},"property_definition_id":{"type":"integer"}}}"#,
        ),
        (
            "trigger.scheduled",
            AutomationPrimitiveKind::Trigger,
            "Scheduled",
            "Runs on an interval, one-shot timestamp, or five-field UTC cron expression.",
            r#"{"type":"object","properties":{"interval_seconds":{"type":"integer"},"run_at_micros":{"type":"integer"},"expression":{"type":"string"}}}"#,
        ),
        (
            "trigger.manual",
            AutomationPrimitiveKind::Trigger,
            "Manual",
            "Runs only when an allowed workspace principal explicitly invokes it. The server stamps the invoker and idempotency key into the event payload.",
            r#"{"type":"object","properties":{"invoker_policy":{"type":"string","enum":["creator_or_admin","workspace","identities"]},"allowed_invoker_identities":{"type":"array","items":{"type":"string"}},"allowed_input_fields":{"type":"array","items":{"type":"string"}},"required_input_fields":{"type":"array","items":{"type":"string"}}}}"#,
        ),
        (
            "action.http_request",
            AutomationPrimitiveKind::Action,
            "HTTP request",
            "Posts to an external URL. Dry-run only until the worker executor ships.",
            r#"{"type":"object","properties":{"url":{"type":"string"},"headers":{"type":"object"},"body_template":{"type":"string"}}}"#,
        ),
        (
            "action.send_email",
            AutomationPrimitiveKind::Action,
            "Send email",
            "Sends an SMTP email. Dry-run only until the worker executor ships.",
            r#"{"type":"object","properties":{"to":{"type":"string"},"subject_template":{"type":"string"},"body_template":{"type":"string"}}}"#,
        ),
        (
            "action.create_page",
            AutomationPrimitiveKind::Action,
            "Create page",
            "Creates a page. title_template supports {{field}} tokens from the trigger payload. Executes for real when the rule is Live.",
            r#"{"type":"object","properties":{"parent_id":{"type":"integer"},"title_template":{"type":"string"}}}"#,
        ),
        (
            "action.update_property",
            AutomationPrimitiveKind::Action,
            "Update property",
            "Sets a property value on a row (target from config.page_id or the payload field named by page_id_field; value from config.value or the payload field named by value_field). Executes for real when the rule is Live.",
            r#"{"type":"object","properties":{"property_definition_id":{"type":"integer"},"value":{},"value_field":{"type":"string"},"page_id":{"type":"integer"},"page_id_field":{"type":"string"}}}"#,
        ),
        (
            "action.orcha_job",
            AutomationPrimitiveKind::Action,
            "Orcha job",
            "Creates an AI job from the trigger payload (prompt_template supports {{field}} tokens). Executes for real when the rule is Live.",
            r#"{"type":"object","properties":{"prompt_template":{"type":"string"},"page_id_field":{"type":"string"},"ai_user_id":{"type":"integer"},"tier":{"type":"string"}}}"#,
        ),
        (
            "condition.payload_field_equals",
            AutomationPrimitiveKind::Condition,
            "Payload field equals",
            "Checks a top-level trigger payload field against a value.",
            r#"{"type":"object","properties":{"field":{"type":"string"},"equals":{"type":"string"}},"required":["field","equals"]}"#,
        ),
    ];

    for (name, primitive_kind, title, description, config_schema_json) in primitives {
        let row = AutomationPrimitive {
            name: name.to_string(),
            primitive_kind,
            title: title.to_string(),
            description: description.to_string(),
            config_schema_json: config_schema_json.to_string(),
        };
        if ctx
            .db
            .automation_primitive()
            .name()
            .find(row.name.clone())
            .is_some()
        {
            ctx.db.automation_primitive().name().update(row);
        } else {
            ctx.db.automation_primitive().insert(row);
        }
    }
}

#[reducer]
pub fn create_automation_draft(
    ctx: &ReducerContext,
    name: String,
    trigger_kind: AutomationTriggerKind,
    trigger_config: String,
    schedule_kind: AutomationScheduleKind,
    schedule_config: String,
    timezone: String,
    canonical_description: String,
) -> Result<(), String> {
    if name.trim().is_empty() {
        return Err("Automation name cannot be empty".to_string());
    }
    parse_json_object(&trigger_config, "trigger_config")?;
    parse_json_object(&schedule_config, "schedule_config")?;

    ctx.db.automation_rule().insert(AutomationRule {
        id: next_automation_rule_id(ctx),
        name: name.trim().to_string(),
        enabled: false,
        mode: AutomationMode::DryRun,
        trigger_kind,
        trigger_config,
        schedule_kind,
        schedule_config,
        timezone: normalize_timezone(timezone),
        next_run_at: None,
        last_run_at: None,
        max_ticks: None,
        tick_count: 0,
        expires_at: None,
        run_as: ctx.sender(),
        created_by: ctx.sender(),
        created_at: ctx.timestamp,
        updated_at: ctx.timestamp,
        canonical_description,
    });
    Ok(())
}

#[reducer]
pub fn update_automation_rule(
    ctx: &ReducerContext,
    automation_id: u64,
    name: String,
    trigger_kind: AutomationTriggerKind,
    trigger_config: String,
    schedule_kind: AutomationScheduleKind,
    schedule_config: String,
    timezone: String,
    canonical_description: String,
) -> Result<(), String> {
    parse_json_object(&trigger_config, "trigger_config")?;
    parse_json_object(&schedule_config, "schedule_config")?;
    let rule = require_rule_owner(ctx, automation_id, "update automation")?;
    ctx.db.automation_rule().id().update(AutomationRule {
        name: name.trim().to_string(),
        trigger_kind,
        trigger_config,
        schedule_kind,
        schedule_config,
        timezone: normalize_timezone(timezone),
        canonical_description,
        enabled: false,
        // Edits demote a Live rule: the approved graph changed, so live
        // execution needs fresh human approval via set_automation_mode.
        mode: AutomationMode::DryRun,
        next_run_at: None,
        updated_at: ctx.timestamp,
        ..rule
    });
    delete_schedule_jobs_for_rule(ctx, automation_id);
    Ok(())
}

#[reducer]
pub fn set_automation_limits(
    ctx: &ReducerContext,
    automation_id: u64,
    max_ticks: Option<u64>,
    expires_at: Option<Timestamp>,
) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "set automation limits")?;
    ctx.db.automation_rule().id().update(AutomationRule {
        max_ticks,
        expires_at,
        updated_at: ctx.timestamp,
        ..rule
    });
    Ok(())
}

#[reducer]
pub fn set_automation_mode(
    ctx: &ReducerContext,
    automation_id: u64,
    mode: AutomationMode,
) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "set automation mode")?;
    if mode == AutomationMode::Live {
        // AI users may author and dry-run rules, but going live is a human
        // decision — an AI creator cannot approve its own side effects.
        if sender_is_ai_user(ctx) {
            return Err(
                "Only a human (creator or admin) can set an automation Live; AI-authored rules \
                 stay in DryRun until a human approves them"
                    .to_string(),
            );
        }
        let offending: Vec<&'static str> = ctx
            .db
            .automation_action()
            .by_rule()
            .filter(&automation_id)
            .filter(|a| !action_kind_is_in_module(&a.action_kind))
            .map(|a| action_kind_name(&a.action_kind))
            .collect();
        if !offending.is_empty() {
            return Err(format!(
                "Live execution supports CreatePage, UpdateProperty, and OrchaJob actions only; \
                 {} requires the worker executor (not yet implemented)",
                offending.join(", ")
            ));
        }
    }
    ctx.db.automation_rule().id().update(AutomationRule {
        mode,
        updated_at: ctx.timestamp,
        ..rule
    });
    Ok(())
}

#[reducer]
pub fn add_automation_action(
    ctx: &ReducerContext,
    automation_id: u64,
    order: u32,
    action_kind: AutomationActionKind,
    config: String,
) -> Result<(), String> {
    require_rule_owner(ctx, automation_id, "add automation actions")?;
    parse_json_object(&config, "action config")?;
    demote_live_rule_on_edit(ctx, automation_id);
    ctx.db.automation_action().insert(AutomationAction {
        id: next_automation_action_id(ctx),
        automation_id,
        order,
        action_kind,
        config,
    });
    Ok(())
}

#[reducer]
pub fn update_automation_action(
    ctx: &ReducerContext,
    action_id: u64,
    order: u32,
    action_kind: AutomationActionKind,
    config: String,
) -> Result<(), String> {
    parse_json_object(&config, "action config")?;
    let action = ctx
        .db
        .automation_action()
        .id()
        .find(action_id)
        .ok_or("Automation action not found")?;
    require_rule_owner(ctx, action.automation_id, "update automation actions")?;
    demote_live_rule_on_edit(ctx, action.automation_id);
    ctx.db.automation_action().id().update(AutomationAction {
        order,
        action_kind,
        config,
        ..action
    });
    Ok(())
}

#[reducer]
pub fn delete_automation_action(ctx: &ReducerContext, action_id: u64) -> Result<(), String> {
    let action = ctx
        .db
        .automation_action()
        .id()
        .find(action_id)
        .ok_or("Automation action not found")?;
    require_rule_owner(ctx, action.automation_id, "delete automation actions")?;
    demote_live_rule_on_edit(ctx, action.automation_id);
    ctx.db.automation_action().id().delete(action_id);
    Ok(())
}

#[reducer]
pub fn add_automation_condition(
    ctx: &ReducerContext,
    automation_id: u64,
    order: u32,
    condition_kind: AutomationConditionKind,
    config: String,
) -> Result<(), String> {
    require_rule_owner(ctx, automation_id, "add automation conditions")?;
    parse_json_object(&config, "condition config")?;
    demote_live_rule_on_edit(ctx, automation_id);
    ctx.db.automation_condition().insert(AutomationCondition {
        id: next_automation_condition_id(ctx),
        automation_id,
        order,
        condition_kind,
        config,
    });
    Ok(())
}

#[reducer]
pub fn add_automation_capability(
    ctx: &ReducerContext,
    automation_id: u64,
    capability_kind: AutomationCapabilityKind,
    scope_config: String,
) -> Result<(), String> {
    require_rule_owner(ctx, automation_id, "add automation capabilities")?;
    parse_json_object(&scope_config, "capability scope_config")?;
    ctx.db.automation_capability().insert(AutomationCapability {
        id: next_automation_capability_id(ctx),
        automation_id,
        capability_kind,
        scope_config,
    });
    Ok(())
}

#[reducer]
pub fn validate_automation(ctx: &ReducerContext, automation_id: u64) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "validate automation")?;
    validate_rule(ctx, &rule)
}

#[reducer]
pub fn enable_automation(ctx: &ReducerContext, automation_id: u64) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "enable automation")?;
    validate_rule(ctx, &rule)?;
    delete_schedule_jobs_for_rule(ctx, automation_id);
    let next_run_at = schedule_rule_if_needed(ctx, &rule)?;
    ctx.db.automation_rule().id().update(AutomationRule {
        enabled: true,
        next_run_at,
        updated_at: ctx.timestamp,
        ..rule
    });
    Ok(())
}

#[reducer]
pub fn disable_automation(ctx: &ReducerContext, automation_id: u64) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "disable automation")?;
    delete_schedule_jobs_for_rule(ctx, automation_id);
    ctx.db.automation_rule().id().update(AutomationRule {
        enabled: false,
        next_run_at: None,
        updated_at: ctx.timestamp,
        ..rule
    });
    stop_cron_tick_if_unused(ctx);
    Ok(())
}

/// Explicitly invoke an enabled Manual automation.
///
/// The input is intentionally a flat JSON object: conditions and action
/// payload bindings can address its fields without a second expression
/// language. Invocation metadata is server-stamped and cannot be spoofed.
#[reducer]
pub fn invoke_automation(
    ctx: &ReducerContext,
    automation_id: u64,
    input_json: String,
    idempotency_key: String,
) -> Result<(), String> {
    let rule = ctx
        .db
        .automation_rule()
        .id()
        .find(automation_id)
        .ok_or("Automation rule not found")?;
    if !rule.enabled {
        return Err("Automation is disabled".to_string());
    }
    if rule.trigger_kind != AutomationTriggerKind::Manual {
        return Err("Only Manual automations can be invoked explicitly".to_string());
    }
    if rule_is_expired(ctx, &rule) {
        disable_automation_inner(ctx, rule);
        return Err("Automation has expired or reached its invocation limit".to_string());
    }
    validate_idempotency_key(&idempotency_key)?;
    if input_json.len() > MAX_MANUAL_INPUT_BYTES {
        return Err(format!(
            "Manual automation input exceeds {MAX_MANUAL_INPUT_BYTES} bytes"
        ));
    }

    let trigger_config = parse_json_object(&rule.trigger_config, "trigger_config")?;
    validate_manual_trigger_config(&trigger_config)?;
    let sender = ctx.sender();
    let is_creator_or_admin = sender == rule.created_by || sender_is_admin(ctx);
    let is_known_principal = is_known_workspace_principal(ctx, sender);
    if !manual_invoker_allowed(
        &trigger_config,
        &sender.to_hex().to_string(),
        is_creator_or_admin,
        is_known_principal,
    )? {
        return Err("Caller is not allowed to invoke this automation".to_string());
    }

    let input = parse_json_object(&input_json, "input_json")?;
    validate_manual_input(&trigger_config, &input)?;

    // Reducers are serialized and transactional, so this lookup + insert is
    // an atomic idempotency boundary without a second table or unique index.
    let duplicate = ctx
        .db
        .automation_event_queue()
        .by_rule()
        .filter(&automation_id)
        .any(|event| {
            event.invoked_by == Some(sender)
                && event.idempotency_key.as_deref() == Some(idempotency_key.as_str())
        });
    if duplicate {
        return Ok(());
    }

    let payload = build_manual_payload(&input, automation_id, sender, &idempotency_key)?;
    let queue_id = insert_event(
        ctx,
        &rule,
        AutomationTriggerKind::Manual,
        payload.to_string(),
        Some(sender),
        Some(idempotency_key),
    );
    try_process_inline(
        ctx,
        queue_id,
        inline_claim_label(&rule.mode, "manual-invocation"),
    )?;
    bump_manual_rule(ctx, automation_id);
    Ok(())
}

#[reducer]
pub fn delete_automation(ctx: &ReducerContext, automation_id: u64) -> Result<(), String> {
    let rule = require_rule_owner(ctx, automation_id, "delete automation")?;
    delete_schedule_jobs_for_rule(ctx, automation_id);
    for a in ctx
        .db
        .automation_action()
        .by_rule()
        .filter(&automation_id)
        .collect::<Vec<_>>()
    {
        ctx.db.automation_action().id().delete(a.id);
    }
    for c in ctx
        .db
        .automation_condition()
        .by_rule()
        .filter(&automation_id)
        .collect::<Vec<_>>()
    {
        ctx.db.automation_condition().id().delete(c.id);
    }
    for cap in ctx
        .db
        .automation_capability()
        .by_rule()
        .filter(&automation_id)
        .collect::<Vec<_>>()
    {
        ctx.db.automation_capability().id().delete(cap.id);
    }
    ctx.db.automation_rule().id().delete(rule.id);
    stop_cron_tick_if_unused(ctx);
    Ok(())
}

/// Process one queued event. In v0 this executes dry-run actions only.
#[reducer]
pub fn process_automation_event(ctx: &ReducerContext, queue_id: u64) -> Result<(), String> {
    let event = ctx
        .db
        .automation_event_queue()
        .id()
        .find(queue_id)
        .ok_or("Automation event not found")?;
    let rule = ctx
        .db
        .automation_rule()
        .id()
        .find(event.automation_id)
        .ok_or("Automation rule not found")?;
    require_creator_or_admin(ctx, rule.created_by, "process automation events")?;
    process_automation_event_inner(ctx, queue_id, Some("manual".to_string()))
}

/// Process pending events without needing a dedicated worker yet.
#[reducer]
pub fn process_pending_automation_events(ctx: &ReducerContext, limit: u32) -> Result<(), String> {
    let max = limit.clamp(1, 100);
    let events: Vec<u64> = ctx
        .db
        .automation_event_queue()
        .iter()
        .filter(|e| e.status == AutomationEventStatus::Pending)
        .take(max as usize)
        .map(|e| e.id)
        .collect();

    for queue_id in events {
        if let Some(event) = ctx.db.automation_event_queue().id().find(queue_id) {
            if let Some(rule) = ctx.db.automation_rule().id().find(event.automation_id) {
                require_creator_or_admin(ctx, rule.created_by, "process automation events")?;
                process_automation_event_inner(ctx, queue_id, Some("manual-batch".to_string()))?;
            }
        }
    }
    Ok(())
}

#[reducer]
pub fn run_scheduled_automation(
    ctx: &ReducerContext,
    job: AutomationScheduleJob,
) -> Result<(), String> {
    let Some(rule) = ctx.db.automation_rule().id().find(job.automation_id) else {
        return Ok(());
    };
    if !rule.enabled || rule.trigger_kind != AutomationTriggerKind::Scheduled {
        return Ok(());
    }
    if rule_is_expired(ctx, &rule) {
        disable_automation_inner(ctx, rule);
        return Ok(());
    }

    enqueue_scheduled_event(ctx, &rule, "schedule")?;
    bump_scheduled_rule(ctx, rule);
    Ok(())
}

#[reducer]
pub fn run_automation_cron_tick(
    ctx: &ReducerContext,
    _job: AutomationCronTick,
) -> Result<(), String> {
    let due: Vec<u64> = ctx
        .db
        .automation_rule()
        .iter()
        .filter(|r| {
            r.enabled
                && r.trigger_kind == AutomationTriggerKind::Scheduled
                && r.schedule_kind == AutomationScheduleKind::Cron
                && !rule_is_expired(ctx, r)
                && cron_rule_due(r, ctx.timestamp)
        })
        .map(|r| r.id)
        .collect();

    for automation_id in due {
        if let Some(rule) = ctx.db.automation_rule().id().find(automation_id) {
            enqueue_scheduled_event(ctx, &rule, "cron")?;
            bump_scheduled_rule(ctx, rule);
        }
    }
    stop_cron_tick_if_unused(ctx);
    Ok(())
}

pub(crate) fn enqueue_page_created(ctx: &ReducerContext, page_id: u64) {
    if let Some(page) = ctx.db.page().id().find(page_id) {
        let payload = json!({
            "event_type": "page_created",
            "page_id": page.id,
            "parent_id": page.parent_id,
            "parent_pk": page.parent_pk,
            "page_type": page_type_name(&page.page_type),
            "title": page.title,
        });
        let _ = enqueue_matching_automations(ctx, AutomationTriggerKind::PageCreated, payload);
    }
}

pub(crate) fn enqueue_page_updated(ctx: &ReducerContext, page_id: u64) {
    if let Some(page) = ctx.db.page().id().find(page_id) {
        let payload = json!({
            "event_type": "page_updated",
            "page_id": page.id,
            "parent_id": page.parent_id,
            "parent_pk": page.parent_pk,
            "page_type": page_type_name(&page.page_type),
            "title": page.title,
        });
        let _ = enqueue_matching_automations(ctx, AutomationTriggerKind::PageUpdated, payload);
    }
}

pub(crate) fn enqueue_page_deleted(ctx: &ReducerContext, page_id: u64) {
    if let Some(page) = ctx.db.page().id().find(page_id) {
        let payload = json!({
            "event_type": "page_deleted",
            "page_id": page.id,
            "parent_id": page.parent_id,
            "parent_pk": page.parent_pk,
            "page_type": page_type_name(&page.page_type),
            "title": page.title,
        });
        let _ = enqueue_matching_automations(ctx, AutomationTriggerKind::PageDeleted, payload);
    }
}

pub(crate) fn enqueue_property_changed(
    ctx: &ReducerContext,
    page_id: u64,
    property_definition_id: u64,
) {
    let payload = json!({
        "event_type": "property_changed",
        "page_id": page_id,
        "property_definition_id": property_definition_id,
    });
    let _ = enqueue_matching_automations(ctx, AutomationTriggerKind::PropertyChanged, payload);
}

fn enqueue_matching_automations(
    ctx: &ReducerContext,
    trigger_kind: AutomationTriggerKind,
    payload: Value,
) -> Result<(), String> {
    let rules: Vec<AutomationRule> = ctx
        .db
        .automation_rule()
        .iter()
        .filter(|r| {
            r.enabled && r.trigger_kind == trigger_kind && trigger_matches_payload(r, &payload)
        })
        .collect();

    for rule in rules {
        let queue_id = insert_event(
            ctx,
            &rule,
            trigger_kind.clone(),
            payload.to_string(),
            None,
            None,
        );
        try_process_inline(ctx, queue_id, inline_claim_label(&rule.mode, "inline"))?;
    }
    Ok(())
}

/// Process an event inline (inside the triggering transaction) unless the
/// recursion-depth cap is reached, in which case the event stays Pending.
fn try_process_inline(ctx: &ReducerContext, queue_id: u64, claimed_by: String) -> Result<(), String> {
    let depth = INLINE_EXEC_DEPTH.with(Cell::get);
    if depth >= MAX_INLINE_EXEC_DEPTH {
        log::warn!(
            "automation event {queue_id}: inline execution depth {depth} reached; leaving Pending"
        );
        return Ok(());
    }
    INLINE_EXEC_DEPTH.with(|d| d.set(depth + 1));
    let result = process_automation_event_inner(ctx, queue_id, Some(claimed_by));
    INLINE_EXEC_DEPTH.with(|d| d.set(depth));
    result
}

fn inline_claim_label(mode: &AutomationMode, source: &str) -> String {
    match mode {
        AutomationMode::DryRun => format!("{source}-dry-run"),
        AutomationMode::Live => format!("{source}-live"),
    }
}

fn enqueue_scheduled_event(
    ctx: &ReducerContext,
    rule: &AutomationRule,
    source: &str,
) -> Result<(), String> {
    let payload = json!({
        "event_type": "scheduled",
        "source": source,
        "automation_id": rule.id,
        "tick_count": rule.tick_count + 1,
        "scheduled_at_micros": ctx.timestamp.to_micros_since_unix_epoch(),
    });
    let queue_id = insert_event(
        ctx,
        rule,
        AutomationTriggerKind::Scheduled,
        payload.to_string(),
        None,
        None,
    );
    try_process_inline(ctx, queue_id, inline_claim_label(&rule.mode, source))?;
    Ok(())
}

fn insert_event(
    ctx: &ReducerContext,
    rule: &AutomationRule,
    trigger_kind: AutomationTriggerKind,
    trigger_payload: String,
    invoked_by: Option<Identity>,
    idempotency_key: Option<String>,
) -> u64 {
    let row = ctx
        .db
        .automation_event_queue()
        .insert(AutomationEventQueue {
            id: next_automation_event_queue_id(ctx),
            automation_id: rule.id,
            trigger_kind,
            trigger_payload,
            status: AutomationEventStatus::Pending,
            attempts: 0,
            claimed_by: None,
            error: None,
            created_at: ctx.timestamp,
            updated_at: ctx.timestamp,
            invoked_by,
            idempotency_key,
        });
    row.id
}

fn process_automation_event_inner(
    ctx: &ReducerContext,
    queue_id: u64,
    claimed_by: Option<String>,
) -> Result<(), String> {
    let event = ctx
        .db
        .automation_event_queue()
        .id()
        .find(queue_id)
        .ok_or("Automation event not found")?;
    if event.status == AutomationEventStatus::Completed
        || event.status == AutomationEventStatus::Failed
        || event.status == AutomationEventStatus::Skipped
    {
        return Ok(());
    }

    let rule = ctx
        .db
        .automation_rule()
        .id()
        .find(event.automation_id)
        .ok_or("Automation rule not found")?;
    let payload = parse_json_object(&event.trigger_payload, "trigger_payload")?;
    let effective_run_as = event.invoked_by.unwrap_or(rule.run_as);

    ctx.db
        .automation_event_queue()
        .id()
        .update(AutomationEventQueue {
            status: AutomationEventStatus::Running,
            attempts: event.attempts + 1,
            claimed_by,
            updated_at: ctx.timestamp,
            ..event
        });

    if !conditions_match(ctx, rule.id, &payload)? {
        insert_run_log(
            ctx,
            queue_id,
            None,
            true,
            true,
            "Conditions did not match; no actions would run".to_string(),
            json!({"condition_result":"skipped"}).to_string(),
        );
        update_event_status(ctx, queue_id, AutomationEventStatus::Skipped, None);
        return Ok(());
    }

    let mut actions: Vec<AutomationAction> = ctx
        .db
        .automation_action()
        .by_rule()
        .filter(&rule.id)
        .collect();
    actions.sort_by_key(|a| a.order);

    if actions.is_empty() {
        insert_run_log(
            ctx,
            queue_id,
            None,
            true,
            true,
            "No actions configured".to_string(),
            "{}".to_string(),
        );
        update_event_status(ctx, queue_id, AutomationEventStatus::Completed, None);
        return Ok(());
    }

    if rule.mode == AutomationMode::DryRun {
        for action in actions {
            insert_run_log(
                ctx,
                queue_id,
                Some(action.id),
                true,
                true,
                format!("Would execute {}", action_kind_name(&action.action_kind)),
                json!({
                    "action_kind": action_kind_name(&action.action_kind),
                    "config": parse_json_object(&action.config, "action config")?,
                    "trigger_payload": payload,
                })
                .to_string(),
            );
        }
        update_event_status(ctx, queue_id, AutomationEventStatus::Completed, None);
        return Ok(());
    }

    // Live execution: event triggers use rule.run_as; Manual triggers use the
    // recorded invoker so generated controls cannot borrow the author's ACLs.
    // An action failure logs and marks the event Failed but returns Ok — an
    // Err here would roll back the triggering transaction (and the logs).
    //
    // `OrchaJob` is asynchronous: the reducer only enqueues the job, and the
    // worker does the real work later. The event therefore stays `Running`
    // until every spawned job reaches a terminal state — `on_orcha_job_finished`
    // (called from the orcha completion path) logs the outcome and closes it.
    let mut awaiting_jobs = false;
    for action in actions {
        match execute_live_action(ctx, &rule, effective_run_as, &action, queue_id, &payload) {
            Ok(result) => {
                let is_job = matches!(action.action_kind, AutomationActionKind::OrchaJob);
                let message = if is_job {
                    awaiting_jobs = true;
                    match json_u64(result.get("job_id")) {
                        Some(job_id) => {
                            format!("Queued OrchaJob #{job_id} — waiting for the worker to run it")
                        }
                        None => "Queued OrchaJob — waiting for the worker to run it".to_string(),
                    }
                } else {
                    format!("Executed {}", action_kind_name(&action.action_kind))
                };
                insert_run_log(
                    ctx,
                    queue_id,
                    Some(action.id),
                    true,
                    false,
                    message,
                    result.to_string(),
                );
            }
            Err(err) => {
                insert_run_log(
                    ctx,
                    queue_id,
                    Some(action.id),
                    false,
                    false,
                    format!("{} failed: {err}", action_kind_name(&action.action_kind)),
                    json!({ "error": err }).to_string(),
                );
                update_event_status(ctx, queue_id, AutomationEventStatus::Failed, Some(err));
                return Ok(());
            }
        }
    }
    if awaiting_jobs {
        return Ok(());
    }
    update_event_status(ctx, queue_id, AutomationEventStatus::Completed, None);
    Ok(())
}

/// Nonce `execute_orcha_job` stamps on the jobs it spawns, so the run log, the
/// UI, and the completion hook can all find the job for a given action run.
fn automation_job_nonce(queue_id: u64, action_id: u64) -> String {
    format!("automation-q{queue_id}-a{action_id}")
}

/// Inverse of [`automation_job_nonce`]: `(queue_id, action_id)`, or `None` for
/// jobs that weren't spawned by an automation.
pub(crate) fn parse_automation_nonce(nonce: &str) -> Option<(u64, u64)> {
    let rest = nonce.strip_prefix("automation-q")?;
    let (queue, action) = rest.split_once("-a")?;
    Some((queue.parse().ok()?, action.parse().ok()?))
}

/// Called from `check_orcha_job_completion` when a job transitions to a
/// terminal state. For automation-spawned jobs this records the per-task
/// outcome in the run log and — once every job spawned by the same event is
/// terminal — moves the event from `Running` to `Completed` / `Failed`.
pub(crate) fn on_orcha_job_finished(
    ctx: &ReducerContext,
    job_id: u64,
    nonce: &str,
    tasks: &[OrchaTask],
    any_failed: bool,
) {
    let Some((queue_id, action_id)) = parse_automation_nonce(nonce) else {
        return;
    };
    let done = tasks.iter().filter(|t| t.status == "done").count();
    let failed = tasks.iter().filter(|t| t.status == "failed").count();
    let first_error = tasks
        .iter()
        .find(|t| t.status == "failed")
        .and_then(|t| t.result.as_deref())
        .map(|r| truncate_chars(r, 300));
    let message = if any_failed {
        format!(
            "OrchaJob #{job_id} failed: {failed} of {} task(s) failed{}",
            tasks.len(),
            first_error
                .as_deref()
                .map(|e| format!(" — {e}"))
                .unwrap_or_default()
        )
    } else {
        format!(
            "OrchaJob #{job_id} completed: {done}/{} task(s) done",
            tasks.len()
        )
    };
    let summary = json!({
        "job_id": job_id,
        "nonce": nonce,
        "status": if any_failed { "failed" } else { "complete" },
        "tasks": tasks
            .iter()
            .map(|t| json!({
                "id": t.id,
                "task_type": t.task_type,
                "status": t.status,
                "description": truncate_chars(&t.description, 200),
                "result": t.result.as_deref().map(|r| tail_chars(r, 400)),
            }))
            .collect::<Vec<_>>(),
    });
    insert_run_log(
        ctx,
        queue_id,
        Some(action_id),
        !any_failed,
        false,
        message.clone(),
        summary.to_string(),
    );

    let Some(event) = ctx.db.automation_event_queue().id().find(queue_id) else {
        return;
    };
    // Only the async-wait state is ours to close; a synchronous action failure
    // may already have marked the event Failed.
    if !matches!(event.status, AutomationEventStatus::Running) {
        return;
    }
    // A rule may spawn several jobs from one event (one per OrchaJob action):
    // the event closes when the last one lands, failing if any of them failed.
    let prefix = format!("automation-q{queue_id}-a");
    let siblings: Vec<_> = ctx
        .db
        .orcha_job()
        .iter()
        .filter(|j| j.nonce.as_deref().is_some_and(|n| n.starts_with(&prefix)))
        .collect();
    if siblings.iter().any(|j| j.status == "executing") {
        return;
    }
    if siblings.iter().any(|j| j.status == "failed") {
        let error = if any_failed {
            message
        } else {
            "An OrchaJob spawned by this run failed".to_string()
        };
        update_event_status(ctx, queue_id, AutomationEventStatus::Failed, Some(error));
    } else {
        update_event_status(ctx, queue_id, AutomationEventStatus::Completed, None);
    }
}

/// Execute one live action. Returns a JSON result for the run log, or an error
/// string (which fails the event without rolling back the transaction).
fn execute_live_action(
    ctx: &ReducerContext,
    rule: &AutomationRule,
    effective_run_as: Identity,
    action: &AutomationAction,
    queue_id: u64,
    payload: &Value,
) -> Result<Value, String> {
    let config = parse_json_object(&action.config, "action config")?;
    match action.action_kind {
        AutomationActionKind::CreatePage => {
            execute_create_page(ctx, rule, effective_run_as, &config, payload)
        }
        AutomationActionKind::UpdateProperty => {
            execute_update_property(ctx, rule, effective_run_as, &config, payload)
        }
        AutomationActionKind::OrchaJob => execute_orcha_job(
            ctx,
            effective_run_as,
            action.id,
            queue_id,
            &config,
            payload,
        ),
        AutomationActionKind::HttpRequest | AutomationActionKind::SendEmail => Err(
            "action requires the worker executor and cannot run in-module; keep the rule in DryRun"
                .to_string(),
        ),
    }
}

fn execute_create_page(
    ctx: &ReducerContext,
    rule: &AutomationRule,
    effective_run_as: Identity,
    config: &Value,
    payload: &Value,
) -> Result<Value, String> {
    let parent_id = json_u64(config.get("parent_id"));
    let title_template = config
        .get("title_template")
        .and_then(Value::as_str)
        .unwrap_or("Automation page");
    let title = render_template(title_template, payload).trim().to_string();
    if title.is_empty() {
        return Err("rendered title is empty".to_string());
    }
    if let Some(pid) = parent_id {
        let parent = ctx
            .db
            .page()
            .id()
            .find(pid)
            .ok_or(format!("parent page {pid} not found"))?;
        if parent.deleted_at.is_some() {
            return Err(format!("parent page {pid} is deleted"));
        }
        if !can_write_page(ctx, pid, effective_run_as) {
            return Err(format!(
                "execution principal lacks write access on parent page {pid}"
            ));
        }
    }
    let page_id = create_component_tree_page_inner(
        ctx,
        parent_id,
        PageType::Doc,
        title.clone(),
        ActorType::Agent(format!("automation:{}", rule.id)),
    )?;
    Ok(json!({ "page_id": page_id, "title": title }))
}

fn execute_update_property(
    ctx: &ReducerContext,
    rule: &AutomationRule,
    effective_run_as: Identity,
    config: &Value,
    payload: &Value,
) -> Result<Value, String> {
    let property_definition_id = json_u64(config.get("property_definition_id"))
        .ok_or("action config.property_definition_id is required")?;
    // Target page: explicit config.page_id, else the payload field named by
    // config.page_id_field (default "page_id" — the common event-trigger case).
    let page_id = match json_u64(config.get("page_id")) {
        Some(id) => id,
        None => {
            let field = config
                .get("page_id_field")
                .and_then(Value::as_str)
                .unwrap_or("page_id");
            json_u64(payload.get(field)).ok_or(format!(
                "trigger payload has no usable '{field}' field to select a target page"
            ))?
        }
    };
    ctx.db
        .page()
        .id()
        .find(page_id)
        .ok_or(format!("page {page_id} not found"))?;
    if !can_write_page(ctx, page_id, effective_run_as) {
        return Err(format!(
            "execution principal lacks write access on page {page_id}"
        ));
    }
    let def = ctx
        .db
        .property_definition()
        .id()
        .find(property_definition_id)
        .ok_or(format!(
            "property definition {property_definition_id} not found"
        ))?;
    let raw = resolve_property_action_value(config, payload)?;
    let value = coerce_property_value(&def.property_type, raw)?;
    set_property_value_inner(
        ctx,
        page_id,
        property_definition_id,
        value,
        ActorType::Agent(format!("automation:{}", rule.id)),
    )?;
    Ok(json!({
        "page_id": page_id,
        "property_definition_id": property_definition_id,
    }))
}

fn execute_orcha_job(
    ctx: &ReducerContext,
    effective_run_as: Identity,
    action_id: u64,
    queue_id: u64,
    config: &Value,
    payload: &Value,
) -> Result<Value, String> {
    let prompt_template = config
        .get("prompt_template")
        .and_then(Value::as_str)
        .ok_or("action config.prompt_template is required")?;
    let prompt = render_template(prompt_template, payload).trim().to_string();
    if prompt.is_empty() {
        return Err("rendered prompt is empty".to_string());
    }
    let page_id = config
        .get("page_id_field")
        .and_then(Value::as_str)
        .and_then(|f| json_u64(payload.get(f)))
        .or_else(|| json_u64(payload.get("page_id")));
    // The AI user whose credentials and governed connection run this job. An
    // explicit `config.ai_user_id` wins; otherwise the run-as principal itself
    // when it is an AI user — "Runs as Kira" means the job is Kira's, using her
    // key. Without either, the worker falls back to its default provider, which
    // a deployment may not configure at all (the job then fails at claim time).
    let ai_user_id = json_u64(config.get("ai_user_id")).or_else(|| {
        ctx.db
            .ai_user_config()
            .identity()
            .find(effective_run_as)
            .map(|c| c.id)
    });
    if let Some(id) = ai_user_id {
        ctx.db
            .ai_user_config()
            .id()
            .find(id)
            .ok_or(format!("AI user {id} not found"))?;
        if ai_user_at_hard_cap(ctx, id) {
            return Err(format!("AI user {id} is at its monthly token cap"));
        }
    }
    let tier = config
        .get("tier")
        .and_then(Value::as_str)
        .map(str::to_string);
    // Same single-task graph the worker's `delegate` tool creates; the nonce
    // lets observers read back exactly this job.
    let nonce = automation_job_nonce(queue_id, action_id);
    let task_graph = json!([{
        "description": prompt,
        "task_type": "orchestrate",
        "depends_on": [],
        "required_capabilities": ["orchestrate"],
    }]);
    let job_id = create_job_inner(
        ctx,
        effective_run_as.to_hex().to_string(),
        prompt,
        page_id,
        ai_user_id,
        tier,
        nonce.clone(),
        None,
        task_graph.to_string(),
    )?;
    Ok(json!({
        "nonce": nonce,
        "page_id": page_id,
        "job_id": job_id,
        "ai_user_id": ai_user_id,
    }))
}

fn resolve_property_action_value<'a>(
    config: &'a Value,
    payload: &'a Value,
) -> Result<&'a Value, String> {
    if let Some(field) = config.get("value_field").and_then(Value::as_str) {
        let field = field.trim();
        if field.is_empty() {
            return Err("action config.value_field cannot be empty".to_string());
        }
        return payload.get(field).ok_or_else(|| {
            format!("trigger payload has no '{field}' field to use as the property value")
        });
    }
    config
        .get("value")
        .ok_or("action config.value or value_field is required".to_string())
}

/// Coerce a JSON action-config value into the typed `PropertyValue` matching
/// the target column. Computed columns (Ai) cannot be set by automations.
fn coerce_property_value(
    property_type: &PropertyType,
    raw: &Value,
) -> Result<PropertyValue, String> {
    fn as_string(raw: &Value) -> Option<String> {
        raw.as_str().map(str::to_string)
    }
    fn as_string_vec(raw: &Value) -> Option<Vec<String>> {
        raw.as_array()?
            .iter()
            .map(|v| v.as_str().map(str::to_string))
            .collect()
    }
    fn as_u64_vec(raw: &Value) -> Option<Vec<u64>> {
        raw.as_array()?.iter().map(|v| json_u64(Some(v))).collect()
    }
    match property_type {
        PropertyType::Text => as_string(raw)
            .map(PropertyValue::Text)
            .ok_or("value must be a string for a Text property".to_string()),
        PropertyType::Url => as_string(raw)
            .map(PropertyValue::Url)
            .ok_or("value must be a string for a Url property".to_string()),
        PropertyType::Select => as_string(raw)
            .map(PropertyValue::Select)
            .ok_or("value must be a string for a Select property".to_string()),
        PropertyType::Number => raw
            .as_f64()
            .map(PropertyValue::Number)
            .ok_or("value must be a number for a Number property".to_string()),
        PropertyType::Date => json_u64(Some(raw))
            .map(PropertyValue::Date)
            .ok_or("value must be a unix-ms number for a Date property".to_string()),
        PropertyType::Checkbox => raw
            .as_bool()
            .map(PropertyValue::Checkbox)
            .ok_or("value must be a boolean for a Checkbox property".to_string()),
        PropertyType::MultiSelect => as_string_vec(raw)
            .map(PropertyValue::MultiSelect)
            .ok_or("value must be an array of strings for a MultiSelect property".to_string()),
        PropertyType::Person => as_string_vec(raw)
            .map(PropertyValue::Person)
            .ok_or("value must be an array of identity strings for a Person property".to_string()),
        PropertyType::Relation => as_u64_vec(raw)
            .map(PropertyValue::Relation)
            .ok_or("value must be an array of page ids for a Relation property".to_string()),
        PropertyType::File => {
            Err("File properties cannot be set by automations yet".to_string())
        }
        _ => Err("computed property types cannot be set by automations".to_string()),
    }
}

/// Replace `{{field}}` tokens with the matching top-level trigger-payload
/// scalar; unknown fields render as empty. Unterminated tokens pass through.
fn render_template(template: &str, payload: &Value) -> String {
    let mut out = String::with_capacity(template.len());
    let mut rest = template;
    while let Some(start) = rest.find("{{") {
        out.push_str(&rest[..start]);
        let after = &rest[start + 2..];
        match after.find("}}") {
            Some(end) => {
                let key = after[..end].trim();
                if let Some(v) = payload.get(key) {
                    out.push_str(&json_scalar_as_string(v));
                }
                rest = &after[end + 2..];
            }
            None => {
                out.push_str(&rest[start..]);
                rest = "";
            }
        }
    }
    out.push_str(rest);
    out
}

fn action_kind_is_in_module(kind: &AutomationActionKind) -> bool {
    matches!(
        kind,
        AutomationActionKind::CreatePage
            | AutomationActionKind::UpdateProperty
            | AutomationActionKind::OrchaJob
    )
}

fn sender_is_ai_user(ctx: &ReducerContext) -> bool {
    ctx.db
        .ai_user_config()
        .identity()
        .find(ctx.sender())
        .is_some()
}

fn is_known_workspace_principal(ctx: &ReducerContext, identity: Identity) -> bool {
    ctx.db
        .user()
        .identity()
        .find(identity)
        .is_some_and(|u| u.is_authenticated)
        || ctx
            .db
            .ai_user_profile()
            .identity()
            .find(identity)
            .is_some()
}

fn validate_idempotency_key(key: &str) -> Result<(), String> {
    if key.is_empty() || key.len() > MAX_IDEMPOTENCY_KEY_BYTES {
        return Err(format!(
            "idempotency_key must be 1-{MAX_IDEMPOTENCY_KEY_BYTES} characters"
        ));
    }
    if !key
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'.' | b'_' | b':' | b'-'))
    {
        return Err(
            "idempotency_key may contain only letters, numbers, '.', '_', ':', and '-'".to_string(),
        );
    }
    Ok(())
}

fn config_string_array(config: &Value, key: &str) -> Result<Option<Vec<String>>, String> {
    let Some(value) = config.get(key) else {
        return Ok(None);
    };
    let values = value
        .as_array()
        .ok_or_else(|| format!("trigger_config.{key} must be an array of strings"))?;
    values
        .iter()
        .map(|value| {
            value
                .as_str()
                .map(str::trim)
                .filter(|value| !value.is_empty())
                .map(str::to_string)
                .ok_or_else(|| format!("trigger_config.{key} entries must be non-empty strings"))
        })
        .collect::<Result<Vec<_>, _>>()
        .map(Some)
}

fn validate_manual_trigger_config(config: &Value) -> Result<(), String> {
    let policy = config
        .get("invoker_policy")
        .and_then(Value::as_str)
        .unwrap_or("creator_or_admin");
    if !matches!(policy, "creator_or_admin" | "workspace" | "identities") {
        return Err(
            "trigger_config.invoker_policy must be creator_or_admin, workspace, or identities"
                .to_string(),
        );
    }

    let identities = config_string_array(config, "allowed_invoker_identities")?;
    if policy == "identities" && identities.as_ref().is_none_or(Vec::is_empty) {
        return Err(
            "identities policy requires trigger_config.allowed_invoker_identities".to_string(),
        );
    }
    if let Some(identities) = identities {
        for identity in identities {
            let decoded = hex::decode(&identity).map_err(|_| {
                "allowed_invoker_identities entries must be 64-character hex identities".to_string()
            })?;
            if decoded.len() != 32 {
                return Err(
                    "allowed_invoker_identities entries must be 64-character hex identities"
                        .to_string(),
                );
            }
        }
    }

    let allowed = config_string_array(config, "allowed_input_fields")?;
    let required = config_string_array(config, "required_input_fields")?.unwrap_or_default();
    for field in allowed.iter().flatten().chain(required.iter()) {
        if MANUAL_RESERVED_FIELDS.contains(&field.as_str()) {
            return Err(format!(
                "'{field}' is reserved and cannot be declared as a Manual input field"
            ));
        }
        if field.len() > 128 {
            return Err("Manual input field names cannot exceed 128 bytes".to_string());
        }
    }
    if let Some(allowed) = allowed {
        for field in required {
            if !allowed.contains(&field) {
                return Err(format!(
                    "required input field '{field}' is missing from allowed_input_fields"
                ));
            }
        }
    }
    Ok(())
}

fn manual_invoker_allowed(
    config: &Value,
    sender_hex: &str,
    is_creator_or_admin: bool,
    is_known_principal: bool,
) -> Result<bool, String> {
    let policy = config
        .get("invoker_policy")
        .and_then(Value::as_str)
        .unwrap_or("creator_or_admin");
    match policy {
        "creator_or_admin" => Ok(is_creator_or_admin),
        "workspace" => Ok(is_creator_or_admin || is_known_principal),
        "identities" => Ok(is_creator_or_admin
            || config_string_array(config, "allowed_invoker_identities")?
                .unwrap_or_default()
                .iter()
                .any(|identity| identity.eq_ignore_ascii_case(sender_hex))),
        _ => Err("Unknown Manual invoker policy".to_string()),
    }
}

fn validate_manual_input(config: &Value, input: &Value) -> Result<(), String> {
    let input = input
        .as_object()
        .ok_or("input_json must be a JSON object")?;
    for reserved in MANUAL_RESERVED_FIELDS {
        if input.contains_key(reserved) {
            return Err(format!(
                "Manual input cannot set server-reserved field '{reserved}'"
            ));
        }
    }
    if let Some(allowed) = config_string_array(config, "allowed_input_fields")? {
        for field in input.keys() {
            if !allowed.contains(field) {
                return Err(format!("Manual input field '{field}' is not allowed"));
            }
        }
    }
    for required in config_string_array(config, "required_input_fields")?.unwrap_or_default() {
        if !input.contains_key(&required) {
            return Err(format!("Manual input field '{required}' is required"));
        }
    }
    Ok(())
}

fn build_manual_payload(
    input: &Value,
    automation_id: u64,
    invoked_by: Identity,
    idempotency_key: &str,
) -> Result<Value, String> {
    let mut payload = input
        .as_object()
        .cloned()
        .ok_or("input_json must be a JSON object")?;
    payload.insert("event_type".to_string(), json!("manual"));
    payload.insert("automation_id".to_string(), json!(automation_id));
    payload.insert(
        "invoked_by".to_string(),
        json!(invoked_by.to_hex().to_string()),
    );
    payload.insert("idempotency_key".to_string(), json!(idempotency_key));
    Ok(Value::Object(payload))
}

/// Any structural edit to a Live rule demotes it to DryRun — a changed graph
/// needs fresh human approval via `set_automation_mode`.
fn demote_live_rule_on_edit(ctx: &ReducerContext, automation_id: u64) {
    if let Some(rule) = ctx.db.automation_rule().id().find(automation_id) {
        if rule.mode == AutomationMode::Live {
            ctx.db.automation_rule().id().update(AutomationRule {
                mode: AutomationMode::DryRun,
                updated_at: ctx.timestamp,
                ..rule
            });
        }
    }
}

fn insert_run_log(
    ctx: &ReducerContext,
    queue_id: u64,
    action_id: Option<u64>,
    success: bool,
    dry_run: bool,
    message: String,
    result_json: String,
) {
    ctx.db.automation_run_log().insert(AutomationRunLog {
        id: next_automation_run_log_id(ctx),
        queue_id,
        action_id,
        success,
        dry_run,
        message,
        result_json,
        created_at: ctx.timestamp,
    });
}

fn update_event_status(
    ctx: &ReducerContext,
    queue_id: u64,
    status: AutomationEventStatus,
    error: Option<String>,
) {
    if let Some(event) = ctx.db.automation_event_queue().id().find(queue_id) {
        ctx.db
            .automation_event_queue()
            .id()
            .update(AutomationEventQueue {
                status,
                error,
                updated_at: ctx.timestamp,
                ..event
            });
    }
}

fn require_rule_owner(
    ctx: &ReducerContext,
    automation_id: u64,
    action: &str,
) -> Result<AutomationRule, String> {
    let rule = ctx
        .db
        .automation_rule()
        .id()
        .find(automation_id)
        .ok_or("Automation rule not found")?;
    require_creator_or_admin(ctx, rule.created_by, action)?;
    Ok(rule)
}

fn validate_rule(ctx: &ReducerContext, rule: &AutomationRule) -> Result<(), String> {
    if rule.name.trim().is_empty() {
        return Err("Automation name cannot be empty".to_string());
    }
    if rule.canonical_description.trim().is_empty() {
        return Err("Automation must include a canonical human-readable description".to_string());
    }
    let trigger_config = parse_json_object(&rule.trigger_config, "trigger_config")?;
    parse_json_object(&rule.schedule_config, "schedule_config")?;

    match rule.trigger_kind {
        AutomationTriggerKind::Scheduled => validate_schedule(rule)?,
        AutomationTriggerKind::Manual => validate_manual_trigger_config(&trigger_config)?,
        _ => {
            if rule.schedule_kind != AutomationScheduleKind::None {
                return Err("Only Scheduled triggers may use schedule_kind".to_string());
            }
        }
    }

    if ctx
        .db
        .automation_action()
        .by_rule()
        .filter(&rule.id)
        .next()
        .is_none()
    {
        return Err("Automation must have at least one action".to_string());
    }

    for action in ctx.db.automation_action().by_rule().filter(&rule.id) {
        parse_json_object(&action.config, "action config")?;
    }
    for condition in ctx.db.automation_condition().by_rule().filter(&rule.id) {
        parse_json_object(&condition.config, "condition config")?;
    }
    for capability in ctx.db.automation_capability().by_rule().filter(&rule.id) {
        parse_json_object(&capability.scope_config, "capability scope_config")?;
    }
    Ok(())
}

fn validate_schedule(rule: &AutomationRule) -> Result<(), String> {
    match rule.schedule_kind {
        AutomationScheduleKind::Interval => {
            let secs = interval_seconds(&rule.schedule_config)?;
            if secs == 0 {
                return Err("interval_seconds must be greater than zero".to_string());
            }
        }
        AutomationScheduleKind::OneShot => {
            run_at_micros(&rule.schedule_config)?;
        }
        AutomationScheduleKind::Cron => {
            let expr = cron_expression(&rule.schedule_config)?;
            parse_cron_fields(&expr)?;
            parse_timezone(&rule.timezone)?;
        }
        AutomationScheduleKind::None => {
            return Err("Scheduled trigger must use Interval, OneShot, or Cron".to_string());
        }
    }
    Ok(())
}

fn schedule_rule_if_needed(
    ctx: &ReducerContext,
    rule: &AutomationRule,
) -> Result<Option<Timestamp>, String> {
    if rule.trigger_kind != AutomationTriggerKind::Scheduled {
        return Ok(None);
    }
    match rule.schedule_kind {
        AutomationScheduleKind::Interval => {
            let secs = interval_seconds(&rule.schedule_config)?;
            let dur = Duration::from_secs(secs);
            ctx.db
                .automation_schedule_job()
                .insert(AutomationScheduleJob {
                    scheduled_id: 0,
                    scheduled_at: dur.into(),
                    automation_id: rule.id,
                });
            Ok(Some(ctx.timestamp + dur))
        }
        AutomationScheduleKind::OneShot => {
            let run_at =
                Timestamp::from_micros_since_unix_epoch(run_at_micros(&rule.schedule_config)?);
            ctx.db
                .automation_schedule_job()
                .insert(AutomationScheduleJob {
                    scheduled_id: 0,
                    scheduled_at: run_at.into(),
                    automation_id: rule.id,
                });
            Ok(Some(run_at))
        }
        AutomationScheduleKind::Cron => {
            ensure_cron_tick(ctx);
            Ok(None)
        }
        AutomationScheduleKind::None => Ok(None),
    }
}

fn delete_schedule_jobs_for_rule(ctx: &ReducerContext, automation_id: u64) {
    let ids: Vec<u64> = ctx
        .db
        .automation_schedule_job()
        .iter()
        .filter(|j| j.automation_id == automation_id)
        .map(|j| j.scheduled_id)
        .collect();
    for id in ids {
        ctx.db.automation_schedule_job().scheduled_id().delete(id);
    }
}

fn ensure_cron_tick(ctx: &ReducerContext) {
    if ctx.db.automation_cron_tick().iter().next().is_some() {
        return;
    }
    ctx.db.automation_cron_tick().insert(AutomationCronTick {
        scheduled_id: 0,
        scheduled_at: Duration::from_secs(60).into(),
    });
}

fn stop_cron_tick_if_unused(ctx: &ReducerContext) {
    let has_enabled_cron = ctx.db.automation_rule().iter().any(|r| {
        r.enabled
            && r.trigger_kind == AutomationTriggerKind::Scheduled
            && r.schedule_kind == AutomationScheduleKind::Cron
    });
    if has_enabled_cron {
        return;
    }
    let ids: Vec<u64> = ctx
        .db
        .automation_cron_tick()
        .iter()
        .map(|j| j.scheduled_id)
        .collect();
    for id in ids {
        ctx.db.automation_cron_tick().scheduled_id().delete(id);
    }
}

fn disable_automation_inner(ctx: &ReducerContext, rule: AutomationRule) {
    delete_schedule_jobs_for_rule(ctx, rule.id);
    ctx.db.automation_rule().id().update(AutomationRule {
        enabled: false,
        next_run_at: None,
        updated_at: ctx.timestamp,
        ..rule
    });
    stop_cron_tick_if_unused(ctx);
}

fn bump_scheduled_rule(ctx: &ReducerContext, rule: AutomationRule) {
    let tick_count = rule.tick_count + 1;
    let max_reached = rule.max_ticks.is_some_and(|m| tick_count >= m);
    if max_reached || rule.schedule_kind == AutomationScheduleKind::OneShot {
        ctx.db.automation_rule().id().update(AutomationRule {
            enabled: false,
            last_run_at: Some(ctx.timestamp),
            next_run_at: None,
            tick_count,
            updated_at: ctx.timestamp,
            ..rule
        });
        delete_schedule_jobs_for_rule(ctx, rule.id);
        stop_cron_tick_if_unused(ctx);
        return;
    }

    let next_run_at = match rule.schedule_kind {
        AutomationScheduleKind::Interval => interval_seconds(&rule.schedule_config)
            .ok()
            .map(|secs| ctx.timestamp + Duration::from_secs(secs)),
        _ => None,
    };
    ctx.db.automation_rule().id().update(AutomationRule {
        last_run_at: Some(ctx.timestamp),
        next_run_at,
        tick_count,
        updated_at: ctx.timestamp,
        ..rule
    });
}

fn bump_manual_rule(ctx: &ReducerContext, automation_id: u64) {
    let Some(rule) = ctx.db.automation_rule().id().find(automation_id) else {
        return;
    };
    let tick_count = rule.tick_count + 1;
    let max_reached = rule.max_ticks.is_some_and(|max| tick_count >= max);
    ctx.db.automation_rule().id().update(AutomationRule {
        enabled: rule.enabled && !max_reached,
        last_run_at: Some(ctx.timestamp),
        next_run_at: None,
        tick_count,
        updated_at: ctx.timestamp,
        ..rule
    });
}

fn rule_is_expired(ctx: &ReducerContext, rule: &AutomationRule) -> bool {
    if let Some(expires_at) = rule.expires_at {
        if ctx.timestamp >= expires_at {
            return true;
        }
    }
    rule.max_ticks.is_some_and(|m| rule.tick_count >= m)
}

fn trigger_matches_payload(rule: &AutomationRule, payload: &Value) -> bool {
    let Ok(config) = parse_json_object(&rule.trigger_config, "trigger_config") else {
        return false;
    };
    field_matches_optional_u64(&config, "page_id", payload, "page_id")
        && field_matches_optional_u64(&config, "parent_id", payload, "parent_id")
        && field_matches_optional_u64(&config, "parent_pk", payload, "parent_pk")
        && field_matches_optional_u64(
            &config,
            "property_definition_id",
            payload,
            "property_definition_id",
        )
}

fn field_matches_optional_u64(
    config: &Value,
    config_field: &str,
    payload: &Value,
    payload_field: &str,
) -> bool {
    let Some(expected) = json_u64(config.get(config_field)) else {
        return true;
    };
    json_u64(payload.get(payload_field)) == Some(expected)
}

fn conditions_match(
    ctx: &ReducerContext,
    automation_id: u64,
    payload: &Value,
) -> Result<bool, String> {
    let mut conditions: Vec<AutomationCondition> = ctx
        .db
        .automation_condition()
        .by_rule()
        .filter(&automation_id)
        .collect();
    conditions.sort_by_key(|c| c.order);

    for condition in conditions {
        match condition.condition_kind {
            AutomationConditionKind::PayloadFieldEquals => {
                let config = parse_json_object(&condition.config, "condition config")?;
                let field = config
                    .get("field")
                    .and_then(Value::as_str)
                    .ok_or("PayloadFieldEquals condition requires field")?;
                let expected = config
                    .get("equals")
                    .map(json_scalar_as_string)
                    .ok_or("PayloadFieldEquals condition requires equals")?;
                let actual = payload.get(field).map(json_scalar_as_string);
                if actual.as_deref() != Some(expected.as_str()) {
                    return Ok(false);
                }
            }
        }
    }
    Ok(true)
}

fn parse_json_object(raw: &str, label: &str) -> Result<Value, String> {
    let value: Value =
        serde_json::from_str(raw).map_err(|e| format!("Invalid {label} JSON: {e}"))?;
    if !value.is_object() {
        return Err(format!("{label} must be a JSON object"));
    }
    Ok(value)
}

fn json_u64(value: Option<&Value>) -> Option<u64> {
    match value? {
        Value::Number(n) => n.as_u64(),
        Value::String(s) => s.parse::<u64>().ok(),
        _ => None,
    }
}

fn json_scalar_as_string(value: &Value) -> String {
    match value {
        Value::String(s) => s.clone(),
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Null => "null".to_string(),
        other => other.to_string(),
    }
}

fn interval_seconds(config: &str) -> Result<u64, String> {
    let config = parse_json_object(config, "schedule_config")?;
    json_u64(config.get("interval_seconds"))
        .ok_or("schedule_config.interval_seconds is required".to_string())
}

fn run_at_micros(config: &str) -> Result<i64, String> {
    let config = parse_json_object(config, "schedule_config")?;
    match config.get("run_at_micros") {
        Some(Value::Number(n)) => n
            .as_i64()
            .ok_or("schedule_config.run_at_micros must fit in i64".to_string()),
        Some(Value::String(s)) => s
            .parse::<i64>()
            .map_err(|_| "schedule_config.run_at_micros must be an integer".to_string()),
        _ => Err("schedule_config.run_at_micros is required".to_string()),
    }
}

fn cron_expression(config: &str) -> Result<String, String> {
    let config = parse_json_object(config, "schedule_config")?;
    config
        .get("expression")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .ok_or("schedule_config.expression is required for cron schedules".to_string())
}

fn cron_rule_due(rule: &AutomationRule, now: Timestamp) -> bool {
    if rule
        .last_run_at
        .is_some_and(|last| minute_bucket(last) == minute_bucket(now))
    {
        return false;
    }
    let Ok(expr) = cron_expression(&rule.schedule_config) else {
        return false;
    };
    // Evaluated in the rule's stored timezone (validated at enable time);
    // an unparseable zone falls back to UTC inside cron_matches.
    cron_matches(&expr, now, &rule.timezone).unwrap_or(false)
}

fn normalize_timezone(timezone: String) -> String {
    let trimmed = timezone.trim();
    if trimmed.is_empty() {
        "UTC".to_string()
    } else {
        trimmed.to_string()
    }
}

fn page_type_name(page_type: &PageType) -> &'static str {
    match page_type {
        PageType::Doc => "Doc",
        PageType::Database => "Database",
    }
}

fn action_kind_name(kind: &AutomationActionKind) -> &'static str {
    match kind {
        AutomationActionKind::HttpRequest => "HttpRequest",
        AutomationActionKind::SendEmail => "SendEmail",
        AutomationActionKind::CreatePage => "CreatePage",
        AutomationActionKind::UpdateProperty => "UpdateProperty",
        AutomationActionKind::OrchaJob => "OrchaJob",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn automation_job_nonce_round_trips() {
        let nonce = automation_job_nonce(42, 7);
        assert_eq!(nonce, "automation-q42-a7");
        assert_eq!(parse_automation_nonce(&nonce), Some((42, 7)));
        // Jobs from chat/editor (no nonce, or a `delegate` nonce) are not ours.
        assert_eq!(parse_automation_nonce(""), None);
        assert_eq!(parse_automation_nonce("delegate-1234"), None);
        assert_eq!(parse_automation_nonce("automation-q1"), None);
        assert_eq!(parse_automation_nonce("automation-qx-a1"), None);
    }

    #[test]
    fn render_template_substitutes_payload_fields() {
        let payload = json!({"page_id": 42, "title": "Dishes", "flag": true});
        assert_eq!(
            render_template("Log: {{title}} ({{page_id}})", &payload),
            "Log: Dishes (42)"
        );
        assert_eq!(render_template("{{ flag }}", &payload), "true");
        // Unknown fields render empty; unterminated tokens pass through.
        assert_eq!(render_template("x{{missing}}y", &payload), "xy");
        assert_eq!(render_template("x{{oops", &payload), "x{{oops");
        assert_eq!(render_template("plain", &payload), "plain");
    }

    #[test]
    fn coerce_property_value_maps_json_to_typed_values() {
        assert_eq!(
            coerce_property_value(&PropertyType::Text, &json!("hi")).unwrap(),
            PropertyValue::Text("hi".to_string())
        );
        assert_eq!(
            coerce_property_value(&PropertyType::Number, &json!(2.5)).unwrap(),
            PropertyValue::Number(2.5)
        );
        assert_eq!(
            coerce_property_value(&PropertyType::Date, &json!(1770000000000u64)).unwrap(),
            PropertyValue::Date(1770000000000)
        );
        assert_eq!(
            coerce_property_value(&PropertyType::Checkbox, &json!(true)).unwrap(),
            PropertyValue::Checkbox(true)
        );
        assert_eq!(
            coerce_property_value(&PropertyType::MultiSelect, &json!(["a", "b"])).unwrap(),
            PropertyValue::MultiSelect(vec!["a".to_string(), "b".to_string()])
        );
        assert_eq!(
            coerce_property_value(&PropertyType::Relation, &json!([1, "2"])).unwrap(),
            PropertyValue::Relation(vec![1, 2])
        );
        assert!(coerce_property_value(&PropertyType::Number, &json!("nope")).is_err());
        assert!(coerce_property_value(&PropertyType::Ai, &json!("x")).is_err());
    }

    #[test]
    fn manual_trigger_config_validates_policy_and_fields() {
        let identity = "11".repeat(32);
        let config = json!({
            "invoker_policy": "identities",
            "allowed_invoker_identities": [identity],
            "allowed_input_fields": ["ask_id", "status"],
            "required_input_fields": ["ask_id"],
        });
        assert!(validate_manual_trigger_config(&config).is_ok());
        assert!(manual_invoker_allowed(&config, &"11".repeat(32), false, false).unwrap());
        assert!(!manual_invoker_allowed(&config, &"22".repeat(32), false, true).unwrap());
        assert!(manual_invoker_allowed(&config, &"22".repeat(32), true, false).unwrap());

        assert!(validate_manual_trigger_config(&json!({
            "invoker_policy": "identities",
            "allowed_invoker_identities": [],
        }))
        .is_err());
        assert!(validate_manual_trigger_config(&json!({
            "allowed_input_fields": ["invoked_by"],
        }))
        .is_err());
        assert!(validate_manual_trigger_config(&json!({
            "allowed_input_fields": ["status"],
            "required_input_fields": ["ask_id"],
        }))
        .is_err());
    }

    #[test]
    fn manual_input_is_allowlisted_and_server_metadata_is_stamped() {
        let config = json!({
            "invoker_policy": "workspace",
            "allowed_input_fields": ["ask_id", "decision"],
            "required_input_fields": ["ask_id"],
        });
        let input = json!({"ask_id": 42, "decision": "accept"});
        assert!(validate_manual_input(&config, &input).is_ok());
        assert!(validate_manual_input(&config, &json!({"decision": "accept"})).is_err());
        assert!(validate_manual_input(&config, &json!({"ask_id": 42, "extra": true})).is_err());
        assert!(validate_manual_input(&json!({}), &json!({"event_type": "spoof"})).is_err());

        let identity = Identity::from_byte_array([7; 32]);
        let payload = build_manual_payload(&input, 9, identity, "message:button:1").unwrap();
        assert_eq!(payload.get("event_type"), Some(&json!("manual")));
        assert_eq!(payload.get("automation_id"), Some(&json!(9)));
        assert_eq!(
            payload.get("invoked_by"),
            Some(&json!(identity.to_hex().to_string()))
        );
        assert_eq!(payload.get("idempotency_key"), Some(&json!("message:button:1")));
    }

    #[test]
    fn manual_idempotency_keys_are_bounded_and_transport_safe() {
        assert!(validate_idempotency_key("message-12:button_4.retry").is_ok());
        assert!(validate_idempotency_key("").is_err());
        assert!(validate_idempotency_key("has spaces").is_err());
        assert!(validate_idempotency_key(&"x".repeat(MAX_IDEMPOTENCY_KEY_BYTES + 1)).is_err());
    }

    #[test]
    fn update_property_can_take_value_from_trigger_payload() {
        let config = json!({"value_field": "decision", "value": "ignored"});
        let payload = json!({"decision": "accepted"});
        assert_eq!(
            resolve_property_action_value(&config, &payload).unwrap(),
            &json!("accepted")
        );
        assert!(resolve_property_action_value(
            &json!({"value_field": "missing"}),
            &payload
        )
        .is_err());
        assert_eq!(
            resolve_property_action_value(&json!({"value": true}), &payload).unwrap(),
            &json!(true)
        );
    }
}
