// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddPropertyReducer from "../add_property_reducer";
import ClearPropertyValueReducer from "../clear_property_value_reducer";
import CreateDatabaseSchemaReducer from "../create_database_schema_reducer";
import CreatePageReducer from "../create_page_reducer";
import CreateViewReducer from "../create_view_reducer";
import DeletePageReducer from "../delete_page_reducer";
import DeletePropertyReducer from "../delete_property_reducer";
import DeleteViewReducer from "../delete_view_reducer";
import LoginReducer from "../login_reducer";
import LogoutReducer from "../logout_reducer";
import MovePageReducer from "../move_page_reducer";
import PurgePageReducer from "../purge_page_reducer";
import RegisterReducer from "../register_reducer";
import RenamePropertyReducer from "../rename_property_reducer";
import RenameViewReducer from "../rename_view_reducer";
import ReorderPropertyReducer from "../reorder_property_reducer";
import RestorePageReducer from "../restore_page_reducer";
import RestorePageToSnapshotReducer from "../restore_page_to_snapshot_reducer";
import SaveYjsStateReducer from "../save_yjs_state_reducer";
import SetDefaultViewReducer from "../set_default_view_reducer";
import SetPropertyValueReducer from "../set_property_value_reducer";
import SetUserProfileReducer from "../set_user_profile_reducer";
import TakeSnapshotReducer from "../take_snapshot_reducer";
import TakeSnapshotWithContentReducer from "../take_snapshot_with_content_reducer";
import UpdatePageContentReducer from "../update_page_content_reducer";
import UpdatePageTitleReducer from "../update_page_title_reducer";
import UpdatePropertyConfigReducer from "../update_property_config_reducer";
import UpdatePropertyTypeReducer from "../update_property_type_reducer";
import UpdateViewConfigReducer from "../update_view_config_reducer";

export type AddPropertyParams = __Infer<typeof AddPropertyReducer>;
export type ClearPropertyValueParams = __Infer<typeof ClearPropertyValueReducer>;
export type CreateDatabaseSchemaParams = __Infer<typeof CreateDatabaseSchemaReducer>;
export type CreatePageParams = __Infer<typeof CreatePageReducer>;
export type CreateViewParams = __Infer<typeof CreateViewReducer>;
export type DeletePageParams = __Infer<typeof DeletePageReducer>;
export type DeletePropertyParams = __Infer<typeof DeletePropertyReducer>;
export type DeleteViewParams = __Infer<typeof DeleteViewReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type MovePageParams = __Infer<typeof MovePageReducer>;
export type PurgePageParams = __Infer<typeof PurgePageReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type RenamePropertyParams = __Infer<typeof RenamePropertyReducer>;
export type RenameViewParams = __Infer<typeof RenameViewReducer>;
export type ReorderPropertyParams = __Infer<typeof ReorderPropertyReducer>;
export type RestorePageParams = __Infer<typeof RestorePageReducer>;
export type RestorePageToSnapshotParams = __Infer<typeof RestorePageToSnapshotReducer>;
export type SaveYjsStateParams = __Infer<typeof SaveYjsStateReducer>;
export type SetDefaultViewParams = __Infer<typeof SetDefaultViewReducer>;
export type SetPropertyValueParams = __Infer<typeof SetPropertyValueReducer>;
export type SetUserProfileParams = __Infer<typeof SetUserProfileReducer>;
export type TakeSnapshotParams = __Infer<typeof TakeSnapshotReducer>;
export type TakeSnapshotWithContentParams = __Infer<typeof TakeSnapshotWithContentReducer>;
export type UpdatePageContentParams = __Infer<typeof UpdatePageContentReducer>;
export type UpdatePageTitleParams = __Infer<typeof UpdatePageTitleReducer>;
export type UpdatePropertyConfigParams = __Infer<typeof UpdatePropertyConfigReducer>;
export type UpdatePropertyTypeParams = __Infer<typeof UpdatePropertyTypeReducer>;
export type UpdateViewConfigParams = __Infer<typeof UpdateViewConfigReducer>;

