// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  aiUserId: __t.u64().name("ai_user_id"),
  rootPageId: __t.u64().name("root_page_id"),
  workingPageId: __t.option(__t.u64()).name("working_page_id"),
  longTermPageId: __t.option(__t.u64()).name("long_term_page_id"),
  createdAt: __t.timestamp().name("created_at"),
  lastConsolidatedAt: __t.option(__t.timestamp()).name("last_consolidated_at"),
});
