// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  HttpMethod,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  endpointId: __t.u64().name("endpoint_id"),
  keyId: __t.option(__t.u64()).name("key_id"),
  get method() {
    return HttpMethod;
  },
  path: __t.string(),
  statusCode: __t.u16().name("status_code"),
  latencyMs: __t.u32().name("latency_ms"),
  callerIp: __t.option(__t.string()).name("caller_ip"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  at: __t.timestamp(),
});
