// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  HttpMethod,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  databasePageId: __t.u64().name("database_page_id"),
  slug: __t.string(),
  displayName: __t.string().name("display_name"),
  description: __t.string(),
  get allowedMethods() {
    return __t.array(HttpMethod).name("allowed_methods");
  },
  requireAuth: __t.bool().name("require_auth"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
