// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AutoApplyContext,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  aiUserId: __t.u64().name("ai_user_id"),
  get context() {
    return AutoApplyContext;
  },
  allowedActionKinds: __t.option(__t.array(__t.string())).name("allowed_action_kinds"),
  grantedBy: __t.identity().name("granted_by"),
  grantedAt: __t.timestamp().name("granted_at"),
});
