// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AutomationPrimitiveKind,
} from "./types";


export default __t.row({
  name: __t.string().primaryKey(),
  get primitiveKind() {
    return AutomationPrimitiveKind.name("primitive_kind");
  },
  title: __t.string(),
  description: __t.string(),
  configSchemaJson: __t.string().name("config_schema_json"),
});
