// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  queueId: __t.u64().name("queue_id"),
  actionId: __t.option(__t.u64()).name("action_id"),
  success: __t.bool(),
  dryRun: __t.bool().name("dry_run"),
  message: __t.string(),
  resultJson: __t.string().name("result_json"),
  createdAt: __t.timestamp().name("created_at"),
});
