// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AutomationCapabilityKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  automationId: __t.u64().name("automation_id"),
  get capabilityKind() {
    return AutomationCapabilityKind.name("capability_kind");
  },
  scopeConfig: __t.string().name("scope_config"),
});
