// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BridgeCommandStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  deviceId: __t.u64().name("device_id"),
  sessionId: __t.u64().name("session_id"),
  conversationId: __t.u64().name("conversation_id"),
  jobId: __t.option(__t.u64()).name("job_id"),
  taskId: __t.option(__t.u64()).name("task_id"),
  requestedBy: __t.identity().name("requested_by"),
  command: __t.string(),
  cwd: __t.option(__t.string()),
  enqueuedAt: __t.timestamp().name("enqueued_at"),
  get status() {
    return BridgeCommandStatus;
  },
  requiresConfirmation: __t.bool().name("requires_confirmation"),
  confirmedAt: __t.option(__t.timestamp()).name("confirmed_at"),
  confirmedBy: __t.option(__t.identity()).name("confirmed_by"),
  deviceIdentity: __t.identity().name("device_identity"),
  ownerIdentity: __t.identity().name("owner_identity"),
});
