// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActorType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  surfaceId: __t.u64().name("surface_id"),
  parentId: __t.option(__t.u64()).name("parent_id"),
  componentType: __t.string().name("component_type"),
  props: __t.string(),
  order: __t.u32(),
  get createdBy() {
    return ActorType.name("created_by");
  },
  get updatedBy() {
    return ActorType.name("updated_by");
  },
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
});
