// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  installedExtensionId: __t.u64(),
  confirmedCapabilities: __t.array(__t.string()),
  confirmedPermissionsJson: __t.string(),
  aiApiKey: __t.option(__t.string()),
  mcpApiKey: __t.option(__t.string()),
  endpointOverride: __t.option(__t.string()),
  aiUserIdentity: __t.option(__t.identity()),
};
