// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ConversationStatus,
  ConversationVisibility,
  ConversationKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  pageId: __t.option(__t.u64()).name("page_id"),
  initiatedBy: __t.identity().name("initiated_by"),
  get status() {
    return ConversationStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  get visibility() {
    return ConversationVisibility;
  },
  get kind() {
    return ConversationKind;
  },
  canonicalKey: __t.option(__t.string()).name("canonical_key"),
  blockAnchor: __t.option(__t.u64()).name("block_anchor"),
  modelOverride: __t.option(__t.string()).name("model_override"),
  effortOverride: __t.option(__t.string()).name("effort_override"),
});
