// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MessageSender,
  MessageStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  conversationId: __t.u64().name("conversation_id"),
  get sender() {
    return MessageSender;
  },
  content: __t.string(),
  jobId: __t.option(__t.u64()).name("job_id"),
  createdAt: __t.timestamp().name("created_at"),
  get status() {
    return MessageStatus;
  },
  thinking: __t.option(__t.string()),
  toolCallsJson: __t.option(__t.string()).name("tool_calls_json"),
  inputTokens: __t.u32().name("input_tokens"),
  outputTokens: __t.u32().name("output_tokens"),
  cacheCreationInputTokens: __t.u32().name("cache_creation_input_tokens"),
  cacheReadInputTokens: __t.u32().name("cache_read_input_tokens"),
  linkedConversationId: __t.option(__t.u64()).name("linked_conversation_id"),
  timelineJson: __t.option(__t.string()).name("timeline_json"),
  componentTreeJson: __t.option(__t.string()).name("component_tree_json"),
  mentions: __t.option(__t.array(__t.identity())),
});
