// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  PropertyValueInput,
} from "./types";

export default {
  databasePageId: __t.u64(),
  title: __t.string(),
  get values() {
    return __t.array(PropertyValueInput);
  },
  clientRequestId: __t.string(),
};
