// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  AutomationTriggerKind,
  AutomationScheduleKind,
} from "./types";

export default {
  name: __t.string(),
  get triggerKind() {
    return AutomationTriggerKind;
  },
  triggerConfig: __t.string(),
  get scheduleKind() {
    return AutomationScheduleKind;
  },
  scheduleConfig: __t.string(),
  timezone: __t.string(),
  canonicalDescription: __t.string(),
};
