// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  InferenceProvider,
  HarnessTemplateSource,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  externalId: __t.string().name("external_id"),
  name: __t.string(),
  description: __t.string(),
  get source() {
    return HarnessTemplateSource;
  },
  systemPrompt: __t.string().name("system_prompt"),
  get defaultProvider() {
    return InferenceProvider.name("default_provider");
  },
  defaultModel: __t.string().name("default_model"),
  defaultMaxTokens: __t.u32().name("default_max_tokens"),
  configJson: __t.string().name("config_json"),
  version: __t.u32(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
