// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conversationId: __t.u64().name("conversation_id"),
  requester: __t.identity(),
  recipient: __t.identity(),
  requestKey: __t.string().name("request_key"),
  question: __t.string(),
  answer: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  answeredAt: __t.option(__t.timestamp()).name("answered_at"),
});
