// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  InstallStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  manifestId: __t.u64().name("manifest_id"),
  installedBy: __t.identity().name("installed_by"),
  get installStatus() {
    return InstallStatus.name("install_status");
  },
  aiUserId: __t.option(__t.u64()).name("ai_user_id"),
  mcpServerId: __t.option(__t.u64()).name("mcp_server_id"),
  enabled: __t.bool(),
  installedAt: __t.timestamp().name("installed_at"),
  confirmedAt: __t.option(__t.timestamp()).name("confirmed_at"),
});
