// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  HttpMethod,
} from "./types";

export default {
  endpointId: __t.u64(),
  keyId: __t.option(__t.u64()),
  get method() {
    return HttpMethod;
  },
  path: __t.string(),
  statusCode: __t.u16(),
  latencyMs: __t.u32(),
  callerIp: __t.option(__t.string()),
  errorMessage: __t.option(__t.string()),
};
