// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PermissionScope,
  PermissionAction,
} from "./types";


export default __t.row({
  permissionId: __t.u64().name("permission_id"),
  installedExtensionId: __t.u64().name("installed_extension_id"),
  get scope() {
    return PermissionScope;
  },
  get action() {
    return PermissionAction;
  },
  allowedDomains: __t.option(__t.string()).name("allowed_domains"),
  grantedAt: __t.timestamp().name("granted_at"),
});
