// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NotionImportJobStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  requestedBy: __t.identity().name("requested_by"),
  encryptedTokenB64: __t.string().name("encrypted_token_b_64"),
  sourceName: __t.string().name("source_name"),
  workspaceSlug: __t.string().name("workspace_slug"),
  get status() {
    return NotionImportJobStatus;
  },
  stage: __t.string(),
  pagesDone: __t.u32().name("pages_done"),
  pagesTotal: __t.u32().name("pages_total"),
  error: __t.option(__t.string()),
  containerPageId: __t.option(__t.u64()).name("container_page_id"),
  claimedBy: __t.option(__t.string()).name("claimed_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
