// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  jobId: __t.u64().name("job_id"),
  description: __t.string(),
  taskType: __t.string().name("task_type"),
  status: __t.string(),
  dependsOn: __t.array(__t.u64()).name("depends_on"),
  requiredCapabilities: __t.array(__t.string()).name("required_capabilities"),
  assignedTo: __t.option(__t.string()).name("assigned_to"),
  result: __t.option(__t.string()),
});
