// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Principal,
  Permission,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  pageId: __t.u64().name("page_id"),
  get principal() {
    return Principal;
  },
  get permission() {
    return Permission;
  },
  grantedBy: __t.identity().name("granted_by"),
  grantedAt: __t.timestamp().name("granted_at"),
});
