// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActorType,
  PropertyValue,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  pageId: __t.u64().name("page_id"),
  propertyDefinitionId: __t.u64().name("property_definition_id"),
  get value() {
    return PropertyValue;
  },
  isCurrent: __t.bool().name("is_current"),
  changedAt: __t.timestamp().name("changed_at"),
  get changedBy() {
    return ActorType.name("changed_by");
  },
});
