// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  deviceName: __t.string(),
  deviceTokenHash: __t.string(),
  platform: __t.string(),
  bridgeVersion: __t.string(),
  deviceIdentity: __t.identity(),
  deviceStdbTokenCiphertext: __t.string(),
  allowedDirectories: __t.array(__t.string()),
};
