// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  taskId: __t.u64(),
  taskType: __t.string(),
  agentId: __t.string(),
  aiUserId: __t.option(__t.u64()),
  tokensIn: __t.u64(),
  tokensOut: __t.u64(),
  wallClockMs: __t.u64(),
};
