// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ComponentCapability,
} from "./types";

export default {
  componentType: __t.string(),
  displayName: __t.string(),
  description: __t.string(),
  propSchemaJson: __t.string(),
  get capabilities() {
    return __t.array(ComponentCapability);
  },
  hasYjsState: __t.bool(),
  acceptsChildren: __t.bool(),
};
