// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ReviewSubject,
  ReviewMode,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  reviewerAiUserId: __t.u64().name("reviewer_ai_user_id"),
  get subject() {
    return ReviewSubject;
  },
  get mode() {
    return ReviewMode;
  },
  failOpen: __t.bool().name("fail_open"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
});
