// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  MessageStatus,
} from "./types";

export default {
  conversationId: __t.u64(),
  content: __t.string(),
  jobId: __t.option(__t.u64()),
  get status() {
    return __t.option(MessageStatus);
  },
  thinking: __t.option(__t.string()),
  toolCallsJson: __t.option(__t.string()),
  inputTokens: __t.option(__t.u32()),
  outputTokens: __t.option(__t.u32()),
  cacheCreationInputTokens: __t.option(__t.u32()),
  cacheReadInputTokens: __t.option(__t.u32()),
  linkedConversationId: __t.option(__t.u64()),
};
