// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  deviceId: __t.u64(),
  allowedCommands: __t.array(__t.string()),
  blockedPatterns: __t.array(__t.string()),
  allowedDirectories: __t.array(__t.string()),
  requireConfirmationFor: __t.array(__t.string()),
  maxOutputBytes: __t.u64(),
  maxRuntimeSeconds: __t.u64(),
};
