// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ActorType`.
export const ActorType = __t.enum("ActorType", {
  Human: __t.unit(),
  Agent: __t.string(),
});
export type ActorType = __Infer<typeof ActorType>;

export const Attachment = __t.object("Attachment", {
  id: __t.u64(),
  pageId: __t.u64(),
  filename: __t.string(),
  contentType: __t.string(),
  storageKey: __t.string(),
  sizeBytes: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Attachment = __Infer<typeof Attachment>;

export const DatabaseSchema = __t.object("DatabaseSchema", {
  id: __t.u64(),
  pageId: __t.u64(),
  name: __t.string(),
});
export type DatabaseSchema = __Infer<typeof DatabaseSchema>;

export const DatabaseView = __t.object("DatabaseView", {
  id: __t.u64(),
  pageId: __t.u64(),
  name: __t.string(),
  get viewType() {
    return ViewType;
  },
  config: __t.string(),
  isDefault: __t.bool(),
  ownerIdentity: __t.option(__t.string()),
  get createdBy() {
    return ActorType;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DatabaseView = __Infer<typeof DatabaseView>;

export const Page = __t.object("Page", {
  id: __t.u64(),
  parentId: __t.option(__t.u64()),
  get pageType() {
    return PageType;
  },
  title: __t.string(),
  sortOrder: __t.u32(),
  embedding: __t.option(__t.array(__t.f32())),
  get createdBy() {
    return ActorType;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
  icon: __t.option(__t.string()),
});
export type Page = __Infer<typeof Page>;

export const PageContent = __t.object("PageContent", {
  pageId: __t.u64(),
  content: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PageContent = __Infer<typeof PageContent>;

export const PagePropertyValue = __t.object("PagePropertyValue", {
  id: __t.u64(),
  pageId: __t.u64(),
  propertyDefinitionId: __t.u64(),
  get value() {
    return PropertyValue;
  },
});
export type PagePropertyValue = __Infer<typeof PagePropertyValue>;

export const PagePropertyValueHistory = __t.object("PagePropertyValueHistory", {
  id: __t.u64(),
  pageId: __t.u64(),
  propertyDefinitionId: __t.u64(),
  get value() {
    return PropertyValue;
  },
  isCurrent: __t.bool(),
  changedAt: __t.timestamp(),
  get changedBy() {
    return ActorType;
  },
});
export type PagePropertyValueHistory = __Infer<typeof PagePropertyValueHistory>;

export const PageSnapshot = __t.object("PageSnapshot", {
  id: __t.u64(),
  pageId: __t.u64(),
  title: __t.string(),
  content: __t.string(),
  snapshotAt: __t.timestamp(),
  get createdBy() {
    return ActorType;
  },
  get snapshotType() {
    return SnapshotType;
  },
});
export type PageSnapshot = __Infer<typeof PageSnapshot>;

// The tagged union or sum type for the algebraic type `PageType`.
export const PageType = __t.enum("PageType", {
  Doc: __t.unit(),
  Database: __t.unit(),
});
export type PageType = __Infer<typeof PageType>;

export const PageYjsState = __t.object("PageYjsState", {
  pageId: __t.u64(),
  data: __t.byteArray(),
  updatedAt: __t.timestamp(),
});
export type PageYjsState = __Infer<typeof PageYjsState>;

export const PropertyDefinition = __t.object("PropertyDefinition", {
  id: __t.u64(),
  schemaId: __t.u64(),
  name: __t.string(),
  get propertyType() {
    return PropertyType;
  },
  config: __t.string(),
  order: __t.u32(),
});
export type PropertyDefinition = __Infer<typeof PropertyDefinition>;

// The tagged union or sum type for the algebraic type `PropertyType`.
export const PropertyType = __t.enum("PropertyType", {
  Text: __t.unit(),
  Number: __t.unit(),
  Date: __t.unit(),
  Select: __t.unit(),
  MultiSelect: __t.unit(),
  Relation: __t.unit(),
  Checkbox: __t.unit(),
  Url: __t.unit(),
});
export type PropertyType = __Infer<typeof PropertyType>;

// The tagged union or sum type for the algebraic type `PropertyValue`.
export const PropertyValue = __t.enum("PropertyValue", {
  Text: __t.string(),
  Number: __t.f64(),
  Date: __t.u64(),
  Select: __t.string(),
  MultiSelect: __t.array(__t.string()),
  Relation: __t.array(__t.u64()),
  Checkbox: __t.bool(),
  Url: __t.string(),
});
export type PropertyValue = __Infer<typeof PropertyValue>;

// The tagged union or sum type for the algebraic type `SnapshotType`.
export const SnapshotType = __t.enum("SnapshotType", {
  Manual: __t.unit(),
  Periodic: __t.unit(),
  PreAgentEdit: __t.unit(),
  PostAgentEdit: __t.unit(),
});
export type SnapshotType = __Infer<typeof SnapshotType>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  email: __t.string(),
  isAuthenticated: __t.bool(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserCredential = __t.object("UserCredential", {
  email: __t.string(),
  name: __t.string(),
  passwordHash: __t.string(),
  createdAt: __t.timestamp(),
});
export type UserCredential = __Infer<typeof UserCredential>;

// The tagged union or sum type for the algebraic type `ViewType`.
export const ViewType = __t.enum("ViewType", {
  Grid: __t.unit(),
  List: __t.unit(),
  Kanban: __t.unit(),
  Calendar: __t.unit(),
  Gallery: __t.unit(),
});
export type ViewType = __Infer<typeof ViewType>;

