// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  InferenceProvider,
} from "./types";

export default {
  aiUserId: __t.u64(),
  get provider() {
    return InferenceProvider;
  },
  model: __t.string(),
  endpoint: __t.option(__t.string()),
  systemPrompt: __t.option(__t.string()),
  maxTokens: __t.option(__t.u32()),
};
