// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AuthScheme,
  AiExtensionRuntimePermission,
} from "./types";


export default __t.row({
  installedExtensionId: __t.u64().name("installed_extension_id"),
  serverId: __t.u64().name("server_id"),
  name: __t.string(),
  endpoint: __t.string(),
  get authScheme() {
    return AuthScheme.name("auth_scheme");
  },
  apiKey: __t.option(__t.string()).name("api_key"),
  capabilities: __t.array(__t.string()),
  get permissions() {
    return __t.array(AiExtensionRuntimePermission);
  },
});
