// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  InferenceProvider,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  createdBy: __t.identity().name("created_by"),
  get provider() {
    return InferenceProvider;
  },
  model: __t.string(),
  endpoint: __t.option(__t.string()),
  apiKey: __t.option(__t.string()).name("api_key"),
  systemPrompt: __t.option(__t.string()).name("system_prompt"),
  maxTokens: __t.u32().name("max_tokens"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
