// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RoutineScheduleKind,
} from "./types";


export default __t.row({
  scheduledId: __t.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  aiUserId: __t.u64().name("ai_user_id"),
  prompt: __t.string(),
  enabled: __t.bool(),
  createdBy: __t.identity().name("created_by"),
  conversationId: __t.option(__t.u64()).name("conversation_id"),
  intervalSecs: __t.u64().name("interval_secs"),
  lastRunAt: __t.option(__t.timestamp()).name("last_run_at"),
  lastStatus: __t.option(__t.string()).name("last_status"),
  createdAt: __t.timestamp().name("created_at"),
  get scheduleKind() {
    return RoutineScheduleKind.name("schedule_kind");
  },
  cronExpression: __t.option(__t.string()).name("cron_expression"),
  timezone: __t.option(__t.string()),
});
