// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  HttpMethod,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  endpointId: __t.u64().name("endpoint_id"),
  keyHash: __t.string().name("key_hash"),
  label: __t.string(),
  get allowedMethods() {
    return __t.array(HttpMethod).name("allowed_methods");
  },
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  lastUsedAt: __t.option(__t.timestamp()).name("last_used_at"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
});
