// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  endpointId: __t.u64().name("endpoint_id"),
  propertyDefinitionId: __t.u64().name("property_definition_id"),
  fieldName: __t.string().name("field_name"),
  requiredOnCreate: __t.bool().name("required_on_create"),
  defaultValue: __t.option(__t.string()).name("default_value"),
  readOnly: __t.bool().name("read_only"),
  fieldOrder: __t.u32().name("field_order"),
});
