// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  pageId: __t.u64().name("page_id"),
  filename: __t.string(),
  contentType: __t.string().name("content_type"),
  storageKey: __t.string().name("storage_key"),
  sizeBytes: __t.u64().name("size_bytes"),
  createdAt: __t.timestamp().name("created_at"),
});
