// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AutomationTriggerKind,
  AutomationMode,
  AutomationScheduleKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  enabled: __t.bool(),
  get mode() {
    return AutomationMode;
  },
  get triggerKind() {
    return AutomationTriggerKind.name("trigger_kind");
  },
  triggerConfig: __t.string().name("trigger_config"),
  get scheduleKind() {
    return AutomationScheduleKind.name("schedule_kind");
  },
  scheduleConfig: __t.string().name("schedule_config"),
  timezone: __t.string(),
  nextRunAt: __t.option(__t.timestamp()).name("next_run_at"),
  lastRunAt: __t.option(__t.timestamp()).name("last_run_at"),
  maxTicks: __t.option(__t.u64()).name("max_ticks"),
  tickCount: __t.u64().name("tick_count"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
  runAs: __t.identity().name("run_as"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  canonicalDescription: __t.string().name("canonical_description"),
});
