// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AutomationTriggerKind,
  AutomationEventStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  automationId: __t.u64().name("automation_id"),
  get triggerKind() {
    return AutomationTriggerKind.name("trigger_kind");
  },
  triggerPayload: __t.string().name("trigger_payload"),
  get status() {
    return AutomationEventStatus;
  },
  attempts: __t.u32(),
  claimedBy: __t.option(__t.string()).name("claimed_by"),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
