// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AutomationActionKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  automationId: __t.u64().name("automation_id"),
  order: __t.u32(),
  get actionKind() {
    return AutomationActionKind.name("action_kind");
  },
  config: __t.string(),
});
