// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  deviceId: __t.u64().primaryKey().name("device_id"),
  allowedCommands: __t.array(__t.string()).name("allowed_commands"),
  blockedPatterns: __t.array(__t.string()).name("blocked_patterns"),
  allowedDirectories: __t.array(__t.string()).name("allowed_directories"),
  requireConfirmationFor: __t.array(__t.string()).name("require_confirmation_for"),
  maxOutputBytes: __t.u64().name("max_output_bytes"),
  maxRuntimeSeconds: __t.u64().name("max_runtime_seconds"),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedBy: __t.identity().name("updated_by"),
});
