// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BridgeApprovalStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  commandId: __t.u64().name("command_id"),
  requestId: __t.string().name("request_id"),
  deviceId: __t.u64().name("device_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  requestedBy: __t.identity().name("requested_by"),
  conversationId: __t.u64().name("conversation_id"),
  title: __t.option(__t.string()),
  kind: __t.option(__t.string()),
  toolCallId: __t.option(__t.string()).name("tool_call_id"),
  optionsJson: __t.string().name("options_json"),
  diffsJson: __t.option(__t.string()).name("diffs_json"),
  get status() {
    return BridgeApprovalStatus;
  },
  decidedOptionId: __t.option(__t.string()).name("decided_option_id"),
  decidedBy: __t.option(__t.identity()).name("decided_by"),
  decidedAt: __t.option(__t.timestamp()).name("decided_at"),
  createdAt: __t.timestamp().name("created_at"),
});
