// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ComponentCapability,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  componentType: __t.string().name("component_type"),
  displayName: __t.string().name("display_name"),
  description: __t.string(),
  propSchema: __t.string().name("prop_schema"),
  get capabilities() {
    return __t.array(ComponentCapability);
  },
  hasYjsState: __t.bool().name("has_yjs_state"),
  acceptsChildren: __t.bool().name("accepts_children"),
  isBuiltin: __t.bool().name("is_builtin"),
  registeredBy: __t.identity().name("registered_by"),
  createdAt: __t.timestamp().name("created_at"),
});
