// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AttachmentKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  messageId: __t.u64().name("message_id"),
  conversationId: __t.u64().name("conversation_id"),
  get kind() {
    return AttachmentKind;
  },
  objectKey: __t.option(__t.string()).name("object_key"),
  mimeType: __t.option(__t.string()).name("mime_type"),
  fileName: __t.option(__t.string()).name("file_name"),
  pageId: __t.option(__t.u64()).name("page_id"),
  contentSnapshot: __t.option(__t.string()).name("content_snapshot"),
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.identity().name("created_by"),
});
