// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ExtensionType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  get extensionType() {
    return ExtensionType.name("extension_type");
  },
  version: __t.string(),
  authorIdentity: __t.option(__t.identity()).name("author_identity"),
  manifestJson: __t.string().name("manifest_json"),
  sourceUrl: __t.option(__t.string()).name("source_url"),
  createdAt: __t.timestamp().name("created_at"),
});
