// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ExtensionRuntimeStatus,
} from "./types";


export default __t.row({
  installedExtensionId: __t.u64().primaryKey().name("installed_extension_id"),
  get status() {
    return ExtensionRuntimeStatus;
  },
  toolCount: __t.u32().name("tool_count"),
  detail: __t.option(__t.string()),
  checkedAt: __t.timestamp().name("checked_at"),
  reportedBy: __t.identity().name("reported_by"),
});
