// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 5836c268a7307f864b33636357b0869ecc40bc0a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddAutomationActionReducer from "./add_automation_action_reducer";
import AddAutomationCapabilityReducer from "./add_automation_capability_reducer";
import AddAutomationConditionReducer from "./add_automation_condition_reducer";
import AddConversationParticipantReducer from "./add_conversation_participant_reducer";
import AddPropertyReducer from "./add_property_reducer";
import AddTasksToJobReducer from "./add_tasks_to_job_reducer";
import CancelExtensionInstallReducer from "./cancel_extension_install_reducer";
import ClaimTaskReducer from "./claim_task_reducer";
import ClearBlockAccessRuleReducer from "./clear_block_access_rule_reducer";
import ClearPageAccessRuleReducer from "./clear_page_access_rule_reducer";
import ClearPropertyValueReducer from "./clear_property_value_reducer";
import CloseConversationReducer from "./close_conversation_reducer";
import ConfirmExtensionInstallReducer from "./confirm_extension_install_reducer";
import CreateAiUserReducer from "./create_ai_user_reducer";
import CreateApiEndpointReducer from "./create_api_endpoint_reducer";
import CreateApiEndpointKeyReducer from "./create_api_endpoint_key_reducer";
import CreateApiFieldMappingReducer from "./create_api_field_mapping_reducer";
import CreateAttachmentReducer from "./create_attachment_reducer";
import CreateAutomationDraftReducer from "./create_automation_draft_reducer";
import CreateConversationReducer from "./create_conversation_reducer";
import CreateDatabaseRowReducer from "./create_database_row_reducer";
import CreateDatabaseSchemaReducer from "./create_database_schema_reducer";
import CreateJobReducer from "./create_job_reducer";
import CreateLocalUserReducer from "./create_local_user_reducer";
import CreatePageReducer from "./create_page_reducer";
import CreateReviewAgentBindingReducer from "./create_review_agent_binding_reducer";
import CreateViewReducer from "./create_view_reducer";
import DeleteAiUserReducer from "./delete_ai_user_reducer";
import DeleteApiEndpointReducer from "./delete_api_endpoint_reducer";
import DeleteApiFieldMappingReducer from "./delete_api_field_mapping_reducer";
import DeleteAttachmentReducer from "./delete_attachment_reducer";
import DeleteAutomationReducer from "./delete_automation_reducer";
import DeleteAutomationActionReducer from "./delete_automation_action_reducer";
import DeleteComponentReducer from "./delete_component_reducer";
import DeleteDatabaseRowReducer from "./delete_database_row_reducer";
import DeleteHarnessTemplateReducer from "./delete_harness_template_reducer";
import DeletePageReducer from "./delete_page_reducer";
import DeletePropertyReducer from "./delete_property_reducer";
import DeleteReviewAgentBindingReducer from "./delete_review_agent_binding_reducer";
import DeleteViewReducer from "./delete_view_reducer";
import DisableAiUserMemoryReducer from "./disable_ai_user_memory_reducer";
import DisableAutomationReducer from "./disable_automation_reducer";
import EnableAutomationReducer from "./enable_automation_reducer";
import FailTaskReducer from "./fail_task_reducer";
import FindOrCreateAiDmReducer from "./find_or_create_ai_dm_reducer";
import FindOrCreateDmReducer from "./find_or_create_dm_reducer";
import GrantAutoApplyReducer from "./grant_auto_apply_reducer";
import GrantExtensionPermissionReducer from "./grant_extension_permission_reducer";
import ImportNotionReducer from "./import_notion_reducer";
import ImportPearSnapshotV1Reducer from "./import_pear_snapshot_v_1_reducer";
import InsertComponentReducer from "./insert_component_reducer";
import InstallExtensionReducer from "./install_extension_reducer";
import InvalidateAiEvaluationsForRowReducer from "./invalidate_ai_evaluations_for_row_reducer";
import LogApiCallReducer from "./log_api_call_reducer";
import LoginReducer from "./login_reducer";
import LogoutReducer from "./logout_reducer";
import MarkConversationReadReducer from "./mark_conversation_read_reducer";
import MoveComponentReducer from "./move_component_reducer";
import MovePageReducer from "./move_page_reducer";
import ProcessAutomationEventReducer from "./process_automation_event_reducer";
import ProcessPendingAutomationEventsReducer from "./process_pending_automation_events_reducer";
import PromoteToInstructionReducer from "./promote_to_instruction_reducer";
import ProvisionAiUserMemoryReducer from "./provision_ai_user_memory_reducer";
import PublishExtensionReducer from "./publish_extension_reducer";
import PurgePageReducer from "./purge_page_reducer";
import RecordAiEvaluationReducer from "./record_ai_evaluation_reducer";
import RecordCompactionReducer from "./record_compaction_reducer";
import RecordReviewAnnotationReducer from "./record_review_annotation_reducer";
import RecordToolCallAuditReducer from "./record_tool_call_audit_reducer";
import RecordUsageEventReducer from "./record_usage_event_reducer";
import RegisterReducer from "./register_reducer";
import RegisterAgentReducer from "./register_agent_reducer";
import RemoveConversationParticipantReducer from "./remove_conversation_participant_reducer";
import RenamePropertyReducer from "./rename_property_reducer";
import RenameViewReducer from "./rename_view_reducer";
import ReorderPropertyReducer from "./reorder_property_reducer";
import RequestPageAccessReducer from "./request_page_access_reducer";
import ResolvePageAccessRequestReducer from "./resolve_page_access_request_reducer";
import ResolveStructuralFindingReducer from "./resolve_structural_finding_reducer";
import RestoreComponentReducer from "./restore_component_reducer";
import RestorePageReducer from "./restore_page_reducer";
import RestorePageToSnapshotReducer from "./restore_page_to_snapshot_reducer";
import RevokeApiEndpointKeyReducer from "./revoke_api_endpoint_key_reducer";
import RevokeAutoApplyReducer from "./revoke_auto_apply_reducer";
import RevokeExtensionPermissionReducer from "./revoke_extension_permission_reducer";
import RunConventionSensorReducer from "./run_convention_sensor_reducer";
import RunDeniedToolCallsSensorReducer from "./run_denied_tool_calls_sensor_reducer";
import RunOrphanDetectorReducer from "./run_orphan_detector_reducer";
import RunPendingMigrationsReducer from "./run_pending_migrations_reducer";
import RunRelationalIntegritySensorReducer from "./run_relational_integrity_sensor_reducer";
import RunSchemaConsistencySensorReducer from "./run_schema_consistency_sensor_reducer";
import SaveComponentYjsStateReducer from "./save_component_yjs_state_reducer";
import SaveYjsStateReducer from "./save_yjs_state_reducer";
import SeedAgentInstructionPropertyReducer from "./seed_agent_instruction_property_reducer";
import SeedBuiltinExtensionsReducer from "./seed_builtin_extensions_reducer";
import SeedSensorRegistryReducer from "./seed_sensor_registry_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetAiUserApiKeyReducer from "./set_ai_user_api_key_reducer";
import SetAiUserSerperApiKeyReducer from "./set_ai_user_serper_api_key_reducer";
import SetAiUserToolSecretsJsonReducer from "./set_ai_user_tool_secrets_json_reducer";
import SetAllowEvaluationSharingReducer from "./set_allow_evaluation_sharing_reducer";
import SetAutomationLimitsReducer from "./set_automation_limits_reducer";
import SetAutomationModeReducer from "./set_automation_mode_reducer";
import SetBlockAccessRuleReducer from "./set_block_access_rule_reducer";
import SetConversationVisibilityReducer from "./set_conversation_visibility_reducer";
import SetDefaultViewReducer from "./set_default_view_reducer";
import SetExtensionEnabledReducer from "./set_extension_enabled_reducer";
import SetMcpServerApiKeyReducer from "./set_mcp_server_api_key_reducer";
import SetPageAccessRuleReducer from "./set_page_access_rule_reducer";
import SetPageEmbeddingReducer from "./set_page_embedding_reducer";
import SetPageHiddenReducer from "./set_page_hidden_reducer";
import SetPropertyValueReducer from "./set_property_value_reducer";
import SetSharedContextReducer from "./set_shared_context_reducer";
import SetUserAdminReducer from "./set_user_admin_reducer";
import SetUserPreferenceReducer from "./set_user_preference_reducer";
import SetUserProfileReducer from "./set_user_profile_reducer";
import SubmitResultReducer from "./submit_result_reducer";
import TakeSnapshotReducer from "./take_snapshot_reducer";
import TakeSnapshotWithContentReducer from "./take_snapshot_with_content_reducer";
import TouchApiEndpointKeyReducer from "./touch_api_endpoint_key_reducer";
import UninstallExtensionReducer from "./uninstall_extension_reducer";
import UpdateAiUserConfigReducer from "./update_ai_user_config_reducer";
import UpdateAiUserProfileReducer from "./update_ai_user_profile_reducer";
import UpdateAiUserSystemPromptReducer from "./update_ai_user_system_prompt_reducer";
import UpdateApiEndpointReducer from "./update_api_endpoint_reducer";
import UpdateApiFieldMappingReducer from "./update_api_field_mapping_reducer";
import UpdateAutomationActionReducer from "./update_automation_action_reducer";
import UpdateAutomationRuleReducer from "./update_automation_rule_reducer";
import UpdateComponentPropsReducer from "./update_component_props_reducer";
import UpdateDatabaseRowReducer from "./update_database_row_reducer";
import UpdateDatabaseSchemaConfigReducer from "./update_database_schema_config_reducer";
import UpdateExtensionReducer from "./update_extension_reducer";
import UpdateMessageReducer from "./update_message_reducer";
import UpdatePageContentReducer from "./update_page_content_reducer";
import UpdatePageIconReducer from "./update_page_icon_reducer";
import UpdatePageTitleReducer from "./update_page_title_reducer";
import UpdatePropertyConfigReducer from "./update_property_config_reducer";
import UpdatePropertyTypeReducer from "./update_property_type_reducer";
import UpdateViewConfigReducer from "./update_view_config_reducer";
import UpsertHarnessTemplateReducer from "./upsert_harness_template_reducer";
import ValidateAutomationReducer from "./validate_automation_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AiEvaluationRow from "./ai_evaluation_table";
import AiUserConfigRow from "./ai_user_config_table";
import AiUserMemoryRow from "./ai_user_memory_table";
import AiUserProfileRow from "./ai_user_profile_table";
import ApiCallLogRow from "./api_call_log_table";
import ApiEndpointRow from "./api_endpoint_table";
import ApiEndpointKeyRow from "./api_endpoint_key_table";
import ApiEndpointKeyLookupRow from "./api_endpoint_key_lookup_table";
import ApiFieldMappingRow from "./api_field_mapping_table";
import AttachmentRow from "./attachment_table";
import AutoApplyBindingRow from "./auto_apply_binding_table";
import AutomationActionRow from "./automation_action_table";
import AutomationCapabilityRow from "./automation_capability_table";
import AutomationConditionRow from "./automation_condition_table";
import AutomationEventQueueRow from "./automation_event_queue_table";
import AutomationPrimitiveRow from "./automation_primitive_table";
import AutomationRuleRow from "./automation_rule_table";
import AutomationRunLogRow from "./automation_run_log_table";
import BlockAccessRuleRow from "./block_access_rule_table";
import ComponentNodeRow from "./component_node_table";
import ComponentTypeDefinitionRow from "./component_type_definition_table";
import ComponentYjsStateRow from "./component_yjs_state_table";
import ConversationRow from "./conversation_table";
import ConversationMessageRow from "./conversation_message_table";
import ConversationParticipantRow from "./conversation_participant_table";
import DatabaseRowMarkerRow from "./database_row_marker_table";
import DatabaseSchemaRow from "./database_schema_table";
import DatabaseViewRow from "./database_view_table";
import ExtensionManifestRow from "./extension_manifest_table";
import HarnessTemplateRow from "./harness_template_table";
import IdCounterRow from "./id_counter_table";
import InstalledExtensionRow from "./installed_extension_table";
import MigrationStateRow from "./migration_state_table";
import ModuleInstallMetaRow from "./module_install_meta_table";
import OrchaAgentRow from "./orcha_agent_table";
import OrchaJobRow from "./orcha_job_table";
import OrchaSharedContextRow from "./orcha_shared_context_table";
import OrchaTaskRow from "./orcha_task_table";
import OrchaUsageEventRow from "./orcha_usage_event_table";
import PageRow from "./page_table";
import PageAccessRequestRow from "./page_access_request_table";
import PageAccessRuleRow from "./page_access_rule_table";
import PageContentRow from "./page_content_table";
import PagePropertyValueRow from "./page_property_value_table";
import PagePropertyValueHistoryRow from "./page_property_value_history_table";
import PageSnapshotRow from "./page_snapshot_table";
import PageYjsStateRow from "./page_yjs_state_table";
import PropertyDefinitionRow from "./property_definition_table";
import ReviewAgentBindingRow from "./review_agent_binding_table";
import ReviewAnnotationRow from "./review_annotation_table";
import SensorRegistryRow from "./sensor_registry_table";
import StructuralSensorFindingRow from "./structural_sensor_finding_table";
import UserRow from "./user_table";
import UserPreferenceRow from "./user_preference_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  ai_evaluation: __table({
    name: 'ai_evaluation',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'ai_evaluation_input_hash', algorithm: 'btree', columns: [
        'inputHash',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { name: 'property_definition_id', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
      { name: 'ai_evaluation_property_page', algorithm: 'btree', columns: [
        'propertyDefinitionId',
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'ai_evaluation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AiEvaluationRow),
  ai_user_config: __table({
    name: 'ai_user_config',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'ai_user_config_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'ai_user_config_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AiUserConfigRow),
  ai_user_memory: __table({
    name: 'ai_user_memory',
    indexes: [
      { name: 'ai_user_id', algorithm: 'btree', columns: [
        'aiUserId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ai_user_memory_ai_user_id_key', constraint: 'unique', columns: ['aiUserId'] },
      { name: 'ai_user_memory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AiUserMemoryRow),
  ai_user_profile: __table({
    name: 'ai_user_profile',
    indexes: [
      { name: 'ai_user_id', algorithm: 'btree', columns: [
        'aiUserId',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'ai_user_profile_ai_user_id_key', constraint: 'unique', columns: ['aiUserId'] },
      { name: 'ai_user_profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AiUserProfileRow),
  api_call_log: __table({
    name: 'api_call_log',
    indexes: [
      { name: 'at', algorithm: 'btree', columns: [
        'at',
      ] },
      { name: 'endpoint_id', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_call_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiCallLogRow),
  api_endpoint: __table({
    name: 'api_endpoint',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'slug', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'api_endpoint_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'api_endpoint_slug_key', constraint: 'unique', columns: ['slug'] },
    ],
  }, ApiEndpointRow),
  api_endpoint_key: __table({
    name: 'api_endpoint_key',
    indexes: [
      { name: 'endpoint_id', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_endpoint_key_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiEndpointKeyRow),
  api_field_mapping: __table({
    name: 'api_field_mapping',
    indexes: [
      { name: 'endpoint_id', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_field_mapping_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiFieldMappingRow),
  attachment: __table({
    name: 'attachment',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'attachment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AttachmentRow),
  auto_apply_binding: __table({
    name: 'auto_apply_binding',
    indexes: [
      { name: 'auto_apply_binding_principal', algorithm: 'btree', columns: [
        'aiUserId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'auto_apply_binding_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AutoApplyBindingRow),
  automation_action: __table({
    name: 'automation_action',
    indexes: [
      { name: 'by_rule', algorithm: 'btree', columns: [
        'automationId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'automation_action_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AutomationActionRow),
  automation_capability: __table({
    name: 'automation_capability',
    indexes: [
      { name: 'by_rule', algorithm: 'btree', columns: [
        'automationId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'automation_capability_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AutomationCapabilityRow),
  automation_condition: __table({
    name: 'automation_condition',
    indexes: [
      { name: 'by_rule', algorithm: 'btree', columns: [
        'automationId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'automation_condition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AutomationConditionRow),
  automation_event_queue: __table({
    name: 'automation_event_queue',
    indexes: [
      { name: 'by_rule', algorithm: 'btree', columns: [
        'automationId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'automation_event_queue_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AutomationEventQueueRow),
  automation_primitive: __table({
    name: 'automation_primitive',
    indexes: [
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'automation_primitive_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, AutomationPrimitiveRow),
  automation_rule: __table({
    name: 'automation_rule',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'automation_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AutomationRuleRow),
  automation_run_log: __table({
    name: 'automation_run_log',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_queue', algorithm: 'btree', columns: [
        'queueId',
      ] },
    ],
    constraints: [
      { name: 'automation_run_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AutomationRunLogRow),
  block_access_rule: __table({
    name: 'block_access_rule',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'block_access_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BlockAccessRuleRow),
  component_node: __table({
    name: 'component_node',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'parent_id', algorithm: 'btree', columns: [
        'parentId',
      ] },
      { name: 'surface_id', algorithm: 'btree', columns: [
        'surfaceId',
      ] },
      { name: 'component_node_by_surface_parent', algorithm: 'btree', columns: [
        'surfaceId',
        'parentId',
      ] },
    ],
    constraints: [
      { name: 'component_node_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentNodeRow),
  component_type_definition: __table({
    name: 'component_type_definition',
    indexes: [
      { name: 'component_type', algorithm: 'btree', columns: [
        'componentType',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'component_type_definition_component_type_key', constraint: 'unique', columns: ['componentType'] },
      { name: 'component_type_definition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentTypeDefinitionRow),
  component_yjs_state: __table({
    name: 'component_yjs_state',
    indexes: [
      { name: 'component_node_id', algorithm: 'btree', columns: [
        'componentNodeId',
      ] },
    ],
    constraints: [
      { name: 'component_yjs_state_component_node_id_key', constraint: 'unique', columns: ['componentNodeId'] },
    ],
  }, ComponentYjsStateRow),
  conversation: __table({
    name: 'conversation',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'conversation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConversationRow),
  conversation_message: __table({
    name: 'conversation_message',
    indexes: [
      { name: 'conversation_id', algorithm: 'btree', columns: [
        'conversationId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'conversation_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConversationMessageRow),
  conversation_participant: __table({
    name: 'conversation_participant',
    indexes: [
      { name: 'conversation_id', algorithm: 'btree', columns: [
        'conversationId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'conversation_participant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConversationParticipantRow),
  database_row_marker: __table({
    name: 'database_row_marker',
    indexes: [
      { name: 'client_request_id', algorithm: 'btree', columns: [
        'clientRequestId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'database_row_marker_client_request_id_key', constraint: 'unique', columns: ['clientRequestId'] },
      { name: 'database_row_marker_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseRowMarkerRow),
  database_schema: __table({
    name: 'database_schema',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_schema_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseSchemaRow),
  database_view: __table({
    name: 'database_view',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_view_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseViewRow),
  extension_manifest: __table({
    name: 'extension_manifest',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'extension_manifest_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExtensionManifestRow),
  harness_template: __table({
    name: 'harness_template',
    indexes: [
      { name: 'harness_template_external_id', algorithm: 'btree', columns: [
        'externalId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'harness_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HarnessTemplateRow),
  id_counter: __table({
    name: 'id_counter',
    indexes: [
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'id_counter_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, IdCounterRow),
  installed_extension: __table({
    name: 'installed_extension',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'manifest_id', algorithm: 'btree', columns: [
        'manifestId',
      ] },
    ],
    constraints: [
      { name: 'installed_extension_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InstalledExtensionRow),
  migration_state: __table({
    name: 'migration_state',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'migration_state_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, MigrationStateRow),
  module_install_meta: __table({
    name: 'module_install_meta',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'module_install_meta_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ModuleInstallMetaRow),
  orcha_agent: __table({
    name: 'orcha_agent',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'orcha_agent_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrchaAgentRow),
  orcha_job: __table({
    name: 'orcha_job',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'orcha_job_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrchaJobRow),
  orcha_shared_context: __table({
    name: 'orcha_shared_context',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'job_id', algorithm: 'btree', columns: [
        'jobId',
      ] },
    ],
    constraints: [
      { name: 'orcha_shared_context_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrchaSharedContextRow),
  orcha_task: __table({
    name: 'orcha_task',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'job_id', algorithm: 'btree', columns: [
        'jobId',
      ] },
    ],
    constraints: [
      { name: 'orcha_task_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrchaTaskRow),
  orcha_usage_event: __table({
    name: 'orcha_usage_event',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'orcha_usage_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrchaUsageEventRow),
  page: __table({
    name: 'page',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'parent_id', algorithm: 'btree', columns: [
        'parentId',
      ] },
      { name: 'parent_pk', algorithm: 'btree', columns: [
        'parentPk',
      ] },
    ],
    constraints: [
      { name: 'page_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageRow),
  page_access_request: __table({
    name: 'page_access_request',
    indexes: [
      { name: 'conversation_id', algorithm: 'btree', columns: [
        'conversationId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_access_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageAccessRequestRow),
  page_access_rule: __table({
    name: 'page_access_rule',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_access_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageAccessRuleRow),
  page_content: __table({
    name: 'page_content',
    indexes: [
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_content_page_id_key', constraint: 'unique', columns: ['pageId'] },
    ],
  }, PageContentRow),
  page_property_value: __table({
    name: 'page_property_value',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { name: 'property_definition_id', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
    ],
    constraints: [
      { name: 'page_property_value_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagePropertyValueRow),
  page_property_value_history: __table({
    name: 'page_property_value_history',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { name: 'property_definition_id', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
    ],
    constraints: [
      { name: 'page_property_value_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagePropertyValueHistoryRow),
  page_snapshot: __table({
    name: 'page_snapshot',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_snapshot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageSnapshotRow),
  page_yjs_state: __table({
    name: 'page_yjs_state',
    indexes: [
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_yjs_state_page_id_key', constraint: 'unique', columns: ['pageId'] },
    ],
  }, PageYjsStateRow),
  property_definition: __table({
    name: 'property_definition',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'schema_id', algorithm: 'btree', columns: [
        'schemaId',
      ] },
    ],
    constraints: [
      { name: 'property_definition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PropertyDefinitionRow),
  review_agent_binding: __table({
    name: 'review_agent_binding',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'reviewer_ai_user_id', algorithm: 'btree', columns: [
        'reviewerAiUserId',
      ] },
    ],
    constraints: [
      { name: 'review_agent_binding_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReviewAgentBindingRow),
  review_annotation: __table({
    name: 'review_annotation',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'snapshot_id', algorithm: 'btree', columns: [
        'snapshotId',
      ] },
    ],
    constraints: [
      { name: 'review_annotation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReviewAnnotationRow),
  sensor_registry: __table({
    name: 'sensor_registry',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'sensor_registry_kind_code', algorithm: 'btree', columns: [
        'sensorKind',
        'code',
      ] },
    ],
    constraints: [
      { name: 'sensor_registry_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SensorRegistryRow),
  structural_sensor_finding: __table({
    name: 'structural_sensor_finding',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'structural_sensor_finding_kind', algorithm: 'btree', columns: [
        'sensorKind',
      ] },
      { name: 'structural_sensor_finding_target', algorithm: 'btree', columns: [
        'targetKind',
        'targetId',
      ] },
    ],
    constraints: [
      { name: 'structural_sensor_finding_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StructuralSensorFindingRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  user_preference: __table({
    name: 'user_preference',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'user_preference_identity_key', algorithm: 'btree', columns: [
        'identity',
        'key',
      ] },
    ],
    constraints: [
      { name: 'user_preference_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserPreferenceRow),
  api_endpoint_key_lookup: __table({
    name: 'api_endpoint_key_lookup',
    indexes: [
    ],
    constraints: [
    ],
  }, ApiEndpointKeyLookupRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_automation_action", AddAutomationActionReducer),
  __reducerSchema("add_automation_capability", AddAutomationCapabilityReducer),
  __reducerSchema("add_automation_condition", AddAutomationConditionReducer),
  __reducerSchema("add_conversation_participant", AddConversationParticipantReducer),
  __reducerSchema("add_property", AddPropertyReducer),
  __reducerSchema("add_tasks_to_job", AddTasksToJobReducer),
  __reducerSchema("cancel_extension_install", CancelExtensionInstallReducer),
  __reducerSchema("claim_task", ClaimTaskReducer),
  __reducerSchema("clear_block_access_rule", ClearBlockAccessRuleReducer),
  __reducerSchema("clear_page_access_rule", ClearPageAccessRuleReducer),
  __reducerSchema("clear_property_value", ClearPropertyValueReducer),
  __reducerSchema("close_conversation", CloseConversationReducer),
  __reducerSchema("confirm_extension_install", ConfirmExtensionInstallReducer),
  __reducerSchema("create_ai_user", CreateAiUserReducer),
  __reducerSchema("create_api_endpoint", CreateApiEndpointReducer),
  __reducerSchema("create_api_endpoint_key", CreateApiEndpointKeyReducer),
  __reducerSchema("create_api_field_mapping", CreateApiFieldMappingReducer),
  __reducerSchema("create_attachment", CreateAttachmentReducer),
  __reducerSchema("create_automation_draft", CreateAutomationDraftReducer),
  __reducerSchema("create_conversation", CreateConversationReducer),
  __reducerSchema("create_database_row", CreateDatabaseRowReducer),
  __reducerSchema("create_database_schema", CreateDatabaseSchemaReducer),
  __reducerSchema("create_job", CreateJobReducer),
  __reducerSchema("create_local_user", CreateLocalUserReducer),
  __reducerSchema("create_page", CreatePageReducer),
  __reducerSchema("create_review_agent_binding", CreateReviewAgentBindingReducer),
  __reducerSchema("create_view", CreateViewReducer),
  __reducerSchema("delete_ai_user", DeleteAiUserReducer),
  __reducerSchema("delete_api_endpoint", DeleteApiEndpointReducer),
  __reducerSchema("delete_api_field_mapping", DeleteApiFieldMappingReducer),
  __reducerSchema("delete_attachment", DeleteAttachmentReducer),
  __reducerSchema("delete_automation", DeleteAutomationReducer),
  __reducerSchema("delete_automation_action", DeleteAutomationActionReducer),
  __reducerSchema("delete_component", DeleteComponentReducer),
  __reducerSchema("delete_database_row", DeleteDatabaseRowReducer),
  __reducerSchema("delete_harness_template", DeleteHarnessTemplateReducer),
  __reducerSchema("delete_page", DeletePageReducer),
  __reducerSchema("delete_property", DeletePropertyReducer),
  __reducerSchema("delete_review_agent_binding", DeleteReviewAgentBindingReducer),
  __reducerSchema("delete_view", DeleteViewReducer),
  __reducerSchema("disable_ai_user_memory", DisableAiUserMemoryReducer),
  __reducerSchema("disable_automation", DisableAutomationReducer),
  __reducerSchema("enable_automation", EnableAutomationReducer),
  __reducerSchema("fail_task", FailTaskReducer),
  __reducerSchema("find_or_create_ai_dm", FindOrCreateAiDmReducer),
  __reducerSchema("find_or_create_dm", FindOrCreateDmReducer),
  __reducerSchema("grant_auto_apply", GrantAutoApplyReducer),
  __reducerSchema("grant_extension_permission", GrantExtensionPermissionReducer),
  __reducerSchema("import_notion", ImportNotionReducer),
  __reducerSchema("import_pear_snapshot_v_1", ImportPearSnapshotV1Reducer),
  __reducerSchema("insert_component", InsertComponentReducer),
  __reducerSchema("install_extension", InstallExtensionReducer),
  __reducerSchema("invalidate_ai_evaluations_for_row", InvalidateAiEvaluationsForRowReducer),
  __reducerSchema("log_api_call", LogApiCallReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("mark_conversation_read", MarkConversationReadReducer),
  __reducerSchema("move_component", MoveComponentReducer),
  __reducerSchema("move_page", MovePageReducer),
  __reducerSchema("process_automation_event", ProcessAutomationEventReducer),
  __reducerSchema("process_pending_automation_events", ProcessPendingAutomationEventsReducer),
  __reducerSchema("promote_to_instruction", PromoteToInstructionReducer),
  __reducerSchema("provision_ai_user_memory", ProvisionAiUserMemoryReducer),
  __reducerSchema("publish_extension", PublishExtensionReducer),
  __reducerSchema("purge_page", PurgePageReducer),
  __reducerSchema("record_ai_evaluation", RecordAiEvaluationReducer),
  __reducerSchema("record_compaction", RecordCompactionReducer),
  __reducerSchema("record_review_annotation", RecordReviewAnnotationReducer),
  __reducerSchema("record_tool_call_audit", RecordToolCallAuditReducer),
  __reducerSchema("record_usage_event", RecordUsageEventReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("register_agent", RegisterAgentReducer),
  __reducerSchema("remove_conversation_participant", RemoveConversationParticipantReducer),
  __reducerSchema("rename_property", RenamePropertyReducer),
  __reducerSchema("rename_view", RenameViewReducer),
  __reducerSchema("reorder_property", ReorderPropertyReducer),
  __reducerSchema("request_page_access", RequestPageAccessReducer),
  __reducerSchema("resolve_page_access_request", ResolvePageAccessRequestReducer),
  __reducerSchema("resolve_structural_finding", ResolveStructuralFindingReducer),
  __reducerSchema("restore_component", RestoreComponentReducer),
  __reducerSchema("restore_page", RestorePageReducer),
  __reducerSchema("restore_page_to_snapshot", RestorePageToSnapshotReducer),
  __reducerSchema("revoke_api_endpoint_key", RevokeApiEndpointKeyReducer),
  __reducerSchema("revoke_auto_apply", RevokeAutoApplyReducer),
  __reducerSchema("revoke_extension_permission", RevokeExtensionPermissionReducer),
  __reducerSchema("run_convention_sensor", RunConventionSensorReducer),
  __reducerSchema("run_denied_tool_calls_sensor", RunDeniedToolCallsSensorReducer),
  __reducerSchema("run_orphan_detector", RunOrphanDetectorReducer),
  __reducerSchema("run_pending_migrations", RunPendingMigrationsReducer),
  __reducerSchema("run_relational_integrity_sensor", RunRelationalIntegritySensorReducer),
  __reducerSchema("run_schema_consistency_sensor", RunSchemaConsistencySensorReducer),
  __reducerSchema("save_component_yjs_state", SaveComponentYjsStateReducer),
  __reducerSchema("save_yjs_state", SaveYjsStateReducer),
  __reducerSchema("seed_agent_instruction_property", SeedAgentInstructionPropertyReducer),
  __reducerSchema("seed_builtin_extensions", SeedBuiltinExtensionsReducer),
  __reducerSchema("seed_sensor_registry", SeedSensorRegistryReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_ai_user_api_key", SetAiUserApiKeyReducer),
  __reducerSchema("set_ai_user_serper_api_key", SetAiUserSerperApiKeyReducer),
  __reducerSchema("set_ai_user_tool_secrets_json", SetAiUserToolSecretsJsonReducer),
  __reducerSchema("set_allow_evaluation_sharing", SetAllowEvaluationSharingReducer),
  __reducerSchema("set_automation_limits", SetAutomationLimitsReducer),
  __reducerSchema("set_automation_mode", SetAutomationModeReducer),
  __reducerSchema("set_block_access_rule", SetBlockAccessRuleReducer),
  __reducerSchema("set_conversation_visibility", SetConversationVisibilityReducer),
  __reducerSchema("set_default_view", SetDefaultViewReducer),
  __reducerSchema("set_extension_enabled", SetExtensionEnabledReducer),
  __reducerSchema("set_mcp_server_api_key", SetMcpServerApiKeyReducer),
  __reducerSchema("set_page_access_rule", SetPageAccessRuleReducer),
  __reducerSchema("set_page_embedding", SetPageEmbeddingReducer),
  __reducerSchema("set_page_hidden", SetPageHiddenReducer),
  __reducerSchema("set_property_value", SetPropertyValueReducer),
  __reducerSchema("set_shared_context", SetSharedContextReducer),
  __reducerSchema("set_user_admin", SetUserAdminReducer),
  __reducerSchema("set_user_preference", SetUserPreferenceReducer),
  __reducerSchema("set_user_profile", SetUserProfileReducer),
  __reducerSchema("submit_result", SubmitResultReducer),
  __reducerSchema("take_snapshot", TakeSnapshotReducer),
  __reducerSchema("take_snapshot_with_content", TakeSnapshotWithContentReducer),
  __reducerSchema("touch_api_endpoint_key", TouchApiEndpointKeyReducer),
  __reducerSchema("uninstall_extension", UninstallExtensionReducer),
  __reducerSchema("update_ai_user_config", UpdateAiUserConfigReducer),
  __reducerSchema("update_ai_user_profile", UpdateAiUserProfileReducer),
  __reducerSchema("update_ai_user_system_prompt", UpdateAiUserSystemPromptReducer),
  __reducerSchema("update_api_endpoint", UpdateApiEndpointReducer),
  __reducerSchema("update_api_field_mapping", UpdateApiFieldMappingReducer),
  __reducerSchema("update_automation_action", UpdateAutomationActionReducer),
  __reducerSchema("update_automation_rule", UpdateAutomationRuleReducer),
  __reducerSchema("update_component_props", UpdateComponentPropsReducer),
  __reducerSchema("update_database_row", UpdateDatabaseRowReducer),
  __reducerSchema("update_database_schema_config", UpdateDatabaseSchemaConfigReducer),
  __reducerSchema("update_extension", UpdateExtensionReducer),
  __reducerSchema("update_message", UpdateMessageReducer),
  __reducerSchema("update_page_content", UpdatePageContentReducer),
  __reducerSchema("update_page_icon", UpdatePageIconReducer),
  __reducerSchema("update_page_title", UpdatePageTitleReducer),
  __reducerSchema("update_property_config", UpdatePropertyConfigReducer),
  __reducerSchema("update_property_type", UpdatePropertyTypeReducer),
  __reducerSchema("update_view_config", UpdateViewConfigReducer),
  __reducerSchema("upsert_harness_template", UpsertHarnessTemplateReducer),
  __reducerSchema("validate_automation", ValidateAutomationReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

