// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MessageFeedbackRating,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  messageId: __t.u64().name("message_id"),
  conversationId: __t.u64().name("conversation_id"),
  rater: __t.identity(),
  get rating() {
    return MessageFeedbackRating;
  },
  note: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
