// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  taskId: __t.u64().name("task_id"),
  taskType: __t.string().name("task_type"),
  agentId: __t.string().name("agent_id"),
  aiUserId: __t.option(__t.u64()).name("ai_user_id"),
  tokensIn: __t.u64().name("tokens_in"),
  tokensOut: __t.u64().name("tokens_out"),
  wallClockMs: __t.u64().name("wall_clock_ms"),
  createdAt: __t.timestamp().name("created_at"),
});
