// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.string().name("user_id"),
  prompt: __t.string(),
  pageId: __t.option(__t.u64()).name("page_id"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  aiUserId: __t.option(__t.u64()).name("ai_user_id"),
  tier: __t.option(__t.string()),
  nonce: __t.option(__t.string()),
  parentJobId: __t.option(__t.u64()).name("parent_job_id"),
  spawnDepth: __t.u32().name("spawn_depth"),
  spawningPrincipal: __t.identity().name("spawning_principal"),
});
