// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  conversationId: __t.u64(),
  jobId: __t.option(__t.u64()),
  taskId: __t.option(__t.u64()),
  agentId: __t.string(),
  installedExtensionId: __t.option(__t.u64()),
  toolName: __t.string(),
  inputHash: __t.string(),
  outputHash: __t.string(),
  outcome: __t.string(),
  outcomeDetail: __t.option(__t.string()),
};
