// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sensorKind: __t.string().name("sensor_kind"),
  code: __t.string(),
  targetKind: __t.string().name("target_kind"),
  targetId: __t.u64().name("target_id"),
  message: __t.string(),
  severity: __t.string(),
  detailsJson: __t.string().name("details_json"),
  createdAt: __t.timestamp().name("created_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
});
