// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ActorType`.
export const ActorType = __t.enum("ActorType", {
  Human: __t.unit(),
  Agent: __t.string(),
});
export type ActorType = __Infer<typeof ActorType>;

export const AiEvaluation = __t.object("AiEvaluation", {
  id: __t.u64(),
  propertyDefinitionId: __t.u64(),
  pageId: __t.u64(),
  inputHash: __t.string(),
  get primitive() {
    return AiPrimitive;
  },
  model: __t.string(),
  promptVersion: __t.u32(),
  output: __t.string(),
  inputTokens: __t.u32(),
  outputTokens: __t.u32(),
  costMicrocents: __t.u64(),
  wallClockMs: __t.u32(),
  createdAt: __t.timestamp(),
  aiUserIdentity: __t.identity(),
  isStale: __t.bool(),
});
export type AiEvaluation = __Infer<typeof AiEvaluation>;

// The tagged union or sum type for the algebraic type `AiPrimitive`.
export const AiPrimitive = __t.enum("AiPrimitive", {
  Classify: __t.unit(),
  Extract: __t.unit(),
  Summarize: __t.unit(),
  Sentiment: __t.unit(),
  Translate: __t.unit(),
});
export type AiPrimitive = __Infer<typeof AiPrimitive>;

export const AiPropertyValue = __t.object("AiPropertyValue", {
  output: __t.string(),
  evaluationId: __t.u64(),
  isStale: __t.bool(),
});
export type AiPropertyValue = __Infer<typeof AiPropertyValue>;

export const AiUserConfig = __t.object("AiUserConfig", {
  id: __t.u64(),
  identity: __t.identity(),
  createdBy: __t.identity(),
  get provider() {
    return InferenceProvider;
  },
  model: __t.string(),
  endpoint: __t.option(__t.string()),
  apiKey: __t.option(__t.string()),
  systemPrompt: __t.option(__t.string()),
  maxTokens: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  monthlyTokenCap: __t.option(__t.u64()),
  get role() {
    return AiUserRole;
  },
  harnessTemplateId: __t.option(__t.u64()),
  allowEvaluationSharing: __t.bool(),
  toolSecretsJson: __t.option(__t.string()),
});
export type AiUserConfig = __Infer<typeof AiUserConfig>;

export const AiUserMemory = __t.object("AiUserMemory", {
  id: __t.u64(),
  aiUserId: __t.u64(),
  rootPageId: __t.u64(),
  workingPageId: __t.option(__t.u64()),
  longTermPageId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  lastConsolidatedAt: __t.option(__t.timestamp()),
});
export type AiUserMemory = __Infer<typeof AiUserMemory>;

export const AiUserProfile = __t.object("AiUserProfile", {
  aiUserId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  avatarUrl: __t.option(__t.string()),
  providerName: __t.string(),
  modelName: __t.string(),
  hasApiKey: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  systemPrompt: __t.option(__t.string()),
});
export type AiUserProfile = __Infer<typeof AiUserProfile>;

// The tagged union or sum type for the algebraic type `AiUserRole`.
export const AiUserRole = __t.enum("AiUserRole", {
  Standard: __t.unit(),
  Reviewer: __t.unit(),
});
export type AiUserRole = __Infer<typeof AiUserRole>;

export const ApiCallLog = __t.object("ApiCallLog", {
  id: __t.u64(),
  endpointId: __t.u64(),
  keyId: __t.option(__t.u64()),
  get method() {
    return HttpMethod;
  },
  path: __t.string(),
  statusCode: __t.u16(),
  latencyMs: __t.u32(),
  callerIp: __t.option(__t.string()),
  errorMessage: __t.option(__t.string()),
  at: __t.timestamp(),
});
export type ApiCallLog = __Infer<typeof ApiCallLog>;

export const ApiEndpoint = __t.object("ApiEndpoint", {
  id: __t.u64(),
  databasePageId: __t.u64(),
  slug: __t.string(),
  displayName: __t.string(),
  description: __t.string(),
  get allowedMethods() {
    return __t.array(HttpMethod);
  },
  requireAuth: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ApiEndpoint = __Infer<typeof ApiEndpoint>;

export const ApiEndpointKey = __t.object("ApiEndpointKey", {
  id: __t.u64(),
  endpointId: __t.u64(),
  keyHash: __t.string(),
  label: __t.string(),
  get allowedMethods() {
    return __t.array(HttpMethod);
  },
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  lastUsedAt: __t.option(__t.timestamp()),
  expiresAt: __t.option(__t.timestamp()),
});
export type ApiEndpointKey = __Infer<typeof ApiEndpointKey>;

export const ApiEndpointKeyLookupRow = __t.object("ApiEndpointKeyLookupRow", {
  id: __t.u64(),
  endpointId: __t.u64(),
  keyHash: __t.string(),
  get allowedMethods() {
    return __t.array(HttpMethod);
  },
  expiresAt: __t.option(__t.timestamp()),
});
export type ApiEndpointKeyLookupRow = __Infer<typeof ApiEndpointKeyLookupRow>;

export const ApiFieldMapping = __t.object("ApiFieldMapping", {
  id: __t.u64(),
  endpointId: __t.u64(),
  propertyDefinitionId: __t.u64(),
  fieldName: __t.string(),
  requiredOnCreate: __t.bool(),
  defaultValue: __t.option(__t.string()),
  readOnly: __t.bool(),
  fieldOrder: __t.u32(),
});
export type ApiFieldMapping = __Infer<typeof ApiFieldMapping>;

export const Attachment = __t.object("Attachment", {
  id: __t.u64(),
  pageId: __t.u64(),
  filename: __t.string(),
  contentType: __t.string(),
  storageKey: __t.string(),
  sizeBytes: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Attachment = __Infer<typeof Attachment>;

// The tagged union or sum type for the algebraic type `AuthScheme`.
export const AuthScheme = __t.enum("AuthScheme", {
  None: __t.unit(),
  ApiKey: __t.unit(),
  OAuth: __t.unit(),
});
export type AuthScheme = __Infer<typeof AuthScheme>;

export const AutoApplyBinding = __t.object("AutoApplyBinding", {
  id: __t.u64(),
  aiUserId: __t.u64(),
  get context() {
    return AutoApplyContext;
  },
  allowedActionKinds: __t.option(__t.array(__t.string())),
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type AutoApplyBinding = __Infer<typeof AutoApplyBinding>;

// The tagged union or sum type for the algebraic type `AutoApplyContext`.
export const AutoApplyContext = __t.enum("AutoApplyContext", {
  Page: __t.u64(),
  Workspace: __t.unit(),
});
export type AutoApplyContext = __Infer<typeof AutoApplyContext>;

export const BlockAccessRule = __t.object("BlockAccessRule", {
  id: __t.u64(),
  pageId: __t.u64(),
  blockId: __t.string(),
  get principal() {
    return Principal;
  },
  get permission() {
    return Permission;
  },
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type BlockAccessRule = __Infer<typeof BlockAccessRule>;

export const Conversation = __t.object("Conversation", {
  id: __t.u64(),
  pageId: __t.option(__t.u64()),
  initiatedBy: __t.identity(),
  get status() {
    return ConversationStatus;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  get visibility() {
    return ConversationVisibility;
  },
});
export type Conversation = __Infer<typeof Conversation>;

export const ConversationMessage = __t.object("ConversationMessage", {
  id: __t.u64(),
  conversationId: __t.u64(),
  get sender() {
    return MessageSender;
  },
  content: __t.string(),
  jobId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  get status() {
    return MessageStatus;
  },
  thinking: __t.option(__t.string()),
  toolCallsJson: __t.option(__t.string()),
  inputTokens: __t.u32(),
  outputTokens: __t.u32(),
  cacheCreationInputTokens: __t.u32(),
  cacheReadInputTokens: __t.u32(),
});
export type ConversationMessage = __Infer<typeof ConversationMessage>;

export const ConversationParticipant = __t.object("ConversationParticipant", {
  id: __t.u64(),
  conversationId: __t.u64(),
  identity: __t.identity(),
  get role() {
    return ParticipantRole;
  },
  joinedAt: __t.timestamp(),
  lastViewedMessageId: __t.option(__t.u64()),
  leftAt: __t.option(__t.timestamp()),
});
export type ConversationParticipant = __Infer<typeof ConversationParticipant>;

// The tagged union or sum type for the algebraic type `ConversationStatus`.
export const ConversationStatus = __t.enum("ConversationStatus", {
  Active: __t.unit(),
  Closed: __t.unit(),
});
export type ConversationStatus = __Infer<typeof ConversationStatus>;

// The tagged union or sum type for the algebraic type `ConversationVisibility`.
export const ConversationVisibility = __t.enum("ConversationVisibility", {
  Private: __t.unit(),
  Participants: __t.unit(),
  PageInheriting: __t.unit(),
});
export type ConversationVisibility = __Infer<typeof ConversationVisibility>;

export const DatabaseRowMarker = __t.object("DatabaseRowMarker", {
  id: __t.u64(),
  clientRequestId: __t.string(),
  pageId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type DatabaseRowMarker = __Infer<typeof DatabaseRowMarker>;

export const DatabaseSchema = __t.object("DatabaseSchema", {
  id: __t.u64(),
  pageId: __t.u64(),
  name: __t.string(),
  config: __t.option(__t.string()),
});
export type DatabaseSchema = __Infer<typeof DatabaseSchema>;

export const DatabaseView = __t.object("DatabaseView", {
  id: __t.u64(),
  pageId: __t.u64(),
  name: __t.string(),
  get viewType() {
    return ViewType;
  },
  config: __t.string(),
  isDefault: __t.bool(),
  ownerIdentity: __t.option(__t.string()),
  get createdBy() {
    return ActorType;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DatabaseView = __Infer<typeof DatabaseView>;

export const ExtensionManifest = __t.object("ExtensionManifest", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  get extensionType() {
    return ExtensionType;
  },
  version: __t.string(),
  authorIdentity: __t.option(__t.identity()),
  manifestJson: __t.string(),
  sourceUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type ExtensionManifest = __Infer<typeof ExtensionManifest>;

export const ExtensionMcpServer = __t.object("ExtensionMcpServer", {
  id: __t.u64(),
  name: __t.string(),
  endpoint: __t.string(),
  get authScheme() {
    return AuthScheme;
  },
  apiKey: __t.option(__t.string()),
  capabilities: __t.array(__t.string()),
  installedBy: __t.identity(),
  enabled: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ExtensionMcpServer = __Infer<typeof ExtensionMcpServer>;

export const ExtensionPermission = __t.object("ExtensionPermission", {
  id: __t.u64(),
  installedExtensionId: __t.u64(),
  get scope() {
    return PermissionScope;
  },
  get action() {
    return PermissionAction;
  },
  allowedDomains: __t.option(__t.string()),
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type ExtensionPermission = __Infer<typeof ExtensionPermission>;

// The tagged union or sum type for the algebraic type `ExtensionType`.
export const ExtensionType = __t.enum("ExtensionType", {
  ConfigBundle: __t.unit(),
  McpServer: __t.unit(),
  Hybrid: __t.unit(),
  Builtin: __t.unit(),
});
export type ExtensionType = __Infer<typeof ExtensionType>;

export const HarnessTemplate = __t.object("HarnessTemplate", {
  id: __t.u64(),
  externalId: __t.string(),
  name: __t.string(),
  description: __t.string(),
  get source() {
    return HarnessTemplateSource;
  },
  systemPrompt: __t.string(),
  get defaultProvider() {
    return InferenceProvider;
  },
  defaultModel: __t.string(),
  defaultMaxTokens: __t.u32(),
  configJson: __t.string(),
  version: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type HarnessTemplate = __Infer<typeof HarnessTemplate>;

// The tagged union or sum type for the algebraic type `HarnessTemplateSource`.
export const HarnessTemplateSource = __t.enum("HarnessTemplateSource", {
  Builtin: __t.unit(),
  Workspace: __t.unit(),
});
export type HarnessTemplateSource = __Infer<typeof HarnessTemplateSource>;

// The tagged union or sum type for the algebraic type `HttpMethod`.
export const HttpMethod = __t.enum("HttpMethod", {
  Get: __t.unit(),
  Post: __t.unit(),
  Patch: __t.unit(),
  Delete: __t.unit(),
});
export type HttpMethod = __Infer<typeof HttpMethod>;

export const IdCounter = __t.object("IdCounter", {
  name: __t.string(),
  value: __t.u64(),
});
export type IdCounter = __Infer<typeof IdCounter>;

// The tagged union or sum type for the algebraic type `InferenceProvider`.
export const InferenceProvider = __t.enum("InferenceProvider", {
  Anthropic: __t.unit(),
  OpenAi: __t.unit(),
  Ollama: __t.unit(),
  OpenAiCompatible: __t.unit(),
});
export type InferenceProvider = __Infer<typeof InferenceProvider>;

// The tagged union or sum type for the algebraic type `InstallStatus`.
export const InstallStatus = __t.enum("InstallStatus", {
  Active: __t.unit(),
  PendingConfirmation: __t.unit(),
});
export type InstallStatus = __Infer<typeof InstallStatus>;

export const InstalledExtension = __t.object("InstalledExtension", {
  id: __t.u64(),
  manifestId: __t.u64(),
  installedBy: __t.identity(),
  get installStatus() {
    return InstallStatus;
  },
  aiUserId: __t.option(__t.u64()),
  mcpServerId: __t.option(__t.u64()),
  enabled: __t.bool(),
  installedAt: __t.timestamp(),
  confirmedAt: __t.option(__t.timestamp()),
});
export type InstalledExtension = __Infer<typeof InstalledExtension>;

// The tagged union or sum type for the algebraic type `MessageSender`.
export const MessageSender = __t.enum("MessageSender", {
  User: __t.identity(),
  System: __t.string(),
});
export type MessageSender = __Infer<typeof MessageSender>;

// The tagged union or sum type for the algebraic type `MessageStatus`.
export const MessageStatus = __t.enum("MessageStatus", {
  Complete: __t.unit(),
  Thinking: __t.unit(),
  ToolUse: __t.unit(),
  Streaming: __t.unit(),
  Error: __t.unit(),
});
export type MessageStatus = __Infer<typeof MessageStatus>;

export const MigrationState = __t.object("MigrationState", {
  key: __t.string(),
  completedAt: __t.timestamp(),
  moduleVersion: __t.string(),
});
export type MigrationState = __Infer<typeof MigrationState>;

export const ModuleInstallMeta = __t.object("ModuleInstallMeta", {
  id: __t.u8(),
  publisherIdentity: __t.identity(),
});
export type ModuleInstallMeta = __Infer<typeof ModuleInstallMeta>;

export const OrchaAgent = __t.object("OrchaAgent", {
  id: __t.string(),
  capabilities: __t.array(__t.string()),
  status: __t.string(),
});
export type OrchaAgent = __Infer<typeof OrchaAgent>;

export const OrchaJob = __t.object("OrchaJob", {
  id: __t.u64(),
  userId: __t.string(),
  prompt: __t.string(),
  pageId: __t.option(__t.u64()),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type OrchaJob = __Infer<typeof OrchaJob>;

export const OrchaSharedContext = __t.object("OrchaSharedContext", {
  id: __t.u64(),
  jobId: __t.u64(),
  key: __t.string(),
  value: __t.string(),
  createdBy: __t.string(),
});
export type OrchaSharedContext = __Infer<typeof OrchaSharedContext>;

export const OrchaTask = __t.object("OrchaTask", {
  id: __t.u64(),
  jobId: __t.u64(),
  description: __t.string(),
  taskType: __t.string(),
  status: __t.string(),
  dependsOn: __t.array(__t.u64()),
  requiredCapabilities: __t.array(__t.string()),
  assignedTo: __t.option(__t.string()),
  result: __t.option(__t.string()),
});
export type OrchaTask = __Infer<typeof OrchaTask>;

export const OrchaUsageEvent = __t.object("OrchaUsageEvent", {
  id: __t.u64(),
  taskId: __t.u64(),
  taskType: __t.string(),
  agentId: __t.string(),
  aiUserId: __t.option(__t.u64()),
  tokensIn: __t.u64(),
  tokensOut: __t.u64(),
  wallClockMs: __t.u64(),
  createdAt: __t.timestamp(),
});
export type OrchaUsageEvent = __Infer<typeof OrchaUsageEvent>;

export const Page = __t.object("Page", {
  id: __t.u64(),
  parentId: __t.option(__t.u64()),
  get pageType() {
    return PageType;
  },
  title: __t.string(),
  sortOrder: __t.u32(),
  embedding: __t.option(__t.array(__t.f32())),
  get createdBy() {
    return ActorType;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
  icon: __t.option(__t.string()),
  parentPk: __t.u64(),
  isHidden: __t.bool(),
});
export type Page = __Infer<typeof Page>;

export const PageAccessRule = __t.object("PageAccessRule", {
  id: __t.u64(),
  pageId: __t.u64(),
  get principal() {
    return Principal;
  },
  get permission() {
    return Permission;
  },
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type PageAccessRule = __Infer<typeof PageAccessRule>;

export const PageContent = __t.object("PageContent", {
  pageId: __t.u64(),
  content: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PageContent = __Infer<typeof PageContent>;

export const PagePropertyValue = __t.object("PagePropertyValue", {
  id: __t.u64(),
  pageId: __t.u64(),
  propertyDefinitionId: __t.u64(),
  get value() {
    return PropertyValue;
  },
});
export type PagePropertyValue = __Infer<typeof PagePropertyValue>;

export const PagePropertyValueHistory = __t.object("PagePropertyValueHistory", {
  id: __t.u64(),
  pageId: __t.u64(),
  propertyDefinitionId: __t.u64(),
  get value() {
    return PropertyValue;
  },
  isCurrent: __t.bool(),
  changedAt: __t.timestamp(),
  get changedBy() {
    return ActorType;
  },
});
export type PagePropertyValueHistory = __Infer<typeof PagePropertyValueHistory>;

export const PageSnapshot = __t.object("PageSnapshot", {
  id: __t.u64(),
  pageId: __t.u64(),
  title: __t.string(),
  content: __t.string(),
  snapshotAt: __t.timestamp(),
  get createdBy() {
    return ActorType;
  },
  get snapshotType() {
    return SnapshotType;
  },
});
export type PageSnapshot = __Infer<typeof PageSnapshot>;

// The tagged union or sum type for the algebraic type `PageType`.
export const PageType = __t.enum("PageType", {
  Doc: __t.unit(),
  Database: __t.unit(),
});
export type PageType = __Infer<typeof PageType>;

export const PageYjsState = __t.object("PageYjsState", {
  pageId: __t.u64(),
  data: __t.byteArray(),
  updatedAt: __t.timestamp(),
});
export type PageYjsState = __Infer<typeof PageYjsState>;

// The tagged union or sum type for the algebraic type `ParticipantRole`.
export const ParticipantRole = __t.enum("ParticipantRole", {
  Initiator: __t.unit(),
  Member: __t.unit(),
});
export type ParticipantRole = __Infer<typeof ParticipantRole>;

// The tagged union or sum type for the algebraic type `Permission`.
export const Permission = __t.enum("Permission", {
  Read: __t.unit(),
  Write: __t.unit(),
});
export type Permission = __Infer<typeof Permission>;

// The tagged union or sum type for the algebraic type `PermissionAction`.
export const PermissionAction = __t.enum("PermissionAction", {
  Read: __t.unit(),
  Write: __t.unit(),
  Edit: __t.unit(),
  Delete: __t.unit(),
  Snapshot: __t.unit(),
  PropertyRead: __t.unit(),
  PropertyWrite: __t.unit(),
  SpawnJob: __t.unit(),
  HttpOutbound: __t.unit(),
});
export type PermissionAction = __Infer<typeof PermissionAction>;

// The tagged union or sum type for the algebraic type `PermissionScope`.
export const PermissionScope = __t.enum("PermissionScope", {
  Page: __t.u64(),
  Subtree: __t.u64(),
  Workspace: __t.unit(),
});
export type PermissionScope = __Infer<typeof PermissionScope>;

// The tagged union or sum type for the algebraic type `Principal`.
export const Principal = __t.enum("Principal", {
  WorkspaceMember: __t.identity(),
});
export type Principal = __Infer<typeof Principal>;

export const PropertyDefinition = __t.object("PropertyDefinition", {
  id: __t.u64(),
  schemaId: __t.u64(),
  name: __t.string(),
  get propertyType() {
    return PropertyType;
  },
  config: __t.string(),
  order: __t.u32(),
});
export type PropertyDefinition = __Infer<typeof PropertyDefinition>;

// The tagged union or sum type for the algebraic type `PropertyType`.
export const PropertyType = __t.enum("PropertyType", {
  Text: __t.unit(),
  Number: __t.unit(),
  Date: __t.unit(),
  Select: __t.unit(),
  MultiSelect: __t.unit(),
  Relation: __t.unit(),
  Checkbox: __t.unit(),
  Url: __t.unit(),
  Person: __t.unit(),
  Ai: __t.unit(),
});
export type PropertyType = __Infer<typeof PropertyType>;

// The tagged union or sum type for the algebraic type `PropertyValue`.
export const PropertyValue = __t.enum("PropertyValue", {
  Text: __t.string(),
  Number: __t.f64(),
  Date: __t.u64(),
  Select: __t.string(),
  MultiSelect: __t.array(__t.string()),
  Relation: __t.array(__t.u64()),
  Checkbox: __t.bool(),
  Url: __t.string(),
  Person: __t.array(__t.string()),
  get Ai() {
    return AiPropertyValue;
  },
});
export type PropertyValue = __Infer<typeof PropertyValue>;

export const PropertyValueInput = __t.object("PropertyValueInput", {
  propertyDefinitionId: __t.u64(),
  get value() {
    return PropertyValue;
  },
});
export type PropertyValueInput = __Infer<typeof PropertyValueInput>;

export const ReviewAgentBinding = __t.object("ReviewAgentBinding", {
  id: __t.u64(),
  reviewerAiUserId: __t.u64(),
  get subject() {
    return ReviewSubject;
  },
  get mode() {
    return ReviewMode;
  },
  failOpen: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ReviewAgentBinding = __Infer<typeof ReviewAgentBinding>;

export const ReviewAnnotation = __t.object("ReviewAnnotation", {
  id: __t.u64(),
  snapshotId: __t.u64(),
  reviewerAiUserId: __t.u64(),
  get severity() {
    return ReviewSeverity;
  },
  comment: __t.string(),
  createdAt: __t.timestamp(),
});
export type ReviewAnnotation = __Infer<typeof ReviewAnnotation>;

// The tagged union or sum type for the algebraic type `ReviewMode`.
export const ReviewMode = __t.enum("ReviewMode", {
  Pre: __t.unit(),
  Post: __t.unit(),
});
export type ReviewMode = __Infer<typeof ReviewMode>;

// The tagged union or sum type for the algebraic type `ReviewSeverity`.
export const ReviewSeverity = __t.enum("ReviewSeverity", {
  Pass: __t.unit(),
  Warn: __t.unit(),
  Fail: __t.unit(),
});
export type ReviewSeverity = __Infer<typeof ReviewSeverity>;

// The tagged union or sum type for the algebraic type `ReviewSubject`.
export const ReviewSubject = __t.enum("ReviewSubject", {
  AiUser: __t.u64(),
  Workspace: __t.unit(),
});
export type ReviewSubject = __Infer<typeof ReviewSubject>;

export const SensorRegistry = __t.object("SensorRegistry", {
  id: __t.u64(),
  sensorKind: __t.string(),
  code: __t.string(),
  displayName: __t.string(),
  description: __t.string(),
  defaultSeverity: __t.string(),
});
export type SensorRegistry = __Infer<typeof SensorRegistry>;

// The tagged union or sum type for the algebraic type `SnapshotType`.
export const SnapshotType = __t.enum("SnapshotType", {
  Manual: __t.unit(),
  Periodic: __t.unit(),
  PreAgentEdit: __t.unit(),
  PostAgentEdit: __t.unit(),
});
export type SnapshotType = __Infer<typeof SnapshotType>;

export const StructuralSensorFinding = __t.object("StructuralSensorFinding", {
  id: __t.u64(),
  sensorKind: __t.string(),
  code: __t.string(),
  targetKind: __t.string(),
  targetId: __t.u64(),
  message: __t.string(),
  severity: __t.string(),
  detailsJson: __t.string(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
});
export type StructuralSensorFinding = __Infer<typeof StructuralSensorFinding>;

export const ToolCallAuditLog = __t.object("ToolCallAuditLog", {
  id: __t.u64(),
  conversationId: __t.u64(),
  jobId: __t.option(__t.u64()),
  taskId: __t.option(__t.u64()),
  agentId: __t.string(),
  installedExtensionId: __t.option(__t.u64()),
  toolName: __t.string(),
  inputHash: __t.string(),
  outputHash: __t.string(),
  outcome: __t.string(),
  outcomeDetail: __t.option(__t.string()),
  calledAt: __t.timestamp(),
});
export type ToolCallAuditLog = __Infer<typeof ToolCallAuditLog>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  email: __t.string(),
  isAuthenticated: __t.bool(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  isAdmin: __t.bool(),
});
export type User = __Infer<typeof User>;

export const UserCredential = __t.object("UserCredential", {
  email: __t.string(),
  name: __t.string(),
  passwordHash: __t.string(),
  createdAt: __t.timestamp(),
});
export type UserCredential = __Infer<typeof UserCredential>;

export const UserPreference = __t.object("UserPreference", {
  id: __t.u64(),
  identity: __t.identity(),
  key: __t.string(),
  valueJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type UserPreference = __Infer<typeof UserPreference>;

// The tagged union or sum type for the algebraic type `ViewType`.
export const ViewType = __t.enum("ViewType", {
  Grid: __t.unit(),
  List: __t.unit(),
  Kanban: __t.unit(),
  Calendar: __t.unit(),
  Gallery: __t.unit(),
});
export type ViewType = __Infer<typeof ViewType>;

