// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  PropertyValueInput,
} from "./types";

export default {
  pageId: __t.u64(),
  title: __t.option(__t.string()),
  get setValues() {
    return __t.array(PropertyValueInput);
  },
  clearValues: __t.array(__t.u64()),
};
