// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  mappingId: __t.u64(),
  fieldName: __t.string(),
  requiredOnCreate: __t.bool(),
  defaultValue: __t.option(__t.string()),
  readOnly: __t.bool(),
  fieldOrder: __t.u32(),
};
