// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  InferenceProvider,
} from "./types";

export default {
  id: __t.option(__t.u64()),
  name: __t.string(),
  description: __t.string(),
  systemPrompt: __t.string(),
  get defaultProvider() {
    return InferenceProvider;
  },
  defaultModel: __t.string(),
  defaultMaxTokens: __t.u32(),
  configJson: __t.string(),
};
